-- ============================================================================
-- Digi_TransX — Supabase PostgreSQL Schema
-- ============================================================================
-- Complete schema for the platform: tables, indexes, helper functions,
-- triggers, Row Level Security policies, seed data, and the private
-- 'shipment-documents' Storage bucket.
--
-- Naming notes:
--   - Some COLUMN names keep the Flask app's established naming
--     (truck_number, client_user_id, order_id, ...) — the backend queries
--     depend on them. Table names follow the current design
--     (vehicles, shipments, shipment_bids, payments, ...).
--   - Status columns are TEXT (not enums) because the app uses many workflow
--     statuses (on_job, delivery_claimed, dispute_pending, ...).
--
-- Run once on a fresh Supabase project (SQL Editor or `supabase db push`).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. EXTENSIONS
-- ---------------------------------------------------------------------------
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. ROLE ENUM (used by RLS)
-- ---------------------------------------------------------------------------
-- Legacy app roles map as:
--   platform_admin                          -> admin
--   client / service_seeker / everyday_user -> customer
--   transporter / logistics_provider        -> transporter
--   (new operational role)                  -> dispatcher
-- The original legacy role string is preserved in users.legacy_role and is
-- what the Flask app logic keeps using.
create type public.app_role as enum
    ('admin', 'dispatcher', 'customer', 'transporter',
     'fuel_station_manager', 'shopkeeper');

-- ---------------------------------------------------------------------------
-- 2. CORE TABLES
-- ---------------------------------------------------------------------------

-- 2.1 USERS -----------------------------------------------------------------
-- Core identity only. Role-specific data lives in the per-role profile
-- tables below (customers / transporter_profiles / fuel_station_profiles /
-- shopkeeper_profiles) — one row per user id, no duplication.
create table public.users (
    id              bigint generated by default as identity primary key,
    auth_id         uuid unique references auth.users (id) on delete set null,
    full_name       text not null default '',
    email           text not null unique,
    phone           text not null default '',
    cnic            text not null unique,
    role            public.app_role not null default 'customer',
    legacy_role     text,                      -- original role string the app logic uses
    city            text,
    address         text,
    about           text,
    mpin_hash       text,
    mpin_enabled    boolean not null default false,
    settings_json   jsonb not null default '{}'::jsonb,
    is_blocked      boolean not null default false,
    block_reason    text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    last_login_at   timestamptz
);

-- 2.2 CUSTOMERS (clients who NEED transport) --------------------------------
-- customer_type = 'business'   : service seekers — companies that book
--                                transport almost daily; history matters.
-- customer_type = 'individual' : everyday users — occasional, simple flow.
create table public.customers (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    customer_type   text,                      -- 'individual' | 'business'
    company_name    text,
    business_type   text,
    transport_need  text,
    default_pickup_city  text,
    default_pickup_area  text,
    billing_address text,
    total_shipments integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.2b TRANSPORTER PROFILES (fleet owners who PROVIDE transport) -------------
create table public.transporter_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    company_name    text,
    fleet_size      text,
    withdrawal_tier integer not null default 0,
    withdrawal_tier_expires_at text,
    payout_card_number text,
    payout_card_holder text,
    payout_card_expiry text,
    payout_card_bank   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.2c FUEL STATION PROFILES (future feature — kept clean from day one) ------
create table public.fuel_station_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    station_name    text,
    pumps_count     text,
    license_no      text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.2d SHOPKEEPER PROFILES (future feature — kept clean from day one) --------
create table public.shopkeeper_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    shop_name       text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.2e COMMISSION POLICIES (versioned, append-only, immutable) ----------------
-- Two completely independent policy types: 'one_time_order' and 'agreement'.
-- Admin changes append a new version; published rows are never edited.
create table public.commission_policies (
    id              bigint generated by default as identity primary key,
    policy_type     text not null
                    check (policy_type in ('one_time_order', 'agreement')),
    version_number  integer not null check (version_number >= 1),
    -- numeric(5,2) enforces max two decimal places at the database level
    company_share_percent     numeric(5,2) not null
                    check (company_share_percent >= 0 and company_share_percent < 100),
    transporter_share_percent numeric(5,2) not null
                    check (transporter_share_percent > 0 and transporter_share_percent <= 100),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    created_by_admin_user_id bigint references public.users (id) on delete set null,
    created_at      timestamptz not null default now(),
    constraint commission_policies_type_version_unique unique (policy_type, version_number),
    constraint commission_policies_shares_sum_100
        check (company_share_percent + transporter_share_percent = 100)
);

-- 2.2f PLATFORM TERMS VERSIONS (versioned, append-only, immutable) ------------
create table public.terms_versions (
    id              bigint generated by default as identity primary key,
    version_number  integer not null unique check (version_number >= 1),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    one_time_policy_id  bigint not null references public.commission_policies (id),
    agreement_policy_id bigint not null references public.commission_policies (id),
    published_by_admin_user_id bigint references public.users (id) on delete set null,
    published_at    timestamptz not null default now()
);

-- 2.2g TERMS ACKNOWLEDGEMENTS (one row per user per Terms version) ------------
create table public.terms_acknowledgements (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null references public.users (id) on delete cascade,
    terms_version_id bigint not null references public.terms_versions (id) on delete cascade,
    acknowledged_at timestamptz not null default now(),
    constraint terms_ack_user_version_unique unique (user_id, terms_version_id)
);

-- Immutability guard: published versions can never be edited or deleted
-- (applies to every connection, including the backend service role).
create or replace function public.prevent_version_mutation()
returns trigger language plpgsql as $$
begin
    raise exception 'published % rows are immutable — publish a new version instead', tg_table_name;
end;
$$;

create trigger trg_commission_policies_immutable
    before update or delete on public.commission_policies
    for each row execute function public.prevent_version_mutation();

create trigger trg_terms_versions_immutable
    before update or delete on public.terms_versions
    for each row execute function public.prevent_version_mutation();

-- Seed both commission types at 20% company / 80% transporter + Terms v1.
insert into public.commission_policies
    (policy_type, version_number, company_share_percent, transporter_share_percent, change_summary)
values
    ('one_time_order', 1, 20.00, 80.00,
     'Initial platform commission rate (20% company / 80% transporter).'),
    ('agreement', 1, 20.00, 80.00,
     'Initial platform commission rate (20% company / 80% transporter).');

insert into public.terms_versions
    (version_number, change_summary, one_time_policy_id, agreement_policy_id)
values
    (1,
     'Initial platform Terms: 20% company / 80% transporter for both one-time orders and agreements.',
     (select id from public.commission_policies
       where policy_type = 'one_time_order' and version_number = 1),
     (select id from public.commission_policies
       where policy_type = 'agreement' and version_number = 1));

-- 2.3 DRIVERS ---------------------------------------------------------------
create table public.drivers (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null references public.users (id) on delete cascade,
    full_name       text not null,
    cnic            text,
    phone           text,
    license_no      text,
    status          text not null default 'active',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.4 VEHICLES (was: trucks — legacy column names kept) ----------------------
create table public.vehicles (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null references public.users (id) on delete cascade,
    driver_id       bigint references public.drivers (id) on delete set null,
    truck_number    text not null,
    truck_company   text,
    truck_model     text,
    truck_type      text not null,
    catalog_type_key text,
    chassis_number  text not null,
    capacity_tons   numeric not null,
    main_use        text not null,
    payload_min_tons numeric,
    payload_max_tons numeric,
    volume_min_cbm  numeric,
    volume_max_cbm  numeric,
    bed_length_ft   numeric,
    bed_width_ft    numeric,
    bed_height_ft   numeric,
    body_style      text,
    catalog_specs_json jsonb,
    driver_name     text,
    driver_cnic     text,
    tracking_id     text,
    traccar_device_id text,
    status          text not null default 'inactive',   -- active|inactive|on_job|maintenance|blocked
    status_reason_code text,
    status_reason   text,
    operating_provinces text,
    per_km_rate     numeric,
    waiting_charge_per_hour numeric,
    loading_charge  numeric,
    refrigeration_supported boolean not null default false,
    hazardous_supported     boolean not null default false,
    fragile_supported       boolean not null default false,
    truck_photo_path     text,   -- storage path in the shipment-documents bucket
    insurance_photo_path text,
    rc_book_photo_path   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create unique index vehicles_truck_number_unique
    on public.vehicles (lower(trim(truck_number)));
create unique index vehicles_chassis_number_unique
    on public.vehicles (lower(trim(chassis_number)));

-- 2.5 SHIPMENTS (was: orders — legacy column names kept) ---------------------
create table public.shipments (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null references public.users (id) on delete cascade,
    pickup_city     text not null,
    pickup_area     text not null default '',
    pickup_location text,
    pickup_lat      double precision,
    pickup_lng      double precision,
    dropoff_city    text not null,
    dropoff_area    text not null default '',
    dropoff_location text,
    dropoff_lat     double precision,
    dropoff_lng     double precision,
    pickup_date     date not null,
    pickup_time     text not null,
    goods_type      text not null,
    goods_category  text,
    goods_form      text,
    goods_commodity text,
    goods_weight_tons numeric not null,
    goods_volume_cbm  numeric,
    length_cm       numeric,
    width_cm        numeric,
    height_cm       numeric,
    volume_liters   numeric,
    quantity        integer,
    animal_count    integer,
    temperature_c   numeric,
    required_truck_types text,                 -- JSON array string (legacy format)
    is_refrigerated boolean not null default false,
    is_hazardous    boolean not null default false,
    is_food_grade   boolean not null default false,
    estimated_budget numeric,
    notes           text,
    status          text not null default 'open',
    accepted_bid_id bigint,                    -- FK added after shipment_bids
    payment_amount  numeric,
    payment_status  text not null default 'pending',
    -- Commission snapshot: saved when a bid is accepted; payouts always use
    -- these values, never the latest global policy.
    company_share_percent_snapshot     numeric(5,2),
    transporter_share_percent_snapshot numeric(5,2),
    commission_policy_id bigint references public.commission_policies (id),
    terms_version_id     bigint references public.terms_versions (id),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.6 SHIPMENT BIDS (was: order_bids) ---------------------------------------
create table public.shipment_bids (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references public.shipments (id) on delete cascade,
    transporter_user_id bigint not null references public.users (id) on delete cascade,
    truck_id        bigint not null references public.vehicles (id) on delete cascade,
    bid_price       numeric not null,
    message         text,
    status          text not null default 'pending',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table public.shipments
    add constraint shipments_accepted_bid_fk
    foreign key (accepted_bid_id) references public.shipment_bids (id) on delete set null;

-- 2.7 SHIPMENT TRIPS (was: order_trips) -------------------------------------
create table public.shipment_trips (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references public.shipments (id) on delete cascade,
    accepted_bid_id bigint not null references public.shipment_bids (id),
    transporter_user_id bigint not null references public.users (id),
    truck_id        bigint not null references public.vehicles (id),
    status          text not null default 'accepted',
    trip_started_at timestamptz,
    trip_completed_at timestamptz,
    delivery_confirmed_at timestamptz,
    pickup_location_lat  double precision,
    pickup_location_lng  double precision,
    dropoff_location_lat double precision,
    dropoff_location_lng double precision,
    actual_distance_km   numeric,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.8 SHIPMENT STATUS HISTORY (new — automatic audit trail) ------------------
create table public.shipment_status_history (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    old_status      text,
    new_status      text not null,
    changed_by      bigint references public.users (id),
    note            text,
    created_at      timestamptz not null default now()
);

-- 2.9 DOCUMENTS -------------------------------------------------------------
-- Metadata for files stored in the 'shipment-documents' Storage bucket.
create table public.documents (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null references public.users (id) on delete cascade,
    shipment_id     bigint references public.shipments (id) on delete cascade,
    vehicle_id      bigint references public.vehicles (id) on delete cascade,
    doc_type        text not null default 'other',
        -- vehicle_photo | insurance | rc_book | invoice_pdf | proof_of_delivery | chat_media | other
    storage_path    text not null,
    file_name       text,
    mime_type       text,
    size_bytes      bigint,
    created_at      timestamptz not null default now()
);

-- 2.10 PAYMENTS (was: order_invoices — legacy column names kept) -------------
create table public.payments (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    shipment_id     bigint references public.shipments (id) on delete set null,
    invoice_number  text not null unique,
    client_user_id  bigint not null references public.users (id),
    transporter_user_id bigint not null references public.users (id),
    bid_price       numeric not null,
    company_fee     numeric not null,
    transporter_amount numeric not null,
    -- Audit trail: commission split actually applied to this invoice.
    company_share_percent     numeric(5,2),
    transporter_share_percent numeric(5,2),
    commission_policy_id bigint references public.commission_policies (id),
    payment_method  text not null default 'wallet',
    status          text not null default 'paid',
    pdf_path        text,
    paid_at         timestamptz,
    created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. SUPPORTING TABLES (existing backend features)
-- ---------------------------------------------------------------------------

-- 3.1 Wallet ----------------------------------------------------------------
create table public.wallets (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    role            text not null,
    balance         numeric not null default 0,
    locked_balance  numeric not null default 0,
    minimum_required numeric not null default 0,
    is_minimum_met  boolean not null default false,
    completed_trips_count integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.wallet_transactions (
    id              bigint generated by default as identity primary key,
    wallet_id       bigint not null references public.wallets (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    type            text not null,
    amount          numeric not null,
    gross_amount    numeric,
    gateway_fee     numeric default 0,
    description     text,
    reference_id    text,
    balance_after   numeric not null,
    created_at      timestamptz not null default now()
);

create table public.wallet_withdrawal_requests (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null references public.users (id) on delete cascade,
    amount          numeric not null,
    status          text not null default 'pending',
    requested_at    timestamptz not null default now(),
    resolved_at     timestamptz,
    processed_at    timestamptz
);

-- 3.2 Shipment ops ----------------------------------------------------------
create table public.shipment_trip_verification (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    transporter_claim_at timestamptz,
    client_first_response text,
    client_first_response_at timestamptz,
    client_second_response text,
    client_second_response_at timestamptz,
    final_verification_status text,
    admin_decision_by bigint references public.users (id),
    admin_decision  text,
    admin_decided_at timestamptz,
    admin_note      text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.shipment_no_show_tracking (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    notification_count integer not null default 0,
    call_count      integer not null default 0,
    last_notification_at timestamptz,
    last_call_at    timestamptz,
    order_deactivated_at timestamptz,
    status          text not null default 'tracking',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.shipment_cancellations (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references public.shipments (id) on delete cascade,
    cancelled_by    text not null,
    reason          text,
    refund_amount   numeric,
    penalty_amount  numeric,
    status          text not null default 'pending',
    created_at      timestamptz not null default now()
);

create table public.shipment_notifications (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references public.shipments (id) on delete cascade,
    trip_id         bigint references public.shipment_trips (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    notification_type text not null,
    message         text,
    is_read         boolean not null default false,
    created_at      timestamptz not null default now()
);

-- 3.3 Chat ------------------------------------------------------------------
create table public.chat_threads (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null references public.users (id) on delete cascade,
    transporter_user_id bigint not null references public.users (id) on delete cascade,
    agreement_post_id bigint,                  -- FK added after agreement_posts
    agreement_bid_id  bigint,
    is_group_chat   boolean not null default false,
    admin_user_id   bigint references public.users (id),
    dispute_trip_id bigint,
    last_message_at timestamptz,
    created_at      timestamptz not null default now(),
    unique (agreement_post_id, transporter_user_id)
);

create table public.chat_messages (
    id              bigint generated by default as identity primary key,
    thread_id       bigint not null references public.chat_threads (id) on delete cascade,
    sender_user_id  bigint not null references public.users (id) on delete cascade,
    message_type    text not null default 'text',
    content         text,
    media_path      text,                      -- storage path (uploads/chat/<file>)
    media_document_id bigint references public.documents (id) on delete set null,
    media_request_status text,
    is_read         boolean not null default false,
    created_at      timestamptz not null default now()
);

-- 3.4 Agreements ------------------------------------------------------------
create table public.agreement_posts (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null references public.users (id) on delete cascade,
    title           text not null,
    cargo_type      text not null,
    service_area    text not null,
    pickup_location text,
    dropoff_location text,
    status          text not null default 'open',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table public.chat_threads
    add constraint chat_threads_agreement_post_fk
    foreign key (agreement_post_id) references public.agreement_posts (id) on delete set null;

create table public.agreement_post_trucks (
    id              bigint generated by default as identity primary key,
    post_id         bigint not null references public.agreement_posts (id) on delete cascade,
    truck_type      text not null,
    capacity_tons   numeric not null,
    quantity        integer not null
);

create table public.agreement_bids (
    id              bigint generated by default as identity primary key,
    post_id         bigint not null references public.agreement_posts (id) on delete cascade,
    transporter_user_id bigint not null references public.users (id) on delete cascade,
    status          text not null default 'pending',
    message         text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table public.chat_threads
    add constraint chat_threads_agreement_bid_fk
    foreign key (agreement_bid_id) references public.agreement_bids (id) on delete set null;

create table public.agreement_bid_trucks (
    id              bigint generated by default as identity primary key,
    bid_id          bigint not null references public.agreement_bids (id) on delete cascade,
    truck_id        bigint not null references public.vehicles (id) on delete cascade,
    per_km_rate     numeric not null,
    minimum_monthly_guarantee numeric not null
);

create table public.agreements (
    id              bigint generated by default as identity primary key,
    post_id         bigint not null references public.agreement_posts (id),
    client_user_id  bigint not null references public.users (id),
    duration_months integer not null,
    cargo_type      text not null,
    service_area    text not null,
    start_date      date not null,
    end_date        date not null,
    status          text not null default 'active',
    contract_text   text,
    -- Commission snapshot: saved when the agreement is finalized; every
    -- monthly payment uses these values for the agreement's entire lifetime.
    company_share_percent_snapshot     numeric(5,2),
    transporter_share_percent_snapshot numeric(5,2),
    commission_policy_id bigint references public.commission_policies (id),
    terms_version_id     bigint references public.terms_versions (id),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.agreement_trucks (
    id              bigint generated by default as identity primary key,
    agreement_id    bigint not null references public.agreements (id) on delete cascade,
    truck_id        bigint not null references public.vehicles (id),
    transporter_user_id bigint not null references public.users (id),
    per_km_rate     numeric not null,
    minimum_monthly_guarantee numeric not null,
    status          text not null default 'active'
);

create table public.agreement_trips (
    id              bigint generated by default as identity primary key,
    agreement_id    bigint not null references public.agreements (id) on delete cascade,
    agreement_truck_id bigint not null references public.agreement_trucks (id),
    truck_id        bigint not null references public.vehicles (id),
    transporter_user_id bigint not null references public.users (id),
    pickup_description text not null,
    pickup_location text,
    dropoff_location text,
    trip_date       date not null,
    gps_start_lat   double precision,
    gps_start_lng   double precision,
    gps_end_lat     double precision,
    gps_end_lng     double precision,
    distance_km     numeric,
    distance_source text,
    started_at      timestamptz,
    ended_at        timestamptz,
    status          text not null default 'pending',
    client_acknowledged boolean not null default false,
    admin_decision  text,
    admin_note      text,
    admin_decided_at timestamptz,
    admin_decided_by bigint references public.users (id),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz
);

create table public.agreement_monthly_payments (
    id              bigint generated by default as identity primary key,
    agreement_id    bigint not null references public.agreements (id) on delete cascade,
    agreement_truck_id bigint not null references public.agreement_trucks (id),
    transporter_user_id bigint not null references public.users (id),
    client_user_id  bigint not null references public.users (id),
    month_year      text not null,
    total_km        numeric not null default 0,
    total_earned    numeric not null default 0,
    minimum_guarantee numeric not null,
    final_amount    numeric not null,
    company_fee     numeric not null,
    transporter_amount numeric not null,
    -- Audit trail: commission split actually applied to this payment.
    company_share_percent     numeric(5,2),
    transporter_share_percent numeric(5,2),
    commission_policy_id bigint references public.commission_policies (id),
    penalty_amount  numeric not null default 0,
    status          text not null default 'pending',
    payment_due_date date not null,
    paid_at         timestamptz,
    created_at      timestamptz not null default now()
);

create table public.agreement_payment_penalties (
    id              bigint generated by default as identity primary key,
    monthly_payment_id bigint not null references public.agreement_monthly_payments (id) on delete cascade,
    client_user_id  bigint not null references public.users (id),
    penalty_amount  numeric not null default 5000,
    penalty_number  integer not null,
    applied_at      timestamptz not null default now()
);

-- 3.5 Auth support / audit --------------------------------------------------
-- Passwords live in Supabase Auth. The app's own OTP flow (email codes with
-- attempt limits) is kept, so its two tables stay with the legacy layout.
create table public.password_reset_otps (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null references public.users (id) on delete cascade,
    purpose         text not null,
    otp_hash        text not null,
    expires_at_iso  text not null,
    created_at      timestamptz not null default now(),
    created_at_iso  text not null default '',
    attempts        integer not null default 0,
    max_attempts    integer not null default 5,
    verified        integer not null default 0,
    cooldown_until_iso text,
    delivery_target text not null
);

create table public.reset_tokens (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null references public.users (id) on delete cascade,
    purpose         text not null,
    token_hash      text not null,
    expires_at_iso  text not null,
    created_at_iso  text not null default '',
    used            integer not null default 0
);

create table public.login_activity (
    id              bigint generated by default as identity primary key,
    user_id         bigint references public.users (id) on delete set null,
    login_identifier text,
    login_method    text,
    status          text not null,
    failure_reason  text,
    ip_address      text,
    user_agent      text,
    created_at      timestamptz not null default now()
);

create table public.trusted_devices (
    id              bigint generated by default as identity primary key,
    device_token    text not null unique,
    user_id         bigint not null references public.users (id) on delete cascade,
    created_at      timestamptz not null default now(),
    last_seen_at    timestamptz not null default now()
);

create table public.user_action_logs (
    id              bigint generated by default as identity primary key,
    user_id         text,                      -- legacy: stored as text by the app
    user_email      text,
    user_role       text,
    action_type     text,
    action_name     text,
    page_url        text,
    payload_json    jsonb,
    created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 4. INDEXES
-- ---------------------------------------------------------------------------
create index idx_shipments_client_status     on public.shipments (client_user_id, status, created_at desc);
create index idx_shipments_status_created    on public.shipments (status, created_at desc);
create index idx_shipment_bids_order         on public.shipment_bids (order_id, status, created_at desc);
create index idx_shipment_bids_transporter   on public.shipment_bids (transporter_user_id, created_at desc);
create index idx_shipment_trips_order        on public.shipment_trips (order_id, status);
create index idx_shipment_trips_transporter  on public.shipment_trips (transporter_user_id, status, created_at desc);
create index idx_trip_verification_trip      on public.shipment_trip_verification (trip_id);
create index idx_status_history_shipment     on public.shipment_status_history (shipment_id, created_at desc);
create index idx_documents_shipment          on public.documents (shipment_id);
create index idx_documents_vehicle           on public.documents (vehicle_id);
create index idx_documents_owner             on public.documents (owner_user_id);
create index idx_payments_client             on public.payments (client_user_id, created_at desc);
create index idx_payments_transporter        on public.payments (transporter_user_id, created_at desc);
create index idx_vehicles_owner              on public.vehicles (owner_user_id, status);
create index idx_drivers_owner               on public.drivers (owner_user_id);
create index idx_wallet_tx_user_created      on public.wallet_transactions (user_id, created_at desc);
create index idx_wallet_tx_wallet_created    on public.wallet_transactions (wallet_id, created_at desc);
create index idx_withdrawals_user_status     on public.wallet_withdrawal_requests (user_id, status, requested_at desc);
create index idx_chat_threads_client_last    on public.chat_threads (client_user_id, last_message_at desc);
create index idx_chat_threads_transp_last    on public.chat_threads (transporter_user_id, last_message_at desc);
create index idx_chat_messages_thread        on public.chat_messages (thread_id, id);
create index idx_chat_messages_thread_read   on public.chat_messages (thread_id, is_read, sender_user_id);
create index idx_agr_posts_client_status     on public.agreement_posts (client_user_id, status, created_at desc);
create index idx_agr_post_trucks_post_type   on public.agreement_post_trucks (post_id, truck_type);
create index idx_agr_bids_post_transporter   on public.agreement_bids (post_id, transporter_user_id, status);
create index idx_agr_trucks_agr_transporter  on public.agreement_trucks (agreement_id, transporter_user_id);
create index idx_agr_trips_agr_truck         on public.agreement_trips (agreement_id, truck_id, status);
create index idx_agr_payments_due_status     on public.agreement_monthly_payments (status, payment_due_date);
create index idx_notifications_user_created  on public.shipment_notifications (user_id, created_at desc);
create index idx_login_activity_user         on public.login_activity (user_id, id desc);
create index idx_otps_user_purpose           on public.password_reset_otps (user_id, purpose, id desc);
create index idx_reset_tokens_user_purpose   on public.reset_tokens (user_id, purpose, used);
create index idx_commission_policies_type_version
    on public.commission_policies (policy_type, version_number desc);
create index idx_terms_versions_version       on public.terms_versions (version_number desc);
create index idx_terms_ack_version            on public.terms_acknowledgements (terms_version_id);
create index idx_shipments_commission_policy  on public.shipments (commission_policy_id);
create index idx_agreements_commission_policy on public.agreements (commission_policy_id);

-- ---------------------------------------------------------------------------
-- 5. HELPER FUNCTIONS (used by RLS)
-- ---------------------------------------------------------------------------
create or replace function public.current_app_user_id()
returns bigint
language sql stable security definer set search_path = public
as $$
    select id from public.users where auth_id = auth.uid();
$$;

create or replace function public.current_app_role()
returns public.app_role
language sql stable security definer set search_path = public
as $$
    select role from public.users where auth_id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
    select coalesce(public.current_app_role() = 'admin', false);
$$;

create or replace function public.is_dispatcher()
returns boolean
language sql stable security definer set search_path = public
as $$
    select coalesce(public.current_app_role() = 'dispatcher', false);
$$;

-- ---------------------------------------------------------------------------
-- 6. TRIGGERS
-- ---------------------------------------------------------------------------
-- 6.1 updated_at maintenance
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

do $$
declare t text;
begin
    foreach t in array array[
        'users','customers','transporter_profiles','fuel_station_profiles',
        'shopkeeper_profiles','drivers','vehicles','shipments','shipment_bids',
        'shipment_trips','shipment_trip_verification','shipment_no_show_tracking',
        'wallets','agreement_posts','agreement_bids','agreements'
    ] loop
        execute format(
            'create trigger trg_%I_updated_at before update on public.%I
             for each row execute function public.set_updated_at()', t, t);
    end loop;
end $$;

-- 6.2 Automatic shipment status history
create or replace function public.log_shipment_status_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if tg_op = 'INSERT' then
        insert into public.shipment_status_history (shipment_id, old_status, new_status, changed_by)
        values (new.id, null, new.status, public.current_app_user_id());
    elsif new.status is distinct from old.status then
        insert into public.shipment_status_history (shipment_id, old_status, new_status, changed_by)
        values (new.id, old.status, new.status, public.current_app_user_id());
    end if;
    return new;
end;
$$;

create trigger trg_shipments_status_history
    after insert or update of status on public.shipments
    for each row execute function public.log_shipment_status_change();

-- 6.3 Auto-create/link public.users profile on Supabase Auth signup
create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
    v_legacy text := coalesce(new.raw_user_meta_data ->> 'legacy_role',
                              new.raw_user_meta_data ->> 'role', '');
    v_role public.app_role;
begin
    v_role := case lower(v_legacy)
        when 'platform_admin' then 'admin'::public.app_role
        when 'logistics_provider' then 'transporter'::public.app_role
        when 'transporter' then 'transporter'::public.app_role
        when 'fuel_station_manager' then 'fuel_station_manager'::public.app_role
        when 'shopkeeper' then 'shopkeeper'::public.app_role
        when 'dispatcher' then 'dispatcher'::public.app_role
        else 'customer'::public.app_role
    end;
    insert into public.users (auth_id, email, full_name, phone, cnic, role, legacy_role)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.raw_user_meta_data ->> 'phone', ''),
        coalesce(nullif(new.raw_user_meta_data ->> 'cnic', ''), 'PENDING-' || new.id::text),
        v_role,
        nullif(v_legacy, '')
    )
    on conflict (email) do update set auth_id = excluded.auth_id;
    return new;
end;
$$;

create trigger trg_on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------
-- NOTE: the Flask backend uses the service_role key, which BYPASSES RLS.
-- These policies protect direct access from browser clients / PostgREST.
--
-- Access model (as requested):
--   admin      -> full access to everything
--   dispatcher -> manage shipments, drivers, vehicles (+ shipment sub-tables)
--   customer   -> only their own shipments (and own related rows)
--   transporter (needed by the app) -> own vehicles/drivers/bids/assigned trips

do $$
declare t text;
begin
    foreach t in array array[
        'users','customers','transporter_profiles','fuel_station_profiles',
        'shopkeeper_profiles','drivers','vehicles','shipments','shipment_bids',
        'shipment_trips','shipment_status_history','documents','payments',
        'wallets','wallet_transactions','wallet_withdrawal_requests',
        'shipment_trip_verification','shipment_no_show_tracking',
        'shipment_cancellations','shipment_notifications',
        'chat_threads','chat_messages',
        'agreement_posts','agreement_post_trucks','agreement_bids',
        'agreement_bid_trucks','agreements','agreement_trucks',
        'agreement_trips','agreement_monthly_payments','agreement_payment_penalties',
        'login_activity','trusted_devices','user_action_logs',
        'password_reset_otps','reset_tokens',
        'commission_policies','terms_versions','terms_acknowledgements'
    ] loop
        execute format('alter table public.%I enable row level security', t);
        execute format(
            'create policy %I on public.%I for all
             using (public.is_admin()) with check (public.is_admin())',
            'admin_all_' || t, t);
    end loop;
end $$;

-- 7.1 users
create policy users_select_own on public.users
    for select using (auth_id = auth.uid() or public.is_dispatcher());
create policy users_update_own on public.users
    for update using (auth_id = auth.uid())
    with check (auth_id = auth.uid() and role = (select u.role from public.users u where u.auth_id = auth.uid()));

-- 7.2 customers
create policy customers_own on public.customers
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
create policy customers_dispatcher_read on public.customers
    for select using (public.is_dispatcher());

-- 7.2b role profile tables: own row only
create policy transporter_profile_own on public.transporter_profiles
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
create policy fuel_station_profile_own on public.fuel_station_profiles
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
create policy shopkeeper_profile_own on public.shopkeeper_profiles
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());

-- 7.3 drivers
create policy drivers_dispatcher_all on public.drivers
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy drivers_owner_all on public.drivers
    for all using (owner_user_id = public.current_app_user_id())
    with check (owner_user_id = public.current_app_user_id());

-- 7.4 vehicles
create policy vehicles_dispatcher_all on public.vehicles
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy vehicles_owner_all on public.vehicles
    for all using (owner_user_id = public.current_app_user_id())
    with check (owner_user_id = public.current_app_user_id());
create policy vehicles_active_read on public.vehicles
    for select using (status = 'active');

-- 7.5 shipments
create policy shipments_dispatcher_all on public.shipments
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy shipments_client_own on public.shipments
    for all using (client_user_id = public.current_app_user_id())
    with check (client_user_id = public.current_app_user_id());
create policy shipments_transporter_read on public.shipments
    for select using (
        public.current_app_role() = 'transporter'
        and (
            status = 'open'
            or id in (select order_id from public.shipment_trips
                      where transporter_user_id = public.current_app_user_id())
        )
    );

-- 7.6 shipment_bids
create policy bids_dispatcher_all on public.shipment_bids
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy bids_transporter_own on public.shipment_bids
    for all using (transporter_user_id = public.current_app_user_id())
    with check (transporter_user_id = public.current_app_user_id());
create policy bids_client_read on public.shipment_bids
    for select using (
        order_id in (select id from public.shipments
                     where client_user_id = public.current_app_user_id()));

-- 7.7 shipment_trips
create policy trips_dispatcher_all on public.shipment_trips
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy trips_transporter_own on public.shipment_trips
    for all using (transporter_user_id = public.current_app_user_id())
    with check (transporter_user_id = public.current_app_user_id());
create policy trips_client_read on public.shipment_trips
    for select using (
        order_id in (select id from public.shipments
                     where client_user_id = public.current_app_user_id()));

-- 7.8 shipment_status_history (read-only for involved parties)
create policy history_dispatcher_read on public.shipment_status_history
    for select using (public.is_dispatcher());
create policy history_client_read on public.shipment_status_history
    for select using (
        shipment_id in (select id from public.shipments
                        where client_user_id = public.current_app_user_id()));
create policy history_transporter_read on public.shipment_status_history
    for select using (
        shipment_id in (select order_id from public.shipment_trips
                        where transporter_user_id = public.current_app_user_id()));

-- 7.9 documents
create policy documents_owner_all on public.documents
    for all using (owner_user_id = public.current_app_user_id())
    with check (owner_user_id = public.current_app_user_id());
create policy documents_dispatcher_read on public.documents
    for select using (public.is_dispatcher());
create policy documents_shipment_parties_read on public.documents
    for select using (
        shipment_id in (
            select id from public.shipments where client_user_id = public.current_app_user_id()
            union
            select order_id from public.shipment_trips where transporter_user_id = public.current_app_user_id()
        ));

-- 7.10 payments
create policy payments_client_read on public.payments
    for select using (client_user_id = public.current_app_user_id());
create policy payments_transporter_read on public.payments
    for select using (transporter_user_id = public.current_app_user_id());

-- 7.11 wallet
create policy wallets_own_read on public.wallets
    for select using (user_id = public.current_app_user_id());
create policy wallet_tx_own_read on public.wallet_transactions
    for select using (user_id = public.current_app_user_id());
create policy withdrawals_own on public.wallet_withdrawal_requests
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());

-- 7.12 chat
create policy chat_threads_participants on public.chat_threads
    for all using (
        client_user_id = public.current_app_user_id()
        or transporter_user_id = public.current_app_user_id()
        or admin_user_id = public.current_app_user_id())
    with check (
        client_user_id = public.current_app_user_id()
        or transporter_user_id = public.current_app_user_id()
        or admin_user_id = public.current_app_user_id());
create policy chat_messages_participants on public.chat_messages
    for all using (
        thread_id in (select id from public.chat_threads
                      where client_user_id = public.current_app_user_id()
                         or transporter_user_id = public.current_app_user_id()
                         or admin_user_id = public.current_app_user_id()))
    with check (sender_user_id = public.current_app_user_id());

-- 7.13 agreements domain
create policy agr_posts_client_own on public.agreement_posts
    for all using (client_user_id = public.current_app_user_id())
    with check (client_user_id = public.current_app_user_id());
create policy agr_posts_transporter_read on public.agreement_posts
    for select using (public.current_app_role() = 'transporter');
create policy agr_post_trucks_read on public.agreement_post_trucks
    for select using (true);
create policy agr_bids_transporter_own on public.agreement_bids
    for all using (transporter_user_id = public.current_app_user_id())
    with check (transporter_user_id = public.current_app_user_id());
create policy agr_bids_client_read on public.agreement_bids
    for select using (
        post_id in (select id from public.agreement_posts
                    where client_user_id = public.current_app_user_id()));
create policy agr_bid_trucks_read on public.agreement_bid_trucks
    for select using (true);
create policy agreements_parties on public.agreements
    for select using (
        client_user_id = public.current_app_user_id()
        or id in (select agreement_id from public.agreement_trucks
                  where transporter_user_id = public.current_app_user_id()));
create policy agr_trucks_parties on public.agreement_trucks
    for select using (
        transporter_user_id = public.current_app_user_id()
        or agreement_id in (select id from public.agreements
                            where client_user_id = public.current_app_user_id()));
create policy agr_trips_transporter_own on public.agreement_trips
    for all using (transporter_user_id = public.current_app_user_id())
    with check (transporter_user_id = public.current_app_user_id());
create policy agr_trips_client_read on public.agreement_trips
    for select using (
        agreement_id in (select id from public.agreements
                         where client_user_id = public.current_app_user_id()));
create policy agr_monthly_parties_read on public.agreement_monthly_payments
    for select using (
        transporter_user_id = public.current_app_user_id()
        or client_user_id = public.current_app_user_id());
create policy agr_penalties_client_read on public.agreement_payment_penalties
    for select using (client_user_id = public.current_app_user_id());

-- 7.14 misc (own rows only; OTP/reset tables are backend-only: admin policy only)
create policy login_activity_own_read on public.login_activity
    for select using (user_id = public.current_app_user_id());
create policy trusted_devices_own on public.trusted_devices
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
create policy action_logs_own_insert on public.user_action_logs
    for insert with check (true);

-- 7.15 commission policies & platform Terms
-- Only platform admins may manage policies (admin_all_* from the loop above).
-- Every authenticated user may read the published policies and Terms; users
-- manage only their own acknowledgement rows (insert + read, no edits).
create policy commission_policies_authenticated_read on public.commission_policies
    for select using (auth.uid() is not null);
create policy terms_versions_authenticated_read on public.terms_versions
    for select using (auth.uid() is not null);
create policy terms_ack_own_read on public.terms_acknowledgements
    for select using (user_id = public.current_app_user_id());
create policy terms_ack_own_insert on public.terms_acknowledgements
    for insert with check (user_id = public.current_app_user_id());

-- ---------------------------------------------------------------------------
-- 8. STORAGE — 'shipment-documents' bucket
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('shipment-documents', 'shipment-documents', false)
on conflict (id) do nothing;

-- The Flask backend uploads/serves files with the service role (bypasses RLS).
-- These policies additionally allow direct dashboard/client access for admins
-- and dispatchers.
create policy "shipment_docs_admin_all" on storage.objects
    for all using (bucket_id = 'shipment-documents' and public.is_admin())
    with check (bucket_id = 'shipment-documents' and public.is_admin());

create policy "shipment_docs_dispatcher_read" on storage.objects
    for select using (bucket_id = 'shipment-documents' and public.is_dispatcher());
