-- ============================================================================
-- Digi_TransX — Supabase PostgreSQL Schema
-- ============================================================================
-- Migration source: Database/digitransx_auth.db (SQLite)
-- Mapping from the existing app:
--   users                    -> users        (linked to Supabase Auth)
--   users (client-side data) -> customers    (profile extension)
--   trucks.driver_name/cnic  -> drivers      (extracted into own table)
--   trucks                   -> vehicles
--   orders                   -> shipments
--   (new, trigger-populated) -> shipment_status_history
--   photo/pdf path columns   -> documents    (metadata for Storage bucket)
--   invoices + payment cols  -> payments
-- Supporting tables the backend also needs (bids, trips, wallet, chat,
-- agreements) are kept so no business logic breaks.
--
-- Run order: this single file is idempotent-safe to run once on a fresh
-- Supabase project (SQL Editor or `supabase db push`).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. EXTENSIONS
-- ---------------------------------------------------------------------------
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. ENUM TYPES
-- ---------------------------------------------------------------------------
-- App role used by RLS. Legacy roles map as:
--   platform_admin                          -> admin
--   client / service_seeker / everyday_user -> customer
--   transporter / logistics_provider        -> transporter
--   (new operational role)                  -> dispatcher
create type public.app_role as enum
    ('admin', 'dispatcher', 'customer', 'transporter',
     'fuel_station_manager', 'shopkeeper');

create type public.shipment_status as enum
    ('open', 'bidding', 'accepted', 'pickup_pending', 'in_transit',
     'delivered', 'completed', 'cancelled', 'deactivated');

create type public.payment_status as enum
    ('pending', 'held', 'paid', 'refunded', 'failed');

create type public.vehicle_status as enum
    ('inactive', 'active', 'suspended', 'maintenance');

create type public.document_type as enum
    ('vehicle_photo', 'insurance', 'rc_book', 'invoice_pdf',
     'proof_of_delivery', 'chat_media', 'other');

-- ---------------------------------------------------------------------------
-- 2. CORE TABLES
-- ---------------------------------------------------------------------------

-- 2.1 USERS -----------------------------------------------------------------
-- Bigint IDs are kept (matches the Flask backend and existing data);
-- auth_id links each row to Supabase Auth (email/password).
create table public.users (
    id              bigint generated by default as identity primary key,
    auth_id         uuid unique references auth.users (id) on delete set null,
    full_name       text not null,
    first_name      text,
    last_name       text,
    email           text not null unique,
    phone           text not null,
    cnic            text not null unique,
    role            public.app_role not null default 'customer',
    legacy_role     text,                      -- original role string from SQLite
    company_name    text,
    business_type   text,
    city            text,
    fleet_size      text,
    transport_need  text,
    station_name    text,
    pumps_count     text,
    license_no      text,
    shop_name       text,
    address         text,
    about           text,
    mpin_hash       text,
    mpin_enabled    boolean not null default false,
    settings_json   jsonb not null default '{}'::jsonb,
    is_blocked      boolean not null default false,
    block_reason    text,
    withdrawal_tier integer not null default 0,
    withdrawal_tier_expires_at timestamptz,
    payout_card_number text,
    payout_card_holder text,
    payout_card_expiry text,
    payout_card_bank   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    last_login_at   timestamptz
);

-- 2.2 CUSTOMERS -------------------------------------------------------------
-- Profile extension for customer-role users (shippers / service seekers).
create table public.customers (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    customer_type   text,                      -- 'individual' | 'business'
    company_name    text,
    business_type   text,
    default_pickup_city  text,
    default_pickup_area  text,
    billing_address text,
    total_shipments integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.3 DRIVERS ---------------------------------------------------------------
-- Extracted from trucks.driver_name / driver_cnic. A driver belongs to a
-- transporter (owner) and can be assigned to vehicles.
create table public.drivers (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null references public.users (id) on delete cascade,
    full_name       text not null,
    cnic            text,
    phone           text,
    license_no      text,
    status          text not null default 'active',   -- active | inactive
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.4 VEHICLES (was: trucks) ------------------------------------------------
create table public.vehicles (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null references public.users (id) on delete cascade,
    driver_id       bigint references public.drivers (id) on delete set null,
    vehicle_number  text not null,             -- was truck_number
    company         text,                      -- was truck_company
    model           text,                      -- was truck_model
    vehicle_type    text not null,             -- was truck_type
    catalog_type_key text,
    chassis_number  text not null,
    capacity_tons   numeric not null,
    main_use        text not null,
    payload_min_tons numeric,
    payload_max_tons numeric,
    volume_min_cbm  numeric,
    volume_max_cbm  numeric,
    bed_length_ft   numeric,
    bed_width_ft    numeric,
    bed_height_ft   numeric,
    body_style      text,
    catalog_specs   jsonb,                     -- was catalog_specs_json
    tracking_id     text,
    traccar_device_id text,
    status          public.vehicle_status not null default 'inactive',
    status_reason_code text,
    status_reason   text,
    operating_provinces text,
    per_km_rate     numeric,
    waiting_charge_per_hour numeric,
    loading_charge  numeric,
    refrigeration_supported boolean not null default false,
    hazardous_supported     boolean not null default false,
    fragile_supported       boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- Case/whitespace-insensitive uniqueness (replaces SQLite COLLATE NOCASE).
create unique index vehicles_vehicle_number_unique
    on public.vehicles (lower(trim(vehicle_number)));
create unique index vehicles_chassis_number_unique
    on public.vehicles (lower(trim(chassis_number)));

-- 2.5 SHIPMENTS (was: orders) -----------------------------------------------
create table public.shipments (
    id              bigint generated by default as identity primary key,
    customer_id     bigint not null references public.users (id) on delete cascade,
    -- pickup / dropoff
    pickup_city     text not null,
    pickup_area     text not null,
    pickup_location text,
    pickup_lat      double precision,
    pickup_lng      double precision,
    dropoff_city    text not null,
    dropoff_area    text not null,
    dropoff_location text,
    dropoff_lat     double precision,
    dropoff_lng     double precision,
    pickup_date     date not null,
    pickup_time     text not null,
    -- goods taxonomy
    goods_type      text not null,
    goods_category  text,
    goods_form      text,
    goods_commodity text,
    goods_weight_tons numeric not null,
    goods_volume_cbm  numeric,
    length_cm       numeric,
    width_cm        numeric,
    height_cm       numeric,
    volume_liters   numeric,
    quantity        integer,
    animal_count    integer,
    temperature_c   numeric,
    required_truck_types text,
    is_refrigerated boolean not null default false,
    is_hazardous    boolean not null default false,
    is_food_grade   boolean not null default false,
    -- commercial
    estimated_budget numeric,
    notes           text,
    status          public.shipment_status not null default 'open',
    accepted_bid_id bigint,                    -- FK added after shipment_bids
    payment_amount  numeric,
    payment_status  public.payment_status not null default 'pending',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.6 SHIPMENT BIDS (was: order_bids) ---------------------------------------
create table public.shipment_bids (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    transporter_id  bigint not null references public.users (id) on delete cascade,
    vehicle_id      bigint not null references public.vehicles (id) on delete cascade,
    bid_price       numeric not null,
    message         text,
    status          text not null default 'pending',  -- pending | accepted | rejected | withdrawn
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table public.shipments
    add constraint shipments_accepted_bid_fk
    foreign key (accepted_bid_id) references public.shipment_bids (id) on delete set null;

-- 2.7 SHIPMENT TRIPS (was: order_trips) -------------------------------------
create table public.shipment_trips (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    accepted_bid_id bigint not null references public.shipment_bids (id),
    transporter_id  bigint not null references public.users (id),
    vehicle_id      bigint not null references public.vehicles (id),
    status          text not null default 'accepted',
    trip_started_at timestamptz,
    trip_completed_at timestamptz,
    delivery_confirmed_at timestamptz,
    pickup_location_lat  double precision,
    pickup_location_lng  double precision,
    dropoff_location_lat double precision,
    dropoff_location_lng double precision,
    actual_distance_km   numeric,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- 2.8 SHIPMENT STATUS HISTORY (new — audit trail) ---------------------------
-- Populated automatically by trigger whenever shipments.status changes.
create table public.shipment_status_history (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    old_status      public.shipment_status,
    new_status      public.shipment_status not null,
    changed_by      bigint references public.users (id),
    note            text,
    created_at      timestamptz not null default now()
);

-- 2.9 DOCUMENTS -------------------------------------------------------------
-- Metadata for files stored in the 'shipment-documents' Storage bucket.
-- Replaces path columns: truck_photo_path, insurance_photo_path,
-- rc_book_photo_path, order_invoices.pdf_path, chat media_path.
create table public.documents (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null references public.users (id) on delete cascade,
    shipment_id     bigint references public.shipments (id) on delete cascade,
    vehicle_id      bigint references public.vehicles (id) on delete cascade,
    doc_type        public.document_type not null default 'other',
    storage_path    text not null,             -- path inside 'shipment-documents' bucket
    file_name       text,
    mime_type       text,
    size_bytes      bigint,
    created_at      timestamptz not null default now()
);

-- 2.10 PAYMENTS (was: order_invoices + orders.payment_*) --------------------
create table public.payments (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint references public.shipments (id) on delete set null,
    trip_id         bigint references public.shipment_trips (id) on delete set null,
    invoice_number  text unique,
    customer_id     bigint not null references public.users (id),
    transporter_id  bigint references public.users (id),
    gross_amount    numeric not null,          -- was bid_price
    company_fee     numeric not null default 0,
    transporter_amount numeric not null default 0,
    payment_method  text not null default 'wallet',
    status          public.payment_status not null default 'pending',
    invoice_document_id bigint references public.documents (id) on delete set null,
    paid_at         timestamptz,
    created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. SUPPORTING TABLES (existing backend features — kept as-is)
-- ---------------------------------------------------------------------------

-- 3.1 Wallet ----------------------------------------------------------------
create table public.wallets (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    role            text not null,
    balance         numeric not null default 0,
    locked_balance  numeric not null default 0,
    minimum_required numeric not null default 0,
    is_minimum_met  boolean not null default false,
    completed_trips_count integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.wallet_transactions (
    id              bigint generated by default as identity primary key,
    wallet_id       bigint not null references public.wallets (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    type            text not null,
    amount          numeric not null,
    gross_amount    numeric,
    gateway_fee     numeric default 0,
    description     text,
    reference_id    text,
    balance_after   numeric not null,
    created_at      timestamptz not null default now()
);

create table public.wallet_withdrawal_requests (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null references public.users (id) on delete cascade,
    amount          numeric not null,
    status          text not null default 'pending',
    requested_at    timestamptz not null default now(),
    resolved_at     timestamptz,
    processed_at    timestamptz
);

-- 3.2 Shipment ops (verification / no-show / cancellations / notifications) -
create table public.shipment_trip_verification (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    transporter_claim_at timestamptz,
    client_first_response text,
    client_first_response_at timestamptz,
    client_second_response text,
    client_second_response_at timestamptz,
    final_verification_status text,
    admin_decision_by bigint references public.users (id),
    admin_decision  text,
    admin_decided_at timestamptz,
    admin_note      text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.shipment_no_show_tracking (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    notification_count integer not null default 0,
    call_count      integer not null default 0,
    last_notification_at timestamptz,
    last_call_at    timestamptz,
    order_deactivated_at timestamptz,
    status          text not null default 'tracking',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.shipment_cancellations (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    cancelled_by    text not null,
    reason          text,
    refund_amount   numeric,
    penalty_amount  numeric,
    status          text not null default 'pending',
    created_at      timestamptz not null default now()
);

create table public.shipment_notifications (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    trip_id         bigint references public.shipment_trips (id) on delete cascade,
    user_id         bigint not null references public.users (id) on delete cascade,
    notification_type text not null,
    message         text,
    is_read         boolean not null default false,
    created_at      timestamptz not null default now()
);

-- 3.3 Chat ------------------------------------------------------------------
create table public.chat_threads (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null references public.users (id) on delete cascade,
    transporter_user_id bigint not null references public.users (id) on delete cascade,
    agreement_post_id bigint,                  -- FK added after agreement_posts
    agreement_bid_id  bigint,
    is_group_chat   boolean not null default false,
    admin_user_id   bigint references public.users (id),
    dispute_trip_id bigint,
    last_message_at timestamptz,
    created_at      timestamptz not null default now(),
    unique (agreement_post_id, transporter_user_id)
);

create table public.chat_messages (
    id              bigint generated by default as identity primary key,
    thread_id       bigint not null references public.chat_threads (id) on delete cascade,
    sender_user_id  bigint not null references public.users (id) on delete cascade,
    message_type    text not null default 'text',
    content         text,
    media_document_id bigint references public.documents (id) on delete set null,
    media_request_status text,
    is_read         boolean not null default false,
    created_at      timestamptz not null default now()
);

-- 3.4 Agreements (long-term contracts) --------------------------------------
create table public.agreement_posts (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null references public.users (id) on delete cascade,
    title           text not null,
    cargo_type      text not null,
    service_area    text not null,
    pickup_location text,
    dropoff_location text,
    status          text not null default 'open',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table public.chat_threads
    add constraint chat_threads_agreement_post_fk
    foreign key (agreement_post_id) references public.agreement_posts (id) on delete set null;

create table public.agreement_post_trucks (
    id              bigint generated by default as identity primary key,
    post_id         bigint not null references public.agreement_posts (id) on delete cascade,
    truck_type      text not null,
    capacity_tons   numeric not null,
    quantity        integer not null
);

create table public.agreement_bids (
    id              bigint generated by default as identity primary key,
    post_id         bigint not null references public.agreement_posts (id) on delete cascade,
    transporter_user_id bigint not null references public.users (id) on delete cascade,
    status          text not null default 'pending',
    message         text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

alter table public.chat_threads
    add constraint chat_threads_agreement_bid_fk
    foreign key (agreement_bid_id) references public.agreement_bids (id) on delete set null;

create table public.agreement_bid_trucks (
    id              bigint generated by default as identity primary key,
    bid_id          bigint not null references public.agreement_bids (id) on delete cascade,
    vehicle_id      bigint not null references public.vehicles (id) on delete cascade,
    per_km_rate     numeric not null,
    minimum_monthly_guarantee numeric not null
);

create table public.agreements (
    id              bigint generated by default as identity primary key,
    post_id         bigint not null references public.agreement_posts (id),
    client_user_id  bigint not null references public.users (id),
    duration_months integer not null,
    cargo_type      text not null,
    service_area    text not null,
    start_date      date not null,
    end_date        date not null,
    status          text not null default 'active',
    contract_text   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.agreement_trucks (
    id              bigint generated by default as identity primary key,
    agreement_id    bigint not null references public.agreements (id) on delete cascade,
    vehicle_id      bigint not null references public.vehicles (id),
    transporter_user_id bigint not null references public.users (id),
    per_km_rate     numeric not null,
    minimum_monthly_guarantee numeric not null,
    status          text not null default 'active'
);

create table public.agreement_trips (
    id              bigint generated by default as identity primary key,
    agreement_id    bigint not null references public.agreements (id) on delete cascade,
    agreement_truck_id bigint not null references public.agreement_trucks (id),
    vehicle_id      bigint not null references public.vehicles (id),
    transporter_user_id bigint not null references public.users (id),
    pickup_description text not null,
    pickup_location text,
    dropoff_location text,
    trip_date       date not null,
    gps_start_lat   double precision,
    gps_start_lng   double precision,
    gps_end_lat     double precision,
    gps_end_lng     double precision,
    distance_km     numeric,
    distance_source text,
    started_at      timestamptz,
    ended_at        timestamptz,
    status          text not null default 'pending',
    client_acknowledged boolean not null default false,
    admin_decision  text,
    admin_note      text,
    admin_decided_at timestamptz,
    admin_decided_by bigint references public.users (id),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table public.agreement_monthly_payments (
    id              bigint generated by default as identity primary key,
    agreement_id    bigint not null references public.agreements (id) on delete cascade,
    agreement_truck_id bigint not null references public.agreement_trucks (id),
    transporter_user_id bigint not null references public.users (id),
    client_user_id  bigint not null references public.users (id),
    month_year      text not null,
    total_km        numeric not null default 0,
    total_earned    numeric not null default 0,
    minimum_guarantee numeric not null,
    final_amount    numeric not null,
    company_fee     numeric not null,
    transporter_amount numeric not null,
    penalty_amount  numeric not null default 0,
    status          text not null default 'pending',
    payment_due_date date not null,
    paid_at         timestamptz,
    created_at      timestamptz not null default now()
);

create table public.agreement_payment_penalties (
    id              bigint generated by default as identity primary key,
    monthly_payment_id bigint not null references public.agreement_monthly_payments (id) on delete cascade,
    client_user_id  bigint not null references public.users (id),
    penalty_amount  numeric not null default 5000,
    penalty_number  integer not null,
    applied_at      timestamptz not null default now()
);

-- 3.5 Auth support / audit --------------------------------------------------
-- Supabase Auth replaces password_reset_otps, reset_tokens and password_hash.
-- Login history and action logs are kept for the admin panel.
create table public.login_activity (
    id              bigint generated by default as identity primary key,
    user_id         bigint references public.users (id) on delete set null,
    login_identifier text,
    login_method    text,
    status          text not null,
    failure_reason  text,
    ip_address      text,
    user_agent      text,
    created_at      timestamptz not null default now()
);

create table public.trusted_devices (
    id              bigint generated by default as identity primary key,
    device_token    text not null unique,
    user_id         bigint not null references public.users (id) on delete cascade,
    created_at      timestamptz not null default now(),
    last_seen_at    timestamptz not null default now()
);

create table public.user_action_logs (
    id              bigint generated by default as identity primary key,
    user_id         bigint references public.users (id) on delete set null,
    user_email      text,
    user_role       text,
    action_type     text,
    action_name     text,
    page_url        text,
    payload_json    jsonb,
    created_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 4. INDEXES
-- ---------------------------------------------------------------------------
create index idx_shipments_customer_status   on public.shipments (customer_id, status, created_at desc);
create index idx_shipments_status_created    on public.shipments (status, created_at desc);
create index idx_shipment_bids_shipment      on public.shipment_bids (shipment_id, status, created_at desc);
create index idx_shipment_bids_transporter   on public.shipment_bids (transporter_id, created_at desc);
create index idx_shipment_trips_shipment     on public.shipment_trips (shipment_id, status);
create index idx_shipment_trips_transporter  on public.shipment_trips (transporter_id, status, created_at desc);
create index idx_status_history_shipment     on public.shipment_status_history (shipment_id, created_at desc);
create index idx_documents_shipment          on public.documents (shipment_id);
create index idx_documents_vehicle           on public.documents (vehicle_id);
create index idx_documents_owner             on public.documents (owner_user_id);
create index idx_payments_customer           on public.payments (customer_id, created_at desc);
create index idx_payments_transporter        on public.payments (transporter_id, created_at desc);
create index idx_payments_shipment           on public.payments (shipment_id);
create index idx_vehicles_owner              on public.vehicles (owner_user_id, status);
create index idx_drivers_owner               on public.drivers (owner_user_id);
create index idx_wallet_tx_user_created      on public.wallet_transactions (user_id, created_at desc);
create index idx_wallet_tx_wallet_created    on public.wallet_transactions (wallet_id, created_at desc);
create index idx_withdrawals_user_status     on public.wallet_withdrawal_requests (user_id, status, requested_at desc);
create index idx_chat_threads_client_last    on public.chat_threads (client_user_id, last_message_at desc);
create index idx_chat_threads_transp_last    on public.chat_threads (transporter_user_id, last_message_at desc);
create index idx_chat_messages_thread        on public.chat_messages (thread_id, id);
create index idx_chat_messages_thread_read   on public.chat_messages (thread_id, is_read, sender_user_id);
create index idx_agr_posts_client_status     on public.agreement_posts (client_user_id, status, created_at desc);
create index idx_agr_bids_post_transporter   on public.agreement_bids (post_id, transporter_user_id, status);
create index idx_agr_trucks_agr_transporter  on public.agreement_trucks (agreement_id, transporter_user_id);
create index idx_agr_trips_agr_vehicle       on public.agreement_trips (agreement_id, vehicle_id, status);
create index idx_agr_payments_due_status     on public.agreement_monthly_payments (status, payment_due_date);
create index idx_notifications_user_created  on public.shipment_notifications (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 5. HELPER FUNCTIONS (used by RLS)
-- ---------------------------------------------------------------------------
-- Resolve the app user id (bigint) of the logged-in Supabase Auth user.
create or replace function public.current_app_user_id()
returns bigint
language sql stable security definer set search_path = public
as $$
    select id from public.users where auth_id = auth.uid();
$$;

create or replace function public.current_app_role()
returns public.app_role
language sql stable security definer set search_path = public
as $$
    select role from public.users where auth_id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
    select coalesce(public.current_app_role() = 'admin', false);
$$;

create or replace function public.is_dispatcher()
returns boolean
language sql stable security definer set search_path = public
as $$
    select coalesce(public.current_app_role() = 'dispatcher', false);
$$;

-- ---------------------------------------------------------------------------
-- 6. TRIGGERS
-- ---------------------------------------------------------------------------
-- 6.1 updated_at maintenance
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

do $$
declare t text;
begin
    foreach t in array array[
        'users','customers','drivers','vehicles','shipments','shipment_bids',
        'shipment_trips','shipment_trip_verification','shipment_no_show_tracking',
        'wallets','agreement_posts','agreement_bids','agreements','agreement_trips'
    ] loop
        execute format(
            'create trigger trg_%I_updated_at before update on public.%I
             for each row execute function public.set_updated_at()', t, t);
    end loop;
end $$;

-- 6.2 Automatic shipment status history
create or replace function public.log_shipment_status_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if tg_op = 'INSERT' then
        insert into public.shipment_status_history (shipment_id, old_status, new_status, changed_by)
        values (new.id, null, new.status, public.current_app_user_id());
    elsif new.status is distinct from old.status then
        insert into public.shipment_status_history (shipment_id, old_status, new_status, changed_by)
        values (new.id, old.status, new.status, public.current_app_user_id());
    end if;
    return new;
end;
$$;

create trigger trg_shipments_status_history
    after insert or update of status on public.shipments
    for each row execute function public.log_shipment_status_change();

-- 6.3 Auto-create public.users profile on Supabase Auth signup
-- (raw_user_meta_data must carry full_name, phone, cnic, role from the app)
create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.users (auth_id, email, full_name, phone, cnic, role, legacy_role)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.raw_user_meta_data ->> 'phone', ''),
        coalesce(new.raw_user_meta_data ->> 'cnic', 'PENDING-' || new.id::text),
        coalesce((new.raw_user_meta_data ->> 'role')::public.app_role, 'customer'),
        new.raw_user_meta_data ->> 'legacy_role'
    )
    on conflict (email) do update set auth_id = excluded.auth_id;
    return new;
end;
$$;

create trigger trg_on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------
-- NOTE: the Flask backend uses the service_role key, which BYPASSES RLS.
-- These policies protect direct access from browser clients / PostgREST.
--
-- Access model (as requested):
--   admin      -> full access to everything
--   dispatcher -> manage shipments, drivers, vehicles (+ shipment sub-tables)
--   customer   -> only their own shipments (and own related rows)
--   transporter (needed by the app) -> own vehicles/drivers/bids/assigned trips

do $$
declare t text;
begin
    foreach t in array array[
        'users','customers','drivers','vehicles','shipments','shipment_bids',
        'shipment_trips','shipment_status_history','documents','payments',
        'wallets','wallet_transactions','wallet_withdrawal_requests',
        'shipment_trip_verification','shipment_no_show_tracking',
        'shipment_cancellations','shipment_notifications',
        'chat_threads','chat_messages',
        'agreement_posts','agreement_post_trucks','agreement_bids',
        'agreement_bid_trucks','agreements','agreement_trucks',
        'agreement_trips','agreement_monthly_payments','agreement_payment_penalties',
        'login_activity','trusted_devices','user_action_logs'
    ] loop
        execute format('alter table public.%I enable row level security', t);
        -- Admin: full access on every table
        execute format(
            'create policy %I on public.%I for all
             using (public.is_admin()) with check (public.is_admin())',
            'admin_all_' || t, t);
    end loop;
end $$;

-- 7.1 users: read/update own profile
create policy users_select_own on public.users
    for select using (auth_id = auth.uid() or public.is_dispatcher());
create policy users_update_own on public.users
    for update using (auth_id = auth.uid())
    with check (auth_id = auth.uid() and role = (select u.role from public.users u where u.auth_id = auth.uid()));

-- 7.2 customers: own profile
create policy customers_own on public.customers
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
create policy customers_dispatcher_read on public.customers
    for select using (public.is_dispatcher());

-- 7.3 drivers: dispatcher manages all; transporter manages own
create policy drivers_dispatcher_all on public.drivers
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy drivers_owner_all on public.drivers
    for all using (owner_user_id = public.current_app_user_id())
    with check (owner_user_id = public.current_app_user_id());

-- 7.4 vehicles: dispatcher manages all; transporter manages own;
--     customers may view active vehicles (needed for bid display)
create policy vehicles_dispatcher_all on public.vehicles
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy vehicles_owner_all on public.vehicles
    for all using (owner_user_id = public.current_app_user_id())
    with check (owner_user_id = public.current_app_user_id());
create policy vehicles_active_read on public.vehicles
    for select using (status = 'active');

-- 7.5 shipments: dispatcher manages all; customer only their own;
--     transporters may view open shipments (marketplace) and assigned ones
create policy shipments_dispatcher_all on public.shipments
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy shipments_customer_own on public.shipments
    for all using (customer_id = public.current_app_user_id())
    with check (customer_id = public.current_app_user_id());
create policy shipments_transporter_open_read on public.shipments
    for select using (
        public.current_app_role() = 'transporter'
        and (
            status = 'open'
            or id in (select shipment_id from public.shipment_trips
                      where transporter_id = public.current_app_user_id())
        )
    );

-- 7.6 shipment_bids
create policy bids_dispatcher_all on public.shipment_bids
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy bids_transporter_own on public.shipment_bids
    for all using (transporter_id = public.current_app_user_id())
    with check (transporter_id = public.current_app_user_id());
create policy bids_customer_read on public.shipment_bids
    for select using (
        shipment_id in (select id from public.shipments
                        where customer_id = public.current_app_user_id()));

-- 7.7 shipment_trips
create policy trips_dispatcher_all on public.shipment_trips
    for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy trips_transporter_own on public.shipment_trips
    for all using (transporter_id = public.current_app_user_id())
    with check (transporter_id = public.current_app_user_id());
create policy trips_customer_read on public.shipment_trips
    for select using (
        shipment_id in (select id from public.shipments
                        where customer_id = public.current_app_user_id()));

-- 7.8 shipment_status_history: read-only for involved parties
create policy history_dispatcher_read on public.shipment_status_history
    for select using (public.is_dispatcher());
create policy history_customer_read on public.shipment_status_history
    for select using (
        shipment_id in (select id from public.shipments
                        where customer_id = public.current_app_user_id()));
create policy history_transporter_read on public.shipment_status_history
    for select using (
        shipment_id in (select shipment_id from public.shipment_trips
                        where transporter_id = public.current_app_user_id()));

-- 7.9 documents: owner full; involved shipment parties read
create policy documents_owner_all on public.documents
    for all using (owner_user_id = public.current_app_user_id())
    with check (owner_user_id = public.current_app_user_id());
create policy documents_dispatcher_read on public.documents
    for select using (public.is_dispatcher());
create policy documents_shipment_parties_read on public.documents
    for select using (
        shipment_id in (
            select id from public.shipments where customer_id = public.current_app_user_id()
            union
            select shipment_id from public.shipment_trips where transporter_id = public.current_app_user_id()
        ));

-- 7.10 payments: parties read their own
create policy payments_customer_read on public.payments
    for select using (customer_id = public.current_app_user_id());
create policy payments_transporter_read on public.payments
    for select using (transporter_id = public.current_app_user_id());

-- 7.11 wallet: strictly own rows
create policy wallets_own_read on public.wallets
    for select using (user_id = public.current_app_user_id());
create policy wallet_tx_own_read on public.wallet_transactions
    for select using (user_id = public.current_app_user_id());
create policy withdrawals_own on public.wallet_withdrawal_requests
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());

-- 7.12 chat: participants only
create policy chat_threads_participants on public.chat_threads
    for all using (
        client_user_id = public.current_app_user_id()
        or transporter_user_id = public.current_app_user_id()
        or admin_user_id = public.current_app_user_id())
    with check (
        client_user_id = public.current_app_user_id()
        or transporter_user_id = public.current_app_user_id()
        or admin_user_id = public.current_app_user_id());
create policy chat_messages_participants on public.chat_messages
    for all using (
        thread_id in (select id from public.chat_threads
                      where client_user_id = public.current_app_user_id()
                         or transporter_user_id = public.current_app_user_id()
                         or admin_user_id = public.current_app_user_id()))
    with check (sender_user_id = public.current_app_user_id());

-- 7.13 agreements domain: involved parties
create policy agr_posts_client_own on public.agreement_posts
    for all using (client_user_id = public.current_app_user_id())
    with check (client_user_id = public.current_app_user_id());
create policy agr_posts_transporter_read on public.agreement_posts
    for select using (public.current_app_role() = 'transporter');
create policy agr_post_trucks_read on public.agreement_post_trucks
    for select using (true);
create policy agr_bids_transporter_own on public.agreement_bids
    for all using (transporter_user_id = public.current_app_user_id())
    with check (transporter_user_id = public.current_app_user_id());
create policy agr_bids_client_read on public.agreement_bids
    for select using (
        post_id in (select id from public.agreement_posts
                    where client_user_id = public.current_app_user_id()));
create policy agr_bid_trucks_read on public.agreement_bid_trucks
    for select using (true);
create policy agreements_parties on public.agreements
    for select using (
        client_user_id = public.current_app_user_id()
        or id in (select agreement_id from public.agreement_trucks
                  where transporter_user_id = public.current_app_user_id()));
create policy agr_trucks_parties on public.agreement_trucks
    for select using (
        transporter_user_id = public.current_app_user_id()
        or agreement_id in (select id from public.agreements
                            where client_user_id = public.current_app_user_id()));
create policy agr_trips_transporter_own on public.agreement_trips
    for all using (transporter_user_id = public.current_app_user_id())
    with check (transporter_user_id = public.current_app_user_id());
create policy agr_trips_client_read on public.agreement_trips
    for select using (
        agreement_id in (select id from public.agreements
                         where client_user_id = public.current_app_user_id()));
create policy agr_monthly_parties_read on public.agreement_monthly_payments
    for select using (
        transporter_user_id = public.current_app_user_id()
        or client_user_id = public.current_app_user_id());
create policy agr_penalties_client_read on public.agreement_payment_penalties
    for select using (client_user_id = public.current_app_user_id());

-- 7.14 misc: own rows only
create policy login_activity_own_read on public.login_activity
    for select using (user_id = public.current_app_user_id());
create policy trusted_devices_own on public.trusted_devices
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
create policy action_logs_own_insert on public.user_action_logs
    for insert with check (user_id = public.current_app_user_id());

-- ---------------------------------------------------------------------------
-- 8. STORAGE — 'shipment-documents' bucket
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('shipment-documents', 'shipment-documents', false)
on conflict (id) do nothing;

-- Path convention: <app_user_id>/<doc_type>/<filename>
-- (first path segment = uploader's app user id)
create policy "shipment_docs_admin_all" on storage.objects
    for all using (bucket_id = 'shipment-documents' and public.is_admin())
    with check (bucket_id = 'shipment-documents' and public.is_admin());

create policy "shipment_docs_dispatcher_read" on storage.objects
    for select using (bucket_id = 'shipment-documents' and public.is_dispatcher());

create policy "shipment_docs_owner_all" on storage.objects
    for all using (
        bucket_id = 'shipment-documents'
        and (storage.foldername(name))[1] = public.current_app_user_id()::text)
    with check (
        bucket_id = 'shipment-documents'
        and (storage.foldername(name))[1] = public.current_app_user_id()::text);

-- Shipment counterparties can read files linked via public.documents
create policy "shipment_docs_parties_read" on storage.objects
    for select using (
        bucket_id = 'shipment-documents'
        and name in (
            select d.storage_path from public.documents d
            where d.shipment_id in (
                select id from public.shipments where customer_id = public.current_app_user_id()
                union
                select shipment_id from public.shipment_trips where transporter_id = public.current_app_user_id()
            )));

-- ---------------------------------------------------------------------------
-- 9. SEQUENCE ALIGNMENT (run AFTER data import from SQLite)
-- ---------------------------------------------------------------------------
-- After importing legacy rows with explicit ids, bump each identity sequence:
--   select setval(pg_get_serial_sequence('public.users', 'id'),
--                 coalesce((select max(id) from public.users), 0) + 1, false);
-- Repeat for every table that received legacy ids.
