"""Test fixtures for the commission-policy suite.

Two tiers of tests:

- Pure calculation/validation tests run with no database at all.
- Database-backed tests are PostgreSQL integration tests. They require a
  DEDICATED test database configured via the TEST_SUPABASE_DB_URL environment
  variable. There is deliberately no fallback to SUPABASE_DB_URL: tests must
  never touch the production database. When TEST_SUPABASE_DB_URL is not set,
  the integration tests are skipped with a clear reason.

Isolation: each test session creates a uniquely named schema on the test
database, installs the commission tables there (mirroring
supabase/schema.sql, including CHECK constraints and the immutability
trigger), pins the connection's search_path to that schema, and drops the
schema again afterwards. Between tests the tables are truncated. The tests
reuse the production Db wrapper from shared.db — there is no second
database abstraction.
"""

import os
import sys
import uuid
from pathlib import Path

import pytest

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))


TEST_DB_ENV = "TEST_SUPABASE_DB_URL"

# Populated by the pg_connection fixture; read by tests that need a second
# independent connection into the same isolated schema.
TEST_SESSION_INFO = {}

SKIP_REASON = (
    "TEST_SUPABASE_DB_URL is not set; PostgreSQL integration tests require a "
    "dedicated test database and never fall back to SUPABASE_DB_URL."
)

# Mirrors the production tables from supabase/schema.sql that the commission
# helpers touch, including CHECK constraints, unique constraints and the
# immutability trigger. User references are plain columns here so the test
# schema stays self-contained.
DDL = """
create table commission_policies (
    id              bigint generated by default as identity primary key,
    policy_type     text not null
                    check (policy_type in ('one_time_order', 'agreement')),
    version_number  integer not null check (version_number >= 1),
    company_share_percent     numeric(5,2) not null
                    check (company_share_percent >= 0 and company_share_percent < 100),
    transporter_share_percent numeric(5,2) not null
                    check (transporter_share_percent > 0 and transporter_share_percent <= 100),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    created_by_admin_user_id bigint,
    created_at      timestamptz not null default now(),
    constraint commission_policies_type_version_unique unique (policy_type, version_number),
    constraint commission_policies_shares_sum_100
        check (company_share_percent + transporter_share_percent = 100)
);

create table terms_versions (
    id              bigint generated by default as identity primary key,
    version_number  integer not null unique check (version_number >= 1),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    one_time_policy_id  bigint not null references commission_policies (id),
    agreement_policy_id bigint not null references commission_policies (id),
    published_by_admin_user_id bigint,
    published_at    timestamptz not null default now()
);

create table terms_acknowledgements (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    terms_version_id bigint not null references terms_versions (id) on delete cascade,
    acknowledged_at timestamptz not null default now(),
    constraint terms_ack_user_version_unique unique (user_id, terms_version_id)
);

create or replace function prevent_version_mutation()
returns trigger language plpgsql as $$
begin
    raise exception 'published % rows are immutable — publish a new version instead', tg_table_name;
end;
$$;

create trigger trg_commission_policies_immutable
    before update or delete on commission_policies
    for each row execute function prevent_version_mutation();

create trigger trg_terms_versions_immutable
    before update or delete on terms_versions
    for each row execute function prevent_version_mutation();

create table wallets (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique,
    role            text not null,
    balance         numeric not null default 0,
    locked_balance  numeric not null default 0,
    minimum_required numeric not null default 0,
    is_minimum_met  boolean not null default false,
    completed_trips_count integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table wallet_transactions (
    id              bigint generated by default as identity primary key,
    wallet_id       bigint not null references wallets (id) on delete cascade,
    user_id         bigint not null,
    type            text not null,
    amount          numeric not null,
    gross_amount    numeric,
    gateway_fee     numeric default 0,
    description     text,
    reference_id    text,
    provider_name       text,
    provider_reference  text,
    balance_after   numeric not null,
    created_at      timestamptz not null default now()
);

create unique index uniq_wallet_topup_idempotency
    on wallet_transactions (user_id, reference_id)
    where type = 'topup' and reference_id is not null;

create table shipments (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null,
    status          text not null default 'open',
    accepted_bid_id bigint,
    payment_amount  numeric,
    payment_status  text not null default 'pending',
    company_share_percent_snapshot     numeric(5,2),
    transporter_share_percent_snapshot numeric(5,2),
    commission_policy_id bigint,
    terms_version_id     bigint,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table shipment_bids (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references shipments (id) on delete cascade,
    transporter_user_id bigint not null,
    truck_id        bigint not null,
    bid_price       numeric not null,
    message         text,
    status          text not null default 'pending',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table shipment_trips (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references shipments (id) on delete cascade,
    accepted_bid_id bigint not null references shipment_bids (id),
    transporter_user_id bigint not null,
    truck_id        bigint not null,
    status          text not null default 'accepted',
    trip_started_at timestamptz,
    trip_completed_at timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table shipment_no_show_tracking (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references shipment_trips (id) on delete cascade,
    status          text not null default 'tracking',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table payments (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references shipment_trips (id) on delete cascade,
    shipment_id     bigint references shipments (id) on delete set null,
    invoice_number  text not null unique,
    client_user_id  bigint not null,
    transporter_user_id bigint not null,
    bid_price       numeric not null,
    company_fee     numeric not null,
    transporter_amount numeric not null,
    company_share_percent     numeric(5,2),
    transporter_share_percent numeric(5,2),
    commission_policy_id bigint references commission_policies (id),
    terms_version_id bigint references terms_versions (id),
    wallet_funded_amount   numeric(12,2) not null default 0
        check (wallet_funded_amount >= 0),
    card_funded_amount     numeric(12,2) not null default 0
        check (card_funded_amount >= 0),
    processing_fee_percent numeric(5,2)
        check (processing_fee_percent is null or processing_fee_percent >= 0),
    processing_fee_amount  numeric(12,2) not null default 0
        check (processing_fee_amount >= 0),
    total_card_charge      numeric(14,2)
        check (total_card_charge is null or total_card_charge >= 0),
    funding_source         text
        check (funding_source is null or funding_source in ('wallet', 'card', 'wallet_card')),
    provider_name          text,
    provider_reference     text,
    idempotency_key        text,
    payment_method  text not null default 'wallet',
    status          text not null default 'paid'
                    check (status in ('processing', 'held', 'released', 'disputed', 'refunded', 'failed', 'paid')),
    held_at         timestamptz,
    released_at     timestamptz,
    refunded_at     timestamptz,
    pdf_path        text,
    paid_at         timestamptz,
    created_at      timestamptz not null default now()
);

create unique index uniq_payments_active_per_shipment
    on payments (shipment_id)
    where shipment_id is not null and status in ('processing', 'held', 'disputed', 'released');
create unique index uniq_payments_idempotency_key
    on payments (idempotency_key)
    where idempotency_key is not null;

create table saved_payment_methods (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    provider_name   text not null default 'dummycard',
    provider_token  text not null unique,
    card_brand      text not null default 'card',
    card_last_four  text not null check (card_last_four ~ '^[0-9]{4}$'),
    expiry_month    integer not null check (expiry_month between 1 and 12),
    expiry_year     integer not null check (expiry_year between 2000 and 2200),
    is_default      boolean not null default false,
    status          text not null default 'active'
                    check (status in ('active', 'removed')),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint saved_payment_methods_user_row_unique unique (user_id, id)
);

create unique index uniq_saved_method_default_per_user
    on saved_payment_methods (user_id)
    where is_default and status = 'active';

create table user_payment_preferences (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique,
    default_payment_method_id bigint,
    auto_shortfall_charge_enabled boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint user_payment_preferences_method_owned_fk
        foreign key (user_id, default_payment_method_id)
        references saved_payment_methods (user_id, id)
        on delete set null (default_payment_method_id)
);

create table transporter_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique,
    company_name    text,
    fleet_size      text,
    withdrawal_tier integer not null default 0,
    withdrawal_tier_expires_at text,
    payout_card_token     text,
    payout_card_brand     text,
    payout_card_last_four text
        check (payout_card_last_four is null or payout_card_last_four ~ '^[0-9]{4}$'),
    payout_card_holder text,
    payout_card_expiry text,
    payout_card_bank   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create unique index uniq_payout_card_token
    on transporter_profiles (payout_card_token)
    where payout_card_token is not null;
"""


@pytest.fixture(scope="session")
def pg_connection():
    test_url = os.environ.get(TEST_DB_ENV, "").strip()
    if not test_url:
        pytest.skip(SKIP_REASON)
    if test_url == os.environ.get("SUPABASE_DB_URL", "").strip():
        pytest.skip(
            "TEST_SUPABASE_DB_URL matches SUPABASE_DB_URL; integration tests "
            "require a dedicated test database, not the application database."
        )

    import psycopg2

    conn = psycopg2.connect(test_url)
    schema = f"dtx_test_{uuid.uuid4().hex[:12]}"
    # Tests that open extra connections (genuine concurrency) look up the
    # session's isolated schema + URL here (psycopg2 connections don't accept
    # arbitrary attributes).
    TEST_SESSION_INFO["schema"] = schema
    TEST_SESSION_INFO["url"] = test_url
    try:
        with conn.cursor() as cur:
            cur.execute(f'create schema "{schema}"')
            cur.execute(f'set search_path to "{schema}"')
            cur.execute(DDL)
        conn.commit()
        yield conn
    finally:
        conn.rollback()
        with conn.cursor() as cur:
            cur.execute(f'drop schema "{schema}" cascade')
        conn.commit()
        conn.close()


@pytest.fixture
def pg_session_info(pg_connection):
    """The isolated schema + URL, for tests that open their own connections
    (e.g. genuine concurrency and route-level tests). Exposed as a fixture so
    callers never re-import conftest as a second module."""
    return {"schema": TEST_SESSION_INFO["schema"], "url": TEST_SESSION_INFO["url"]}


@pytest.fixture
def db(pg_connection):
    from shared.db import Db

    yield Db(pg_connection)
    # A test may end mid-transaction (e.g. after asserting a constraint
    # violation); roll back first, then reset the tables for the next test.
    pg_connection.rollback()
    with pg_connection.cursor() as cur:
        cur.execute(
            "truncate terms_acknowledgements, terms_versions, commission_policies, "
            "payments, shipment_no_show_tracking, shipment_trips, shipment_bids, shipments, "
            "wallet_transactions, wallets, user_payment_preferences, saved_payment_methods, "
            "transporter_profiles "
            "restart identity cascade"
        )
    pg_connection.commit()


def seed_default_policies(db):
    """Mirror the production seed: both types at 20/80 plus Terms v1."""
    from shared import commissions

    one_time = commissions.create_policy_version(
        db, commissions.POLICY_TYPE_ONE_TIME, "20.00",
        "Initial platform commission rate (20% company / 80% transporter).",
        None, "2026-07-21T00:00:00",
    )
    agreement = commissions.create_policy_version(
        db, commissions.POLICY_TYPE_AGREEMENT, "20.00",
        "Initial platform commission rate (20% company / 80% transporter).",
        None, "2026-07-21T00:00:00",
    )
    commissions.create_terms_version(
        db, one_time["id"], agreement["id"],
        "Initial platform Terms.", None, "2026-07-21T00:00:00",
    )
    db.commit()


@pytest.fixture
def seeded_db(db):
    seed_default_policies(db)
    return db
