"""Test fixtures for the commission-policy suite.

Two tiers of tests:

- Pure calculation/validation tests run with no database at all.
- Database-backed tests are PostgreSQL integration tests. They require a
  DEDICATED test database configured via the TEST_SUPABASE_DB_URL environment
  variable. There is deliberately no fallback to SUPABASE_DB_URL: tests must
  never touch the production database. When TEST_SUPABASE_DB_URL is not set,
  the integration tests are skipped with a clear reason.

Isolation: each test session creates a uniquely named schema on the test
database, installs the commission tables there (mirroring
supabase/schema.sql, including CHECK constraints and the immutability
trigger), pins the connection's search_path to that schema, and drops the
schema again afterwards. Between tests the tables are truncated. The tests
reuse the production Db wrapper from shared.db — there is no second
database abstraction.
"""

import os
import sys
import uuid
from pathlib import Path

import pytest

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))


TEST_DB_ENV = "TEST_SUPABASE_DB_URL"

# Populated by the pg_connection fixture; read by tests that need a second
# independent connection into the same isolated schema.
TEST_SESSION_INFO = {}

SKIP_REASON = (
    "TEST_SUPABASE_DB_URL is not set; PostgreSQL integration tests require a "
    "dedicated test database and never fall back to SUPABASE_DB_URL."
)

# Mirrors the production tables from supabase/schema.sql that the commission
# helpers touch, including CHECK constraints, unique constraints and the
# immutability trigger. User references are plain columns here so the test
# schema stays self-contained.
DDL = """
create table commission_policies (
    id              bigint generated by default as identity primary key,
    policy_type     text not null
                    check (policy_type in ('one_time_order', 'agreement')),
    version_number  integer not null check (version_number >= 1),
    company_share_percent     numeric(5,2) not null
                    check (company_share_percent >= 0 and company_share_percent < 100),
    transporter_share_percent numeric(5,2) not null
                    check (transporter_share_percent > 0 and transporter_share_percent <= 100),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    created_by_admin_user_id bigint,
    created_at      timestamptz not null default now(),
    constraint commission_policies_type_version_unique unique (policy_type, version_number),
    constraint commission_policies_shares_sum_100
        check (company_share_percent + transporter_share_percent = 100)
);

create table terms_versions (
    id              bigint generated by default as identity primary key,
    version_number  integer not null unique check (version_number >= 1),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    one_time_policy_id  bigint not null references commission_policies (id),
    agreement_policy_id bigint not null references commission_policies (id),
    published_by_admin_user_id bigint,
    published_at    timestamptz not null default now()
);

create table terms_acknowledgements (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    terms_version_id bigint not null references terms_versions (id) on delete cascade,
    acknowledged_at timestamptz not null default now(),
    constraint terms_ack_user_version_unique unique (user_id, terms_version_id)
);

create or replace function prevent_version_mutation()
returns trigger language plpgsql as $$
begin
    raise exception 'published % rows are immutable — publish a new version instead', tg_table_name;
end;
$$;

create trigger trg_commission_policies_immutable
    before update or delete on commission_policies
    for each row execute function prevent_version_mutation();

create trigger trg_terms_versions_immutable
    before update or delete on terms_versions
    for each row execute function prevent_version_mutation();

create table wallets (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique,
    role            text not null,
    balance         numeric not null default 0,
    locked_balance  numeric not null default 0,
    minimum_required numeric not null default 0,
    is_minimum_met  boolean not null default false,
    completed_trips_count integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table wallet_transactions (
    id              bigint generated by default as identity primary key,
    wallet_id       bigint not null references wallets (id) on delete cascade,
    user_id         bigint not null,
    type            text not null,
    amount          numeric not null,
    gross_amount    numeric,
    gateway_fee     numeric default 0,
    description     text,
    reference_id    text,
    provider_name       text,
    provider_reference  text,
    balance_after   numeric not null,
    created_at      timestamptz not null default now()
);

create unique index uniq_wallet_topup_idempotency
    on wallet_transactions (user_id, reference_id)
    where type = 'topup' and reference_id is not null;

create table users (
    id              bigint generated by default as identity primary key,
    full_name       text not null default '',
    email           text not null default '',
    phone           text not null default '',
    cnic            text not null default '',
    role            text,
    legacy_role     text,
    city            text,
    address         text,
    about           text,
    last_login_at   timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table service_seeker_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references users (id) on delete cascade,
    company_name    text,
    business_type   text,
    transport_need  text,
    default_pickup_city text,
    billing_address text,
    total_shipments integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table everyday_user_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references users (id) on delete cascade,
    total_shipments integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create or replace function enforce_single_client_profile()
returns trigger language plpgsql as $$
declare
    other_table text := case tg_table_name
        when 'service_seeker_profiles' then 'everyday_user_profiles'
        else 'service_seeker_profiles' end;
    conflict boolean;
begin
    execute format('select exists(select 1 from %I where user_id = $1)', other_table)
        into conflict using new.user_id;
    if conflict then
        raise exception 'user % already has a % row', new.user_id, other_table;
    end if;
    return new;
end;
$$;

create trigger trg_service_seeker_single_profile
    before insert or update of user_id on service_seeker_profiles
    for each row execute function enforce_single_client_profile();
create trigger trg_everyday_single_profile
    before insert or update of user_id on everyday_user_profiles
    for each row execute function enforce_single_client_profile();

create table vehicles (
    id              bigint generated by default as identity primary key,
    owner_user_id   bigint not null,
    truck_number    text,
    truck_company   text,
    truck_model     text,
    truck_type      text,
    catalog_type_key text,
    capacity_tons   numeric,
    payload_min_tons numeric,
    payload_max_tons numeric,
    volume_min_cbm  numeric,
    volume_max_cbm  numeric,
    bed_length_ft   numeric,
    bed_width_ft    numeric,
    bed_height_ft   numeric,
    body_style      text,
    truck_photo_path text,
    current_city    text,
    current_lat     double precision,
    current_lng     double precision,
    service_radius_km numeric(6,2) not null default 100
        check (service_radius_km > 0 and service_radius_km <= 150),
    status          text not null default 'active',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint vehicles_current_coords_pair
        check (
            (current_lat is null and current_lng is null)
            or (current_lat is not null and current_lng is not null)
        )
);

create table shipments (
    id              bigint generated by default as identity primary key,
    client_user_id  bigint not null,
    status          text not null default 'open',
    -- Production has no default (server sets it); the test mirror defaults to
    -- 'business' so seed helpers that don't care about the kind still insert.
    seeker_kind_snapshot text not null default 'business'
        check (seeker_kind_snapshot in ('everyday', 'business')),
    goods_type      text,
    goods_category  text,
    goods_form      text,
    goods_commodity text,
    goods_weight_tons numeric,
    goods_volume_cbm  numeric,
    required_truck_types text,
    length_cm       numeric,
    width_cm        numeric,
    height_cm       numeric,
    volume_liters   numeric,
    quantity        integer,
    animal_count    integer,
    temperature_c   numeric,
    is_refrigerated boolean not null default false,
    is_hazardous    boolean not null default false,
    is_food_grade   boolean not null default false,
    estimated_budget numeric,
    notes           text,
    pickup_city     text,
    pickup_location text,
    pickup_lat      double precision,
    pickup_lng      double precision,
    dropoff_city    text,
    dropoff_location text,
    dropoff_lat     double precision,
    dropoff_lng     double precision,
    pickup_date     date,
    pickup_time     text,
    accepted_bid_id bigint,
    payment_amount  numeric,
    payment_status  text not null default 'pending',
    company_share_percent_snapshot     numeric(5,2),
    transporter_share_percent_snapshot numeric(5,2),
    commission_policy_id bigint,
    terms_version_id     bigint,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table shipment_bids (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references shipments (id) on delete cascade,
    transporter_user_id bigint not null,
    truck_id        bigint not null,
    bid_price       numeric not null,
    message         text,
    status          text not null default 'pending',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table shipment_trips (
    id              bigint generated by default as identity primary key,
    order_id        bigint not null references shipments (id) on delete cascade,
    accepted_bid_id bigint not null references shipment_bids (id),
    transporter_user_id bigint not null,
    truck_id        bigint not null,
    status          text not null default 'accepted',
    trip_started_at timestamptz,
    trip_completed_at timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table shipment_no_show_tracking (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references shipment_trips (id) on delete cascade,
    status          text not null default 'tracking',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table payments (
    id              bigint generated by default as identity primary key,
    trip_id         bigint not null references shipment_trips (id) on delete cascade,
    shipment_id     bigint references shipments (id) on delete set null,
    invoice_number  text not null unique,
    client_user_id  bigint not null,
    transporter_user_id bigint not null,
    bid_price       numeric not null,
    company_fee     numeric not null,
    transporter_amount numeric not null,
    company_share_percent     numeric(5,2),
    transporter_share_percent numeric(5,2),
    commission_policy_id bigint references commission_policies (id),
    terms_version_id bigint references terms_versions (id),
    wallet_funded_amount   numeric(12,2) not null default 0
        check (wallet_funded_amount >= 0),
    card_funded_amount     numeric(12,2) not null default 0
        check (card_funded_amount >= 0),
    processing_fee_percent numeric(5,2)
        check (processing_fee_percent is null or processing_fee_percent >= 0),
    processing_fee_amount  numeric(12,2) not null default 0
        check (processing_fee_amount >= 0),
    total_card_charge      numeric(14,2)
        check (total_card_charge is null or total_card_charge >= 0),
    funding_source         text
        check (funding_source is null or funding_source in ('wallet', 'card', 'wallet_card')),
    provider_name          text,
    provider_reference     text,
    idempotency_key        text,
    payment_method  text not null default 'wallet',
    status          text not null default 'paid'
                    check (status in ('processing', 'held', 'released', 'disputed', 'refunded', 'failed', 'paid')),
    held_at         timestamptz,
    released_at     timestamptz,
    refunded_at     timestamptz,
    pdf_path        text,
    paid_at         timestamptz,
    created_at      timestamptz not null default now()
);

create unique index uniq_payments_active_per_shipment
    on payments (shipment_id)
    where shipment_id is not null and status in ('processing', 'held', 'disputed', 'released');
create unique index uniq_payments_idempotency_key
    on payments (idempotency_key)
    where idempotency_key is not null;

create table saved_payment_methods (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    provider_name   text not null default 'dummycard',
    provider_token  text not null unique,
    card_brand      text not null default 'card',
    card_last_four  text not null check (card_last_four ~ '^[0-9]{4}$'),
    expiry_month    integer not null check (expiry_month between 1 and 12),
    expiry_year     integer not null check (expiry_year between 2000 and 2200),
    is_default      boolean not null default false,
    status          text not null default 'active'
                    check (status in ('active', 'removed')),
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint saved_payment_methods_user_row_unique unique (user_id, id)
);

create unique index uniq_saved_method_default_per_user
    on saved_payment_methods (user_id)
    where is_default and status = 'active';

create table user_payment_preferences (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique,
    default_payment_method_id bigint,
    auto_shortfall_charge_enabled boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint user_payment_preferences_method_owned_fk
        foreign key (user_id, default_payment_method_id)
        references saved_payment_methods (user_id, id)
        on delete set null (default_payment_method_id)
);

create table transporter_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique,
    company_name    text,
    fleet_size      text,
    withdrawal_tier integer not null default 0,
    withdrawal_tier_expires_at text,
    payout_card_token     text,
    payout_card_brand     text,
    payout_card_last_four text
        check (payout_card_last_four is null or payout_card_last_four ~ '^[0-9]{4}$'),
    payout_card_holder text,
    payout_card_expiry text,
    payout_card_bank   text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create unique index uniq_payout_card_token
    on transporter_profiles (payout_card_token)
    where payout_card_token is not null;
"""


@pytest.fixture(scope="session")
def pg_connection():
    test_url = os.environ.get(TEST_DB_ENV, "").strip()
    if not test_url:
        pytest.skip(SKIP_REASON)
    if test_url == os.environ.get("SUPABASE_DB_URL", "").strip():
        pytest.skip(
            "TEST_SUPABASE_DB_URL matches SUPABASE_DB_URL; integration tests "
            "require a dedicated test database, not the application database."
        )

    import psycopg2

    conn = psycopg2.connect(test_url)
    schema = f"dtx_test_{uuid.uuid4().hex[:12]}"
    # Tests that open extra connections (genuine concurrency) look up the
    # session's isolated schema + URL here (psycopg2 connections don't accept
    # arbitrary attributes).
    TEST_SESSION_INFO["schema"] = schema
    TEST_SESSION_INFO["url"] = test_url
    try:
        with conn.cursor() as cur:
            cur.execute(f'create schema "{schema}"')
            cur.execute(f'set search_path to "{schema}"')
            cur.execute(DDL)
        conn.commit()
        yield conn
    finally:
        conn.rollback()
        with conn.cursor() as cur:
            cur.execute(f'drop schema "{schema}" cascade')
        conn.commit()
        conn.close()


@pytest.fixture
def pg_session_info(pg_connection):
    """The isolated schema + URL, for tests that open their own connections
    (e.g. genuine concurrency and route-level tests). Exposed as a fixture so
    callers never re-import conftest as a second module."""
    return {"schema": TEST_SESSION_INFO["schema"], "url": TEST_SESSION_INFO["url"]}


@pytest.fixture
def db(pg_connection):
    from shared.db import Db

    yield Db(pg_connection)
    # A test may end mid-transaction (e.g. after asserting a constraint
    # violation); roll back first, then reset the tables for the next test.
    pg_connection.rollback()
    with pg_connection.cursor() as cur:
        cur.execute(
            "truncate terms_acknowledgements, terms_versions, commission_policies, "
            "payments, shipment_no_show_tracking, shipment_trips, shipment_bids, shipments, "
            "wallet_transactions, wallets, user_payment_preferences, saved_payment_methods, "
            "transporter_profiles, service_seeker_profiles, everyday_user_profiles, "
            "vehicles, users "
            "restart identity cascade"
        )
    pg_connection.commit()


def seed_default_policies(db):
    """Mirror the production seed: both types at 20/80 plus Terms v1."""
    from shared import commissions

    one_time = commissions.create_policy_version(
        db, commissions.POLICY_TYPE_ONE_TIME, "20.00",
        "Initial platform commission rate (20% company / 80% transporter).",
        None, "2026-07-21T00:00:00",
    )
    agreement = commissions.create_policy_version(
        db, commissions.POLICY_TYPE_AGREEMENT, "20.00",
        "Initial platform commission rate (20% company / 80% transporter).",
        None, "2026-07-21T00:00:00",
    )
    commissions.create_terms_version(
        db, one_time["id"], agreement["id"],
        "Initial platform Terms.", None, "2026-07-21T00:00:00",
    )
    db.commit()


@pytest.fixture
def seeded_db(db):
    seed_default_policies(db)
    return db


# ---------------------------------------------------------------------------
# Route-level Flask app + client fixtures (shared by the route test modules)
# ---------------------------------------------------------------------------

@pytest.fixture
def app_env(seeded_db, pg_session_info, monkeypatch):
    """Flask app wired to the test schema + a stub user registry.

    Returns (app, ctx, seeded_db) where ctx holds mutable test state (current
    user). The route modules' open_db() is redirected to a fresh connection
    into the same isolated schema so handlers run their own real transactions,
    exactly like production.
    """
    import psycopg2
    from contextlib import contextmanager
    from flask import Flask

    from shared.db import Db
    import auth.helpers as auth_helpers
    import auth.routes as auth_routes
    import orders.routes as orders_routes
    import payments.routes as payments_routes
    import wallet.routes as wallet_routes
    import wallet.helpers as wallet_helpers
    import agreements.routes as agreements_routes

    schema = pg_session_info["schema"]
    url = pg_session_info["url"]

    open_connections = []

    @contextmanager
    def test_open_db():
        conn = psycopg2.connect(url)
        open_connections.append(conn)
        try:
            with conn.cursor() as cur:
                cur.execute(f'set search_path to "{schema}"')
            wrapper = Db(conn)
            yield wrapper
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    for module in (orders_routes, payments_routes, wallet_routes, wallet_helpers,
                   auth_helpers, auth_routes, agreements_routes):
        if hasattr(module, "open_db"):
            monkeypatch.setattr(module, "open_db", test_open_db)

    ctx = {"user": None}

    def fake_get_user_by_id(user_id):
        user = ctx["user"]
        if user and str(user["id"]) == str(user_id):
            return dict(user)
        return None

    monkeypatch.setattr(auth_helpers, "get_user_by_id", fake_get_user_by_id)

    app = Flask(__name__)
    app.config["SECRET_KEY"] = "test-secret"
    app.config["SESSION_COOKIE_SECURE"] = False
    app.register_blueprint(orders_routes.orders_blueprint)
    app.register_blueprint(payments_routes.payments_blueprint)
    app.register_blueprint(wallet_routes.wallet_blueprint)
    app.register_blueprint(auth_routes.auth_blueprint)
    app.register_blueprint(agreements_routes.agreements_blueprint)

    yield app, ctx, seeded_db

    for conn in open_connections:
        try:
            conn.close()
        except Exception:
            pass


@pytest.fixture
def client(app_env):
    app, ctx, db = app_env
    test_client = app.test_client()

    def login(user):
        ctx["user"] = user
        with test_client.session_transaction() as sess:
            sess["user_id"] = user["id"]
            sess["csrf_token"] = "test-csrf-token"

    test_client.login = login
    test_client.ctx = ctx
    test_client.db = db
    return test_client
