"""Test fixtures for the commission-policy suite.

Two tiers of tests:

- Pure calculation/validation tests run with no database at all.
- Database-backed tests are PostgreSQL integration tests. They require a
  DEDICATED test database configured via the TEST_SUPABASE_DB_URL environment
  variable. There is deliberately no fallback to SUPABASE_DB_URL: tests must
  never touch the production database. When TEST_SUPABASE_DB_URL is not set,
  the integration tests are skipped with a clear reason.

Isolation: each test session creates a uniquely named schema on the test
database, installs the commission tables there (mirroring
supabase/schema.sql, including CHECK constraints and the immutability
trigger), pins the connection's search_path to that schema, and drops the
schema again afterwards. Between tests the tables are truncated. The tests
reuse the production Db wrapper from shared.db — there is no second
database abstraction.
"""

import os
import sys
import uuid
from pathlib import Path

import pytest

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))


TEST_DB_ENV = "TEST_SUPABASE_DB_URL"
SKIP_REASON = (
    "TEST_SUPABASE_DB_URL is not set; PostgreSQL integration tests require a "
    "dedicated test database and never fall back to SUPABASE_DB_URL."
)

# Mirrors the production tables from supabase/schema.sql that the commission
# helpers touch, including CHECK constraints, unique constraints and the
# immutability trigger. User references are plain columns here so the test
# schema stays self-contained.
DDL = """
create table commission_policies (
    id              bigint generated by default as identity primary key,
    policy_type     text not null
                    check (policy_type in ('one_time_order', 'agreement')),
    version_number  integer not null check (version_number >= 1),
    company_share_percent     numeric(5,2) not null
                    check (company_share_percent >= 0 and company_share_percent < 100),
    transporter_share_percent numeric(5,2) not null
                    check (transporter_share_percent > 0 and transporter_share_percent <= 100),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    created_by_admin_user_id bigint,
    created_at      timestamptz not null default now(),
    constraint commission_policies_type_version_unique unique (policy_type, version_number),
    constraint commission_policies_shares_sum_100
        check (company_share_percent + transporter_share_percent = 100)
);

create table terms_versions (
    id              bigint generated by default as identity primary key,
    version_number  integer not null unique check (version_number >= 1),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    one_time_policy_id  bigint not null references commission_policies (id),
    agreement_policy_id bigint not null references commission_policies (id),
    published_by_admin_user_id bigint,
    published_at    timestamptz not null default now()
);

create table terms_acknowledgements (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null,
    terms_version_id bigint not null references terms_versions (id) on delete cascade,
    acknowledged_at timestamptz not null default now(),
    constraint terms_ack_user_version_unique unique (user_id, terms_version_id)
);

create or replace function prevent_version_mutation()
returns trigger language plpgsql as $$
begin
    raise exception 'published % rows are immutable — publish a new version instead', tg_table_name;
end;
$$;

create trigger trg_commission_policies_immutable
    before update or delete on commission_policies
    for each row execute function prevent_version_mutation();

create trigger trg_terms_versions_immutable
    before update or delete on terms_versions
    for each row execute function prevent_version_mutation();
"""


@pytest.fixture(scope="session")
def pg_connection():
    test_url = os.environ.get(TEST_DB_ENV, "").strip()
    if not test_url:
        pytest.skip(SKIP_REASON)
    if test_url == os.environ.get("SUPABASE_DB_URL", "").strip():
        pytest.skip(
            "TEST_SUPABASE_DB_URL matches SUPABASE_DB_URL; integration tests "
            "require a dedicated test database, not the application database."
        )

    import psycopg2

    conn = psycopg2.connect(test_url)
    schema = f"dtx_test_{uuid.uuid4().hex[:12]}"
    try:
        with conn.cursor() as cur:
            cur.execute(f'create schema "{schema}"')
            cur.execute(f'set search_path to "{schema}"')
            cur.execute(DDL)
        conn.commit()
        yield conn
    finally:
        conn.rollback()
        with conn.cursor() as cur:
            cur.execute(f'drop schema "{schema}" cascade')
        conn.commit()
        conn.close()


@pytest.fixture
def db(pg_connection):
    from shared.db import Db

    yield Db(pg_connection)
    # A test may end mid-transaction (e.g. after asserting a constraint
    # violation); roll back first, then reset the tables for the next test.
    pg_connection.rollback()
    with pg_connection.cursor() as cur:
        cur.execute(
            "truncate terms_acknowledgements, terms_versions, commission_policies "
            "restart identity cascade"
        )
    pg_connection.commit()


def seed_default_policies(db):
    """Mirror the production seed: both types at 20/80 plus Terms v1."""
    from shared import commissions

    one_time = commissions.create_policy_version(
        db, commissions.POLICY_TYPE_ONE_TIME, "20.00",
        "Initial platform commission rate (20% company / 80% transporter).",
        None, "2026-07-21T00:00:00",
    )
    agreement = commissions.create_policy_version(
        db, commissions.POLICY_TYPE_AGREEMENT, "20.00",
        "Initial platform commission rate (20% company / 80% transporter).",
        None, "2026-07-21T00:00:00",
    )
    commissions.create_terms_version(
        db, one_time["id"], agreement["id"],
        "Initial platform Terms.", None, "2026-07-21T00:00:00",
    )
    db.commit()


@pytest.fixture
def seeded_db(db):
    seed_default_policies(db)
    return db
