"""Smoke test for the actual payment-foundation migration files.

Unlike the other integration tests (which build the final tables directly),
this test proves the shipped migration SQL works: it stands up a minimal
pre-migration baseline in a DISPOSABLE database, runs the real files from
supabase/migrations/, and verifies columns, constraints, indexes, RLS,
the safe view, the payout-card tokenization and the wallet backfill — then
re-runs both files to prove the idempotency guards hold.

Isolation: a brand-new throwaway database is created on the same server as
TEST_SUPABASE_DB_URL and dropped afterwards. If the test role cannot create
databases (e.g. managed Supabase), the test skips with a clear reason. It
never falls back to SUPABASE_DB_URL and never runs against a shared/live
database.
"""

import os
from pathlib import Path

import pytest

BACKEND_DIR = Path(__file__).resolve().parent.parent
MIGRATIONS_DIR = BACKEND_DIR.parent / "supabase" / "migrations"
PAYMENT_MIGRATION = MIGRATIONS_DIR / "20260721120000_one_time_payment_foundation.sql"
PAYOUT_MIGRATION = MIGRATIONS_DIR / "20260721130000_tokenize_payout_cards.sql"

TEST_DB_ENV = "TEST_SUPABASE_DB_URL"

# Minimal "main-branch" baseline: exactly the objects the phase-2 migrations
# depend on (helper functions + the tables they ALTER / reference), in the
# public schema the migrations target by fully-qualified name.
BASELINE_DDL = """
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end; $$;

create or replace function public.current_app_user_id()
returns bigint language sql stable as $$ select null::bigint $$;

create or replace function public.is_admin()
returns boolean language sql stable as $$ select false $$;

create table public.users (
    id bigint generated by default as identity primary key,
    email text
);

create table public.commission_policies (
    id bigint generated by default as identity primary key,
    policy_type text not null
);

create table public.terms_versions (
    id bigint generated by default as identity primary key,
    version_number integer not null
);

create table public.shipments (
    id bigint generated by default as identity primary key,
    client_user_id bigint not null,
    status text not null default 'open'
);

create table public.shipment_trips (
    id bigint generated by default as identity primary key,
    order_id bigint not null
);

create table public.agreements (
    id bigint generated by default as identity primary key,
    client_user_id bigint not null
);

create table public.payments (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references public.shipment_trips (id) on delete cascade,
    shipment_id bigint references public.shipments (id) on delete set null,
    invoice_number text not null unique,
    client_user_id bigint not null references public.users (id),
    transporter_user_id bigint not null references public.users (id),
    bid_price numeric not null,
    company_fee numeric not null,
    transporter_amount numeric not null,
    company_share_percent numeric(5,2),
    transporter_share_percent numeric(5,2),
    commission_policy_id bigint references public.commission_policies (id),
    payment_method text not null default 'wallet',
    status text not null default 'paid',
    pdf_path text,
    paid_at timestamptz,
    created_at timestamptz not null default now()
);

create table public.wallets (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users (id),
    role text not null,
    balance numeric not null default 0,
    locked_balance numeric not null default 0,
    minimum_required numeric not null default 0,
    is_minimum_met boolean not null default false
);

create table public.wallet_transactions (
    id bigint generated by default as identity primary key,
    wallet_id bigint not null references public.wallets (id) on delete cascade,
    user_id bigint not null references public.users (id) on delete cascade,
    type text not null,
    amount numeric not null,
    gross_amount numeric,
    gateway_fee numeric default 0,
    description text,
    reference_id text,
    balance_after numeric not null,
    created_at timestamptz not null default now()
);

create table public.transporter_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users (id),
    payout_card_number text,
    payout_card_holder text,
    payout_card_expiry text,
    payout_card_bank text
);
"""

# A little seed data so the backfills have something to convert.
BASELINE_SEED = """
insert into public.users (id, email) values (1, 'client@example.com'), (2, 'fleet@example.com');
insert into public.wallets (user_id, role, balance, minimum_required, is_minimum_met)
    values (1, 'client', 5000, 20000, false), (2, 'transporter', 60000, 30000, true);
insert into public.transporter_profiles (user_id, payout_card_number, payout_card_holder, payout_card_expiry, payout_card_bank)
    values (2, '4111 1111 1111 1234', 'Fleet Owner', '11/29', 'HBL');
"""


def _admin_conn_and_dbname(test_url):
    import psycopg2
    from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

    conn = psycopg2.connect(test_url)
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    return conn


@pytest.fixture
def migration_db():
    """A fresh disposable database with the pre-migration baseline applied."""
    test_url = os.environ.get(TEST_DB_ENV, "").strip()
    if not test_url:
        pytest.skip(
            "TEST_SUPABASE_DB_URL is not set; the migration smoke test needs a "
            "dedicated PostgreSQL server and never falls back to SUPABASE_DB_URL."
        )
    if test_url == os.environ.get("SUPABASE_DB_URL", "").strip():
        pytest.skip("TEST_SUPABASE_DB_URL must not equal SUPABASE_DB_URL.")

    import psycopg2

    new_db = f"dtx_migtest_{os.urandom(6).hex()}"
    # Connect to the maintenance database to create/drop the throwaway one.
    if "/" in test_url.rsplit("@", 1)[-1]:
        base, _old_db = test_url.rsplit("/", 1)
        admin_url = base + "/postgres"
        new_url = base + "/" + new_db
    else:
        pytest.skip("TEST_SUPABASE_DB_URL has no database component to derive a disposable database from.")

    try:
        admin = _admin_conn_and_dbname(admin_url)
    except Exception as exc:
        pytest.skip(f"Cannot reach a maintenance database to create a disposable one: {exc}")

    try:
        with admin.cursor() as cur:
            cur.execute(f'create database "{new_db}"')
    except psycopg2.Error as exc:
        admin.close()
        pytest.skip(f"Test role cannot CREATE DATABASE (managed environment?): {exc}")

    conn = psycopg2.connect(new_url)
    try:
        with conn.cursor() as cur:
            cur.execute(BASELINE_DDL)
            cur.execute(BASELINE_SEED)
        conn.commit()
        yield conn
    finally:
        conn.close()
        with admin.cursor() as cur:
            cur.execute(
                "select pg_terminate_backend(pid) from pg_stat_activity where datname = %s",
                (new_db,),
            )
            cur.execute(f'drop database if exists "{new_db}"')
        admin.close()


def _run_sql_file(conn, path):
    with conn.cursor() as cur:
        cur.execute(path.read_text(encoding="utf-8"))
    conn.commit()


def _columns(conn, table):
    with conn.cursor() as cur:
        cur.execute(
            "select column_name from information_schema.columns "
            "where table_schema = 'public' and table_name = %s",
            (table,),
        )
        return {r[0] for r in cur.fetchall()}


def _index_predicate(conn, index_name):
    with conn.cursor() as cur:
        cur.execute("select indexdef from pg_indexes where indexname = %s", (index_name,))
        row = cur.fetchone()
        return row[0] if row else None


def test_payment_migration_applies_and_is_idempotent(migration_db):
    conn = migration_db

    # Run the real migration files, in order.
    _run_sql_file(conn, PAYMENT_MIGRATION)
    _run_sql_file(conn, PAYOUT_MIGRATION)

    # --- payments: audit columns + status constraint ---
    payment_cols = _columns(conn, "payments")
    for col in (
        "wallet_funded_amount", "card_funded_amount", "processing_fee_percent",
        "processing_fee_amount", "total_card_charge", "funding_source",
        "provider_name", "provider_reference", "idempotency_key",
        "terms_version_id", "held_at", "released_at", "refunded_at",
    ):
        assert col in payment_cols, f"payments.{col} missing after migration"

    with conn.cursor() as cur:
        cur.execute(
            "select pg_get_constraintdef(oid) from pg_constraint "
            "where conname = 'payments_status_check'"
        )
        status_def = cur.fetchone()[0]
    for status in ("processing", "held", "released", "disputed", "refunded", "failed"):
        assert status in status_def

    # --- active-payment predicate must include disputed ---
    predicate = _index_predicate(conn, "uniq_payments_active_per_shipment")
    assert predicate and "disputed" in predicate
    assert _index_predicate(conn, "uniq_payments_idempotency_key") is not None

    # --- new tables + safe view ---
    assert _columns(conn, "saved_payment_methods")
    assert _columns(conn, "user_payment_preferences")
    with conn.cursor() as cur:
        cur.execute("select 1 from information_schema.views where table_name = 'saved_payment_methods_safe'")
        assert cur.fetchone() is not None
        # The safe view must not expose the provider token.
        cur.execute(
            "select column_name from information_schema.columns "
            "where table_name = 'saved_payment_methods_safe'"
        )
        view_cols = {r[0] for r in cur.fetchall()}
    assert "provider_token" not in view_cols
    assert view_cols == {
        "id", "card_brand", "card_last_four", "expiry_month",
        "expiry_year", "is_default", "status", "created_at",
    }

    # --- composite ownership FK on preferences ---
    with conn.cursor() as cur:
        cur.execute(
            "select 1 from pg_constraint where conname = 'user_payment_preferences_method_owned_fk'"
        )
        assert cur.fetchone() is not None

    # --- RLS enabled ---
    with conn.cursor() as cur:
        cur.execute(
            "select relrowsecurity from pg_class where relname = 'saved_payment_methods'"
        )
        assert cur.fetchone()[0] is True
        cur.execute(
            "select count(*) from pg_policies where tablename = 'saved_payment_methods'"
        )
        assert cur.fetchone()[0] >= 1

    # --- wallet backfill: client minimum released, transporter untouched ---
    with conn.cursor() as cur:
        cur.execute("select minimum_required, is_minimum_met from wallets where user_id = 1")
        client_min, client_met = cur.fetchone()
        cur.execute("select minimum_required, is_minimum_met from wallets where user_id = 2")
        transporter_min, transporter_met = cur.fetchone()
    assert float(client_min) == 0.0 and client_met is True
    assert float(transporter_min) == 30000.0 and transporter_met is True  # unchanged

    # --- payout card: raw column dropped, tokenized data backfilled ---
    profile_cols = _columns(conn, "transporter_profiles")
    assert "payout_card_number" not in profile_cols
    for col in ("payout_card_token", "payout_card_brand", "payout_card_last_four"):
        assert col in profile_cols
    with conn.cursor() as cur:
        cur.execute(
            "select payout_card_last_four, payout_card_brand, payout_card_token "
            "from transporter_profiles where user_id = 2"
        )
        last_four, brand, token = cur.fetchone()
    assert last_four == "1234"
    assert brand == "visa"
    assert token and token.startswith("dummytok_")

    # --- wallet_transactions: provider columns + top-up idempotency index ---
    wt_cols = _columns(conn, "wallet_transactions")
    assert "provider_name" in wt_cols and "provider_reference" in wt_cols
    assert _index_predicate(conn, "uniq_wallet_topup_idempotency") is not None

    # --- total_card_charge widened to numeric(14,2) ---
    with conn.cursor() as cur:
        cur.execute(
            "select numeric_precision, numeric_scale from information_schema.columns "
            "where table_name = 'payments' and column_name = 'total_card_charge'"
        )
        precision, scale = cur.fetchone()
    assert (precision, scale) == (14, 2)

    # --- payout card integrity: unique token index + last-four check ---
    assert _index_predicate(conn, "uniq_payout_card_token") is not None
    with conn.cursor() as cur:
        cur.execute(
            "select 1 from pg_constraint where conname = 'transporter_profiles_last_four_check'"
        )
        assert cur.fetchone() is not None

    # --- idempotency: re-running both files is safe ---
    _run_sql_file(conn, PAYMENT_MIGRATION)
    _run_sql_file(conn, PAYOUT_MIGRATION)
    assert "wallet_funded_amount" in _columns(conn, "payments")
    assert "payout_card_number" not in _columns(conn, "transporter_profiles")


def test_saved_method_privileges_enforced(migration_db):
    """Prove the claimed column/table privileges and own-row RLS by acting as
    a real 'authenticated' role.

    Skips only the privilege assertions (with a precise reason) when the test
    role cannot create roles.
    """
    conn = migration_db

    # Roles must exist BEFORE the migration so its grant block applies to them.
    # Roles are cluster-global; drop any leftovers from a previous run first.
    import psycopg2
    try:
        with conn.cursor() as cur:
            for role in ("authenticated", "anon"):
                cur.execute("select 1 from pg_roles where rolname = %s", (role,))
                if cur.fetchone():
                    cur.execute(f"drop owned by {role} cascade")
                    cur.execute(f"drop role {role}")
            cur.execute("create role anon nologin")
            cur.execute("create role authenticated nologin")
        conn.commit()
    except psycopg2.Error as exc:
        conn.rollback()
        pytest.skip(f"Cannot create test roles for privilege assertions: {exc}")

    try:
        # current_app_user_id() reads a GUC so we can act as different users.
        with conn.cursor() as cur:
            cur.execute(
                "create or replace function public.current_app_user_id() returns bigint "
                "language sql stable as $$ select nullif(current_setting('app.uid', true), '')::bigint $$"
            )
        conn.commit()

        _run_sql_file(conn, PAYMENT_MIGRATION)
        _run_sql_file(conn, PAYOUT_MIGRATION)

        # Two users each own one saved card.
        with conn.cursor() as cur:
            cur.execute("insert into public.users (id, email) values (10,'a@x'),(11,'b@x') on conflict do nothing")
            cur.execute(
                "insert into public.saved_payment_methods "
                "(user_id, provider_token, card_brand, card_last_four, expiry_month, expiry_year) "
                "values (10,'tok-a','visa','1111',1,2030),(11,'tok-b','visa','2222',1,2030)"
            )
            cur.execute(
                "grant usage on schema public to authenticated"
            )
        conn.commit()

        # Act as 'authenticated' user 10.
        with conn.cursor() as cur:
            cur.execute("set role authenticated")
            cur.execute("set app.uid = '10'")

            # Cannot read the token or user_id columns of the base table.
            for secret in ("provider_token", "user_id"):
                cur.execute("rollback")  # clear any aborted state
                cur.execute("set role authenticated")
                cur.execute("set app.uid = '10'")
                try:
                    cur.execute(f"select {secret} from public.saved_payment_methods")
                    got = "allowed"
                except psycopg2.Error:
                    got = "denied"
                conn.rollback()
                assert got == "denied", f"authenticated must not read {secret}"

            # Cannot write the base table.
            cur.execute("set role authenticated")
            cur.execute("set app.uid = '10'")
            try:
                cur.execute(
                    "insert into public.saved_payment_methods "
                    "(user_id, provider_token, card_brand, card_last_four, expiry_month, expiry_year) "
                    "values (10,'tok-x','visa','9999',1,2030)"
                )
                wrote = "allowed"
            except psycopg2.Error:
                wrote = "denied"
            conn.rollback()
            assert wrote == "denied"

            # The safe view exposes only approved columns, own rows only.
            cur.execute("set role authenticated")
            cur.execute("set app.uid = '10'")
            cur.execute("select * from public.saved_payment_methods_safe")
            view_cols = {d[0] for d in cur.description}
            rows = cur.fetchall()
            conn.rollback()
            assert "provider_token" not in view_cols and "user_id" not in view_cols
            assert len(rows) == 1                    # only user 10's row is visible

        # Composite FK blocks pointing a preference at another user's method.
        with conn.cursor() as cur:
            cur.execute("reset role")
            cur.execute("select id from public.saved_payment_methods where user_id = 11")
            other_method_id = cur.fetchone()[0]
            try:
                cur.execute(
                    "insert into public.user_payment_preferences "
                    "(user_id, default_payment_method_id) values (10, %s)",
                    (other_method_id,),
                )
                cross = "allowed"
            except psycopg2.Error:
                cross = "denied"
            conn.rollback()
        assert cross == "denied", "composite FK must reject a cross-user default method"
    finally:
        with conn.cursor() as cur:
            cur.execute("reset role")
            # Drop granted privileges/owned objects before dropping the roles.
            for role in ("authenticated", "anon"):
                cur.execute(
                    "select 1 from pg_roles where rolname = %s", (role,)
                )
                if cur.fetchone():
                    cur.execute(f"drop owned by {role} cascade")
                    cur.execute(f"drop role {role}")
        conn.commit()
