"""Forward-migration test for the everyday-user separation.

Builds a minimal PRE-migration fixture (users + old customers + shipments with
area columns) in a throwaway database, applies the real migration file, and
asserts the final state: customers gone, area columns gone, profiles split by
customer_type/legacy_role, nobody in both tables, RLS own-row policies present.

Requires a server the test user can CREATE DATABASE on. Skipped (not failed)
when that is not permitted (e.g. a locked-down managed test database) or when
TEST_SUPABASE_DB_URL is unset.
"""

import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest

MIGRATION = (
    Path(__file__).resolve().parent.parent.parent
    / "supabase" / "migrations" / "20260723090000_everyday_user_separation.sql"
)

PRELUDE = """
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end; $$;
create or replace function public.is_admin() returns boolean language sql as $$ select false $$;
create or replace function public.is_dispatcher() returns boolean language sql as $$ select false $$;
create or replace function public.current_app_user_id() returns bigint language sql as $$ select null::bigint $$;

create table public.users (
    id bigint generated by default as identity primary key,
    email text not null unique, legacy_role text
);
create table public.customers (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    customer_type text, company_name text, business_type text, transport_need text,
    default_pickup_city text, default_pickup_area text, billing_address text,
    total_shipments integer not null default 0,
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.shipments (
    id bigint generated by default as identity primary key,
    client_user_id bigint not null references public.users(id) on delete cascade,
    pickup_city text, pickup_area text not null default '',
    dropoff_city text, dropoff_area text not null default '',
    status text not null default 'open',
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.users (email, legacy_role) values
  ('biz@test','service_seeker'), ('eve@test','everyday_user'),
  ('cli@test','client'), ('amb@test', null);
insert into public.customers (user_id, customer_type, company_name, default_pickup_area) values
  (1,'business','BizCo','Area A'), (2,'individual',null,'Area B'),
  (3,'business','CliCo',null), (4,'individual',null,null);
insert into public.shipments (client_user_id, pickup_city, pickup_area, dropoff_city, dropoff_area) values
  (1,'Lahore','AreaX','Karachi','AreaY'), (2,'Multan','AreaZ','Sialkot','AreaW');
"""


@pytest.fixture
def throwaway_db():
    psycopg2 = pytest.importorskip("psycopg2")
    url = os.environ.get("TEST_SUPABASE_DB_URL", "").strip()
    if not url:
        pytest.skip("TEST_SUPABASE_DB_URL not set")
    parts = urlsplit(url)
    admin_url = urlunsplit((parts.scheme, parts.netloc, "/postgres", "", ""))
    dbname = "dtx_migtest_ev"
    try:
        admin = psycopg2.connect(admin_url)
    except Exception as exc:  # pragma: no cover
        pytest.skip(f"cannot reach admin database: {exc}")
    admin.autocommit = True
    try:
        with admin.cursor() as cur:
            cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
            cur.execute(f"CREATE DATABASE {dbname}")
    except Exception as exc:
        admin.close()
        pytest.skip(f"CREATE DATABASE not permitted: {exc}")
    admin.close()
    child_url = urlunsplit((parts.scheme, parts.netloc, "/" + dbname, "", ""))
    conn = psycopg2.connect(child_url)
    try:
        yield conn
    finally:
        conn.close()
        admin = psycopg2.connect(admin_url)
        admin.autocommit = True
        with admin.cursor() as cur:
            cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
        admin.close()


def test_migration_splits_and_drops(throwaway_db):
    conn = throwaway_db
    with conn.cursor() as cur:
        cur.execute(PRELUDE)
        conn.commit()
        cur.execute(MIGRATION.read_text(encoding="utf-8"))
        conn.commit()

        def scalar(sql):
            cur.execute(sql)
            return cur.fetchone()[0]

        # #5 customers gone, area columns gone.
        assert not scalar("select exists(select 1 from information_schema.tables "
                          "where table_schema='public' and table_name='customers')")
        assert not scalar("select exists(select 1 from information_schema.columns "
                          "where table_name='shipments' and column_name='pickup_area')")
        assert not scalar("select exists(select 1 from information_schema.columns "
                          "where table_name='shipments' and column_name='dropoff_area')")
        # #4 migrated to the right tables (business: 1,3 ; everyday: 2,4).
        assert scalar("select array_agg(user_id order by user_id) from public.service_seeker_profiles") == [1, 3]
        assert scalar("select array_agg(user_id order by user_id) from public.everyday_user_profiles") == [2, 4]
        # #3 nobody in both.
        assert scalar("select count(*) from public.service_seeker_profiles s "
                      "join public.everyday_user_profiles e on e.user_id=s.user_id") == 0
        # seeker_kind_snapshot backfilled + NOT NULL.
        assert scalar("select array_agg(seeker_kind_snapshot order by id) from public.shipments") == ["business", "everyday"]
        assert scalar("select is_nullable from information_schema.columns where "
                      "table_name='shipments' and column_name='seeker_kind_snapshot'") == "NO"
        # default_pickup_area not copied into the new business table.
        assert not scalar("select exists(select 1 from information_schema.columns where "
                          "table_name='service_seeker_profiles' and column_name='default_pickup_area')")
        # #6 own-row RLS policies exist on both new tables.
        policies = scalar("select array_agg(policyname order by policyname) from pg_policies "
                          "where tablename in ('service_seeker_profiles','everyday_user_profiles')")
        assert "service_seeker_profile_own" in policies
        assert "everyday_user_profile_own" in policies
