"""Tests for the dispatcher-role removal (migration 20260723110000).

Two independent construction paths, per the task:

  * PRE-MIGRATION FIXTURE (`PRELUDE`) — a self-contained, dispatcher-bearing
    database that faithfully reproduces every object migration 20260723110000
    touches (the app_role enum WITH dispatcher, is_dispatcher(), the signup
    trigger's dispatcher mapping, all dispatcher RLS/storage policies, and the
    neighbouring admin/owner/transporter/client/seeker/everyday policies). The
    migration is applied to it and the end state is asserted. This mirrors the
    repo's existing migration-test convention (test_migration_everyday's
    PRELUDE, test_profile_rls's SETUP) and stays valid forever — it does not
    depend on git history that moves once this branch merges.

  * FULL CANONICAL SCHEMA — the real supabase/schema.sql (the head schema,
    i.e. the state a database reaches after every migration through
    20260723100000). A fresh load must already be dispatcher-free (a new
    deployment never gets a dispatcher), and applying the removal migration on
    top must be a clean no-op (idempotency on the real, complete policy set).

Pure-calculation tests (no database) cover the application layer: dispatcher is
neither a legacy mapping nor an accepted signup role.

The database tests need a server the test user can CREATE DATABASE on. They are
SKIPPED (never failed) when that is not permitted (e.g. a locked-down managed
Supabase) or when TEST_SUPABASE_DB_URL is unset — exactly like the other
migration tests in this suite.
"""

import os
import uuid
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_SQL = (REPO_ROOT / "supabase" / "schema.sql")
MIGRATION_SQL = (REPO_ROOT / "supabase" / "migrations"
                 / "20260723110000_remove_dispatcher_role.sql")

# Minimal Supabase-compatible stubs so schema.sql / the prelude load on vanilla
# PostgreSQL (Supabase provides auth + storage schemas and the anon/authenticated
# roles in the real project).
STUBS = """
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;
do $r$ begin
  if not exists (select 1 from pg_roles where rolname='anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname='service_role') then create role service_role nologin; end if;
end $r$;
create schema if not exists auth;
create table if not exists auth.users (
    id uuid primary key default gen_random_uuid(),
    email text,
    raw_user_meta_data jsonb not null default '{}'::jsonb);
create or replace function auth.uid() returns uuid language sql stable as $$
    select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create schema if not exists storage;
create table if not exists storage.buckets (id text primary key, name text, public boolean default false);
create table if not exists storage.objects (
    id uuid primary key default gen_random_uuid(), bucket_id text, name text);
"""

# Faithful pre-migration ("20260723100000") state, dispatcher present. Column
# shapes on public.users match schema.sql closely enough for the real
# handle_new_auth_user replacement (which inserts full_name/phone/cnic) to run.
PRELUDE = STUBS + """
create type public.app_role as enum
    ('admin','dispatcher','customer','transporter','fuel_station_manager','shopkeeper');

create table public.users (
  id bigint generated by default as identity primary key,
  auth_id uuid unique references auth.users(id) on delete set null,
  email text not null unique, full_name text not null default '',
  phone text not null default '', cnic text not null default '',
  role public.app_role not null default 'customer', legacy_role text);
create table public.service_seeker_profiles (id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade, company_name text);
create table public.everyday_user_profiles (id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade);
create table public.drivers (id bigint generated by default as identity primary key, owner_user_id bigint);
create table public.vehicles (id bigint generated by default as identity primary key, owner_user_id bigint, status text default 'active');
create table public.shipments (id bigint generated by default as identity primary key, client_user_id bigint, status text default 'open');
create table public.shipment_bids (id bigint generated by default as identity primary key, order_id bigint, transporter_user_id bigint);
create table public.shipment_trips (id bigint generated by default as identity primary key, order_id bigint, transporter_user_id bigint);
create table public.shipment_status_history (id bigint generated by default as identity primary key, shipment_id bigint);
create table public.documents (id bigint generated by default as identity primary key, owner_user_id bigint, shipment_id bigint);
create table public.agreement_posts (id bigint generated by default as identity primary key, client_user_id bigint);

create function public.current_app_user_id() returns bigint language sql stable security definer set search_path=public as $$ select id from public.users where auth_id = auth.uid() $$;
create function public.current_app_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.users where auth_id = auth.uid() $$;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role()='admin', false) $$;
create function public.is_dispatcher() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role()='dispatcher', false) $$;

create function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $h$
declare v_legacy text := coalesce(new.raw_user_meta_data->>'legacy_role', new.raw_user_meta_data->>'role','');
        v_role public.app_role;
begin
  v_role := case lower(v_legacy)
    when 'platform_admin' then 'admin'::public.app_role
    when 'transporter' then 'transporter'::public.app_role
    when 'dispatcher' then 'dispatcher'::public.app_role
    else 'customer'::public.app_role end;
  insert into public.users (auth_id,email,full_name,phone,cnic,role,legacy_role)
    values (new.id,new.email,'', '', coalesce(nullif(new.raw_user_meta_data->>'cnic',''),'PENDING-'||new.id::text), v_role, nullif(v_legacy,''))
    on conflict (email) do update set auth_id=excluded.auth_id;
  return new;
end $h$;
create trigger trg_on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();

do $p$ declare t text; begin
  foreach t in array array['users','service_seeker_profiles','everyday_user_profiles','drivers','vehicles','shipments','shipment_bids','shipment_trips','shipment_status_history','documents','agreement_posts'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy %I on public.%I for all using (public.is_admin()) with check (public.is_admin())','admin_all_'||t, t);
  end loop; end $p$;

create policy users_select_own on public.users for select using (auth_id = auth.uid() or public.is_dispatcher());
create policy users_update_own on public.users for update using (auth_id = auth.uid())
  with check (auth_id = auth.uid() and role = (select u.role from public.users u where u.auth_id = auth.uid()));
create policy service_seeker_profile_select_own on public.service_seeker_profiles for select using (user_id = public.current_app_user_id());
create policy everyday_user_profile_select_own on public.everyday_user_profiles for select using (user_id = public.current_app_user_id());
create policy drivers_dispatcher_all on public.drivers for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy drivers_owner_all on public.drivers for all using (owner_user_id = public.current_app_user_id()) with check (owner_user_id = public.current_app_user_id());
create policy vehicles_dispatcher_all on public.vehicles for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy vehicles_owner_all on public.vehicles for all using (owner_user_id = public.current_app_user_id()) with check (owner_user_id = public.current_app_user_id());
create policy shipments_dispatcher_all on public.shipments for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy shipments_client_own on public.shipments for all using (client_user_id = public.current_app_user_id()) with check (client_user_id = public.current_app_user_id());
create policy shipments_transporter_read on public.shipments for select using (public.current_app_role()='transporter' and (status='open' or id in (select order_id from public.shipment_trips where transporter_user_id = public.current_app_user_id())));
create policy bids_dispatcher_all on public.shipment_bids for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy bids_transporter_own on public.shipment_bids for all using (transporter_user_id = public.current_app_user_id()) with check (transporter_user_id = public.current_app_user_id());
create policy trips_dispatcher_all on public.shipment_trips for all using (public.is_dispatcher()) with check (public.is_dispatcher());
create policy trips_transporter_own on public.shipment_trips for all using (transporter_user_id = public.current_app_user_id()) with check (transporter_user_id = public.current_app_user_id());
create policy history_dispatcher_read on public.shipment_status_history for select using (public.is_dispatcher());
create policy documents_dispatcher_read on public.documents for select using (public.is_dispatcher());
create policy agr_posts_transporter_read on public.agreement_posts for select using (public.current_app_role()='transporter');
create policy "shipment_docs_admin_all" on storage.objects for all using (bucket_id='shipment-documents' and public.is_admin()) with check (bucket_id='shipment-documents' and public.is_admin());
create policy "shipment_docs_dispatcher_read" on storage.objects for select using (bucket_id='shipment-documents' and public.is_dispatcher());
"""

DISPATCHER_POLICY_FILTER = (
    "policyname ilike '%dispatcher%' "
    "or coalesce(qual,'') ilike '%is_dispatcher%' "
    "or coalesce(with_check,'') ilike '%is_dispatcher%'"
)

# The exact non-dispatcher policies whose survival proves each role keeps its
# previous access after the enum rebuild.
PRESERVED_POLICIES = {
    "admin_all_users",                     # admin: full access (req 7)
    "admin_all_shipments",
    "drivers_owner_all",                   # owner own-row (req 8)
    "vehicles_owner_all",
    "shipments_client_own",                # service seeker business access (req 10)
    "shipments_transporter_read",          # transporter order access (req 9)
    "bids_transporter_own",                # transporter bids (req 9)
    "trips_transporter_own",               # transporter trips (req 9)
    "agr_posts_transporter_read",          # transporter (req 9)
    "service_seeker_profile_select_own",   # business seeker (req 10)
    "everyday_user_profile_select_own",    # everyday user separated access (req 11)
    "users_update_own",
    "users_select_own",
    "shipment_docs_admin_all",
}


# ---------------------------------------------------------------------------
# Pure-calculation tests (no database) — the application layer.
# ---------------------------------------------------------------------------

def test_dispatcher_is_not_a_legacy_app_role_mapping():
    """req 1: dispatcher is not a valid app role — no legacy mapping to it."""
    from auth.helpers import LEGACY_TO_APP_ROLE
    assert "dispatcher" not in LEGACY_TO_APP_ROLE
    assert "dispatcher" not in set(LEGACY_TO_APP_ROLE.values())


def test_map_legacy_role_dispatcher_falls_back_to_customer():
    """req 1/3: an unknown 'dispatcher' role maps to customer, never admin."""
    from auth.helpers import map_legacy_role
    assert map_legacy_role("dispatcher") == "customer"
    assert map_legacy_role("DISPATCHER") == "customer"
    assert map_legacy_role("") == "customer"
    assert map_legacy_role("nonsense") == "customer"


def test_signup_rejects_dispatcher_role():
    """req 2: dispatcher signup/role selection is rejected by validation."""
    from auth.helpers import validate_signup_payload
    base = {
        "name": "X", "email": "x@example.com", "phone": "0300123456",
        "password": "password123", "cnic": "1234512345671", "city": "Lahore",
    }
    errors = validate_signup_payload({**base, "role": "dispatcher"})
    assert "role" in errors
    # A legitimate role has no role error, proving the rejection is specific.
    ok = validate_signup_payload({**base, "role": "service_seeker"})
    assert "role" not in ok


# ---------------------------------------------------------------------------
# Database-backed migration tests.
# ---------------------------------------------------------------------------

def _admin_url():
    url = os.environ.get("TEST_SUPABASE_DB_URL", "").strip()
    if not url:
        pytest.skip("TEST_SUPABASE_DB_URL not set")
    parts = urlsplit(url)
    return url, parts, urlunsplit((parts.scheme, parts.netloc, "/postgres", "", ""))


@pytest.fixture
def make_db():
    """Factory: build a fresh throwaway database from a SQL string and return a
    live connection to it. Every database created is dropped at teardown."""
    psycopg2 = pytest.importorskip("psycopg2")
    _, parts, admin_url = _admin_url()
    try:
        admin = psycopg2.connect(admin_url)
    except Exception as exc:  # pragma: no cover
        pytest.skip(f"cannot reach admin database: {exc}")
    admin.autocommit = True
    created = []
    conns = []

    def _factory(setup_sql):
        dbname = f"dtx_disp_{uuid.uuid4().hex[:12]}"
        try:
            with admin.cursor() as cur:
                cur.execute(f"CREATE DATABASE {dbname}")
        except Exception as exc:
            pytest.skip(f"CREATE DATABASE not permitted: {exc}")
        created.append(dbname)
        conn = psycopg2.connect(urlunsplit((parts.scheme, parts.netloc, "/" + dbname, "", "")))
        conns.append(conn)
        with conn.cursor() as cur:
            cur.execute(setup_sql)
        conn.commit()
        return conn

    try:
        yield _factory
    finally:
        for c in conns:
            try:
                c.close()
            except Exception:
                pass
        with admin.cursor() as cur:
            for dbname in created:
                cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
        admin.close()


def _migration_sql():
    return MIGRATION_SQL.read_text(encoding="utf-8")


def _scalar(cur, sql):
    cur.execute(sql)
    return cur.fetchone()[0]


def _enum_labels(cur):
    cur.execute("select enumlabel from pg_enum e join pg_type t on t.oid=e.enumtypid "
                "join pg_namespace n on n.oid=t.typnamespace "
                "where n.nspname='public' and t.typname='app_role' order by e.enumsortorder")
    return [r[0] for r in cur.fetchall()]


def _policy_rows(cur):
    cur.execute("select schemaname, tablename, policyname, cmd, coalesce(qual,''), "
                "coalesce(with_check,'') from pg_policies "
                "where schemaname in ('public','storage') order by 1,2,3")
    return set(cur.fetchall())


def test_migration_removes_all_dispatcher_artifacts(make_db):
    """req 4,5,6: after migration — no dispatcher enum value, no is_dispatcher()
    function, no dispatcher policy in public or storage, no temp enum left."""
    conn = make_db(PRELUDE)
    with conn.cursor() as cur:
        assert "dispatcher" in _enum_labels(cur)                       # precondition
        cur.execute(_migration_sql())
        conn.commit()

        assert _enum_labels(cur) == ["admin", "customer", "transporter",
                                     "fuel_station_manager", "shopkeeper"]
        assert "dispatcher" not in _enum_labels(cur)                   # req 4
        assert _scalar(cur, "select count(*) from pg_proc p join pg_namespace n "
                            "on n.oid=p.pronamespace where n.nspname='public' "
                            "and p.proname='is_dispatcher'") == 0       # req 5
        assert _scalar(cur, f"select count(*) from pg_policies where "
                            f"schemaname in ('public','storage') and "
                            f"({DISPATCHER_POLICY_FILTER})") == 0       # req 6
        assert _scalar(cur, "select count(*) from pg_type t join pg_namespace n "
                            "on n.oid=t.typnamespace where n.nspname='public' "
                            "and t.typname like 'app_role__%'") == 0    # no temp type


def test_non_dispatcher_policies_survive_enum_rebuild(make_db):
    """req 7-11,14: every non-dispatcher policy is byte-identical before/after;
    the only removals are the dispatcher policies + the users_select_own
    rewrite, and the only addition is the dispatcher-free users_select_own."""
    conn = make_db(PRELUDE)
    with conn.cursor() as cur:
        before = _policy_rows(cur)
        cur.execute(_migration_sql())
        conn.commit()
        after = _policy_rows(cur)

        removed = before - after
        added = after - before

        # Everything removed is a dispatcher artifact (either a dispatcher
        # policy, or the old users_select_own that referenced is_dispatcher()).
        for row in removed:
            _, _, name, _, qual, chk = row
            assert ("dispatcher" in name or "is_dispatcher" in qual
                    or "is_dispatcher" in chk), f"unexpected removal: {row}"
        # The only thing added back is the rewritten users_select_own.
        assert {(r[1], r[2]) for r in added} == {("users", "users_select_own")}

        # Every role's defining policy is still present.
        surviving = {r[2] for r in after}
        for name in PRESERVED_POLICIES:
            assert name in surviving, f"lost non-dispatcher policy: {name}"

        # And none of the surviving non-dispatcher policies changed definition.
        nondisp_before = {r for r in before
                          if "dispatcher" not in r[2]
                          and "is_dispatcher" not in r[4]
                          and "is_dispatcher" not in r[5]
                          and r[2] != "users_select_own"}
        assert nondisp_before <= after                                # req 14


def test_new_auth_user_trigger_cannot_create_dispatcher(make_db):
    """req 3: signup metadata asking for dispatcher yields role=customer."""
    conn = make_db(PRELUDE)
    with conn.cursor() as cur:
        cur.execute(_migration_sql())
        conn.commit()
        cur.execute("insert into auth.users (email, raw_user_meta_data) "
                    "values ('disp-signup@test', '{\"role\":\"dispatcher\"}'::jsonb)")
        conn.commit()
        cur.execute("select role::text from public.users where email='disp-signup@test'")
        assert cur.fetchone()[0] == "customer"


def test_migration_aborts_if_dispatcher_user_exists(make_db):
    """req 12: a dispatcher user makes the migration abort and change nothing."""
    import psycopg2
    conn = make_db(PRELUDE)
    with conn.cursor() as cur:
        cur.execute("insert into public.users (email, cnic, role, legacy_role) "
                    "values ('disp@test','1112223334445','dispatcher','dispatcher')")
        conn.commit()
        with pytest.raises(psycopg2.errors.RaiseException):
            cur.execute(_migration_sql())
        conn.rollback()
        # Nothing changed: dispatcher artifacts all still present.
        assert "dispatcher" in _enum_labels(cur)
        assert _scalar(cur, "select count(*) from pg_proc p join pg_namespace n "
                            "on n.oid=p.pronamespace where n.nspname='public' "
                            "and p.proname='is_dispatcher'") == 1
        assert _scalar(cur, "select count(*) from public.users where role::text='dispatcher'") == 1
        assert _scalar(cur, "select count(*) from pg_policies where policyname='drivers_dispatcher_all'") == 1


def test_migration_deletes_no_rows(make_db):
    """req 13: a normal zero-dispatcher migration deletes no user/business rows."""
    conn = make_db(PRELUDE)
    with conn.cursor() as cur:
        cur.execute("""
            insert into public.users (email,cnic,role,legacy_role) values
              ('admin@test','1000000000001','admin','platform_admin'),
              ('seeker@test','1000000000002','customer','service_seeker'),
              ('eve@test','1000000000003','customer','everyday_user'),
              ('carrier@test','1000000000004','transporter','transporter');
            insert into public.service_seeker_profiles (user_id, company_name)
              select id, 'BizCo' from public.users where email='seeker@test';
            insert into public.everyday_user_profiles (user_id)
              select id from public.users where email='eve@test';
            insert into public.shipments (client_user_id, status)
              select id, 'open' from public.users where email='seeker@test';
        """)
        conn.commit()
        before = {t: _scalar(cur, f"select count(*) from public.{t}") for t in
                  ("users", "service_seeker_profiles", "everyday_user_profiles", "shipments")}
        cur.execute(_migration_sql())
        conn.commit()
        after = {t: _scalar(cur, f"select count(*) from public.{t}") for t in before}
        assert after == before
        # The seeker/everyday split is intact and non-overlapping.
        assert _scalar(cur, "select count(*) from public.service_seeker_profiles s "
                            "join public.everyday_user_profiles e on e.user_id=s.user_id") == 0


def test_migration_is_idempotent(make_db):
    """req 15: re-applying the migration is a safe no-op."""
    conn = make_db(PRELUDE)
    with conn.cursor() as cur:
        cur.execute(_migration_sql())
        conn.commit()
        first = _policy_rows(cur)
        first_enum = _enum_labels(cur)
        cur.execute(_migration_sql())     # re-apply
        conn.commit()
        assert _policy_rows(cur) == first
        assert _enum_labels(cur) == first_enum
        assert "dispatcher" not in first_enum


# ---------------------------------------------------------------------------
# Full canonical schema (fresh deployment) — the real supabase/schema.sql.
# ---------------------------------------------------------------------------

def test_canonical_schema_is_dispatcher_free_and_migration_is_noop(make_db):
    """A fresh load of the real schema.sql already has no dispatcher, and the
    removal migration applied on top is a clean idempotent no-op across the
    complete policy set."""
    if not SCHEMA_SQL.exists():   # pragma: no cover
        pytest.skip("schema.sql not found")
    conn = make_db(STUBS + SCHEMA_SQL.read_text(encoding="utf-8"))
    with conn.cursor() as cur:
        assert "dispatcher" not in _enum_labels(cur)
        assert _scalar(cur, "select count(*) from pg_proc p join pg_namespace n "
                            "on n.oid=p.pronamespace where n.nspname='public' "
                            "and p.proname='is_dispatcher'") == 0
        assert _scalar(cur, f"select count(*) from pg_policies where "
                            f"schemaname in ('public','storage') and "
                            f"({DISPATCHER_POLICY_FILTER})") == 0
        before = _policy_rows(cur)
        cur.execute(_migration_sql())     # must be a clean no-op
        conn.commit()
        assert _policy_rows(cur) == before
        assert "dispatcher" not in _enum_labels(cur)
