"""Actual RLS privilege tests for the new client-profile tables.

Builds the profile tables + policies in a throwaway database and exercises them
as a NON-superuser role (RLS is bypassed by superusers/table owners, so a real
privilege test must switch to an unprivileged role). Proves:

  * an authenticated owner may SELECT only their own profile row;
  * an owner cannot read another user's profile;
  * an owner cannot INSERT / UPDATE / DELETE their profile via RLS (mutations
    are backend/service-role only);
  * an admin (is_admin() true) has full access;
  * dispatcher has NO special access (no dispatcher policy exists).

Skipped (not failed) when a throwaway database cannot be created or
TEST_SUPABASE_DB_URL is unset.
"""

import os
from urllib.parse import urlsplit, urlunsplit

import pytest

SETUP = """
create or replace function public.current_app_user_id() returns bigint language sql stable as $$
  select nullif(current_setting('app.uid', true), '')::bigint
$$;
create or replace function public.is_admin() returns boolean language sql stable as $$
  select coalesce(current_setting('app.is_admin', true) = '1', false)
$$;

create table public.users (id bigint primary key, email text, legacy_role text);
create table public.service_seeker_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    company_name text, total_shipments integer not null default 0
);
create table public.everyday_user_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    total_shipments integer not null default 0
);

insert into public.users values (1,'a@t','service_seeker'), (2,'b@t','service_seeker');
insert into public.service_seeker_profiles (user_id, company_name) values (1,'A Co'), (2,'B Co');

alter table public.service_seeker_profiles enable row level security;
alter table public.everyday_user_profiles enable row level security;

-- Final policy set (mirrors schema.sql): admin all; owner SELECT-own; NO
-- dispatcher policy and NO owner write policy.
create policy admin_all_service_seeker_profiles on public.service_seeker_profiles
    for all using (public.is_admin()) with check (public.is_admin());
create policy service_seeker_profile_select_own on public.service_seeker_profiles
    for select using (user_id = public.current_app_user_id());
create policy admin_all_everyday_user_profiles on public.everyday_user_profiles
    for all using (public.is_admin()) with check (public.is_admin());
create policy everyday_user_profile_select_own on public.everyday_user_profiles
    for select using (user_id = public.current_app_user_id());

create role app_user nologin;
grant usage on schema public to app_user;
grant select, insert, update, delete on public.service_seeker_profiles, public.everyday_user_profiles to app_user;
grant usage, select on all sequences in schema public to app_user;
grant select on public.users to app_user;
"""


@pytest.fixture
def rls_conn():
    psycopg2 = pytest.importorskip("psycopg2")
    url = os.environ.get("TEST_SUPABASE_DB_URL", "").strip()
    if not url:
        pytest.skip("TEST_SUPABASE_DB_URL not set")
    parts = urlsplit(url)
    admin_url = urlunsplit((parts.scheme, parts.netloc, "/postgres", "", ""))
    dbname = "dtx_rls_test"
    try:
        admin = psycopg2.connect(admin_url)
    except Exception as exc:  # pragma: no cover
        pytest.skip(f"cannot reach admin database: {exc}")
    admin.autocommit = True
    try:
        with admin.cursor() as cur:
            cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
            cur.execute(f"CREATE DATABASE {dbname}")
    except Exception as exc:
        admin.close()
        pytest.skip(f"CREATE DATABASE not permitted: {exc}")
    admin.close()
    conn = psycopg2.connect(urlunsplit((parts.scheme, parts.netloc, "/" + dbname, "", "")))
    try:
        with conn.cursor() as cur:
            cur.execute(SETUP)
        conn.commit()
        yield conn
    finally:
        conn.close()
        admin = psycopg2.connect(admin_url)
        admin.autocommit = True
        with admin.cursor() as cur:
            # Drop the role's grants with the database, and the role itself.
            cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
            try:
                cur.execute("DROP ROLE IF EXISTS app_user")
            except Exception:
                pass
        admin.close()


def _as_owner(cur, uid):
    cur.execute("RESET ROLE")
    cur.execute("SELECT set_config('app.is_admin','0',false)")
    cur.execute("SELECT set_config('app.uid',%s,false)", (str(uid),))
    cur.execute("SET ROLE app_user")


def test_owner_reads_only_own_profile(rls_conn):
    import psycopg2
    with rls_conn.cursor() as cur:
        _as_owner(cur, 1)
        cur.execute("SELECT user_id FROM service_seeker_profiles")
        rows = [r[0] for r in cur.fetchall()]
        assert rows == [1]
        _as_owner(cur, 2)
        cur.execute("SELECT user_id FROM service_seeker_profiles")
        assert [r[0] for r in cur.fetchall()] == [2]
        cur.execute("RESET ROLE")


def test_owner_cannot_insert_update_delete(rls_conn):
    import psycopg2
    with rls_conn.cursor() as cur:
        _as_owner(cur, 1)
        # INSERT for self is blocked (no permissive INSERT policy).
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            cur.execute("INSERT INTO everyday_user_profiles (user_id) VALUES (1)")
        rls_conn.rollback()
        _as_owner(cur, 1)
        # UPDATE / DELETE affect zero rows (USING is false for non-admin writes).
        cur.execute("UPDATE service_seeker_profiles SET total_shipments = 999 WHERE user_id = 1")
        assert cur.rowcount == 0
        cur.execute("DELETE FROM service_seeker_profiles WHERE user_id = 1")
        assert cur.rowcount == 0
        cur.execute("RESET ROLE")
    # The backend service role (superuser here) still sees the untouched row.
    with rls_conn.cursor() as cur:
        cur.execute("SELECT total_shipments FROM service_seeker_profiles WHERE user_id = 1")
        assert cur.fetchone()[0] == 0


def test_admin_has_full_access(rls_conn):
    with rls_conn.cursor() as cur:
        cur.execute("RESET ROLE")
        cur.execute("SELECT set_config('app.is_admin','1',false)")
        cur.execute("SELECT set_config('app.uid','',false)")
        cur.execute("SET ROLE app_user")
        cur.execute("SELECT count(*) FROM service_seeker_profiles")
        assert cur.fetchone()[0] == 2                      # admin sees all
        cur.execute("UPDATE service_seeker_profiles SET total_shipments = 5 WHERE user_id = 2")
        assert cur.rowcount == 1                            # admin may write
        cur.execute("RESET ROLE")
    rls_conn.rollback()


def test_no_dispatcher_policy_exists(rls_conn):
    with rls_conn.cursor() as cur:
        cur.execute(
            "SELECT policyname FROM pg_policies WHERE tablename IN "
            "('service_seeker_profiles','everyday_user_profiles') AND policyname LIKE '%dispatcher%'"
        )
        assert cur.fetchall() == []
