"""Forward-migration test for the everyday-user separation.

Builds a minimal PRE-migration fixture (users + old customers + shipments with
area columns) in a throwaway database, applies the real migration file, and
asserts the final state: customers gone, area columns gone, profiles split by
customer_type/legacy_role, nobody in both tables, RLS own-row policies present.

Requires a server the test user can CREATE DATABASE on. Skipped (not failed)
when that is not permitted (e.g. a locked-down managed test database) or when
TEST_SUPABASE_DB_URL is unset.
"""

import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import pytest

_MIG_DIR = Path(__file__).resolve().parent.parent.parent / "supabase" / "migrations"
MIGRATION = _MIG_DIR / "20260723090000_everyday_user_separation.sql"
HARDENING = _MIG_DIR / "20260723100000_everyday_profile_hardening.sql"

PRELUDE = """
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end; $$;
create or replace function public.is_admin() returns boolean language sql as $$ select false $$;
create or replace function public.is_dispatcher() returns boolean language sql as $$ select false $$;
create or replace function public.current_app_user_id() returns bigint language sql as $$ select null::bigint $$;

create table public.users (
    id bigint generated by default as identity primary key,
    email text not null unique, legacy_role text
);
create table public.customers (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    customer_type text, company_name text, business_type text, transport_need text,
    default_pickup_city text, default_pickup_area text, billing_address text,
    total_shipments integer not null default 0,
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.shipments (
    id bigint generated by default as identity primary key,
    client_user_id bigint not null references public.users(id) on delete cascade,
    pickup_city text, pickup_area text not null default '',
    dropoff_city text, dropoff_area text not null default '',
    status text not null default 'open',
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.users (email, legacy_role) values
  ('biz@test','service_seeker'), ('eve@test','everyday_user'),
  ('cli@test','client'), ('amb@test', null);
insert into public.customers (user_id, customer_type, company_name, default_pickup_area) values
  (1,'business','BizCo','Area A'), (2,'individual',null,'Area B'),
  (3,'business','CliCo',null), (4,'individual',null,null);
insert into public.shipments (client_user_id, pickup_city, pickup_area, dropoff_city, dropoff_area) values
  (1,'Lahore','AreaX','Karachi','AreaY'), (2,'Multan','AreaZ','Sialkot','AreaW');
"""


@pytest.fixture
def throwaway_db():
    psycopg2 = pytest.importorskip("psycopg2")
    url = os.environ.get("TEST_SUPABASE_DB_URL", "").strip()
    if not url:
        pytest.skip("TEST_SUPABASE_DB_URL not set")
    parts = urlsplit(url)
    admin_url = urlunsplit((parts.scheme, parts.netloc, "/postgres", "", ""))
    dbname = "dtx_migtest_ev"
    try:
        admin = psycopg2.connect(admin_url)
    except Exception as exc:  # pragma: no cover
        pytest.skip(f"cannot reach admin database: {exc}")
    admin.autocommit = True
    try:
        with admin.cursor() as cur:
            cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
            cur.execute(f"CREATE DATABASE {dbname}")
    except Exception as exc:
        admin.close()
        pytest.skip(f"CREATE DATABASE not permitted: {exc}")
    admin.close()
    child_url = urlunsplit((parts.scheme, parts.netloc, "/" + dbname, "", ""))
    conn = psycopg2.connect(child_url)
    try:
        yield conn
    finally:
        conn.close()
        admin = psycopg2.connect(admin_url)
        admin.autocommit = True
        with admin.cursor() as cur:
            cur.execute(f"DROP DATABASE IF EXISTS {dbname}")
        admin.close()


def _scalar(cur, sql):
    cur.execute(sql)
    return cur.fetchone()[0]


def _profile_policies(cur):
    cur.execute("select policyname from pg_policies where tablename in "
                "('service_seeker_profiles','everyday_user_profiles')")
    return {r[0] for r in cur.fetchall()}


def test_both_migrations_sequentially(throwaway_db):
    """A fresh pre-migration database run through BOTH migrations in order."""
    conn = throwaway_db
    with conn.cursor() as cur:
        cur.execute(PRELUDE)
        conn.commit()
        cur.execute(MIGRATION.read_text(encoding="utf-8"))
        conn.commit()
        cur.execute(HARDENING.read_text(encoding="utf-8"))
        conn.commit()

        # customers gone, area columns gone.
        assert not _scalar(cur, "select exists(select 1 from information_schema.tables "
                                "where table_schema='public' and table_name='customers')")
        assert not _scalar(cur, "select exists(select 1 from information_schema.columns "
                                "where table_name='shipments' and column_name='pickup_area')")
        assert not _scalar(cur, "select exists(select 1 from information_schema.columns "
                                "where table_name='shipments' and column_name='dropoff_area')")
        # migrated to the right tables (business: 1,3 ; everyday: 2,4).
        assert _scalar(cur, "select array_agg(user_id order by user_id) from public.service_seeker_profiles") == [1, 3]
        assert _scalar(cur, "select array_agg(user_id order by user_id) from public.everyday_user_profiles") == [2, 4]
        assert _scalar(cur, "select count(*) from public.service_seeker_profiles s "
                            "join public.everyday_user_profiles e on e.user_id=s.user_id") == 0
        assert _scalar(cur, "select array_agg(seeker_kind_snapshot order by id) from public.shipments") == ["business", "everyday"]
        assert _scalar(cur, "select is_nullable from information_schema.columns where "
                            "table_name='shipments' and column_name='seeker_kind_snapshot'") == "NO"
        # Final RLS: SELECT-own only, NO dispatcher, NO FOR ALL owner policy.
        pols = _profile_policies(cur)
        assert "service_seeker_profile_select_own" in pols
        assert "everyday_user_profile_select_own" in pols
        assert not any("dispatcher" in p for p in pols)
        assert "service_seeker_profile_own" not in pols
        assert "everyday_user_profile_own" not in pols
        # Hardened trigger active: a service_seeker cannot get an everyday row.
        cur.execute("insert into public.users values (99,'x@t','service_seeker')")
        with pytest.raises(psycopg2_error()):
            cur.execute("insert into public.everyday_user_profiles (user_id) values (99)")
        conn.rollback()


def test_hardening_alone_on_090000_state(throwaway_db):
    """The hardening migration applied ALONE to a database already at the
    20260723090000 state (dispatcher policies + FOR ALL owner policies present),
    and re-applied to prove idempotency."""
    conn = throwaway_db
    with conn.cursor() as cur:
        cur.execute(PRELUDE)
        conn.commit()
        cur.execute(MIGRATION.read_text(encoding="utf-8"))
        conn.commit()

        # State after the FIRST migration: dispatcher + FOR ALL owner policies.
        pols = _profile_policies(cur)
        assert "service_seeker_profile_dispatcher_read" in pols
        assert "everyday_user_profile_dispatcher_read" in pols
        assert "service_seeker_profile_own" in pols

        # Apply ONLY the hardening migration.
        hardening_sql = HARDENING.read_text(encoding="utf-8")
        cur.execute(hardening_sql)
        conn.commit()

        pols = _profile_policies(cur)
        assert not any("dispatcher" in p for p in pols)
        assert "service_seeker_profile_own" not in pols
        assert "everyday_user_profile_own" not in pols
        assert "service_seeker_profile_select_own" in pols
        assert "everyday_user_profile_select_own" in pols

        # Idempotent: re-applying the hardening migration succeeds unchanged.
        cur.execute(hardening_sql)
        conn.commit()
        assert _profile_policies(cur) == pols


def psycopg2_error():
    import psycopg2
    return psycopg2.errors.RaiseException
