-- ============================================================================
-- Migration: separate business (service seeker) and everyday client profiles
-- Date: 2026-07-23
-- ============================================================================
-- 1. Add shipments.seeker_kind_snapshot (backfill from the owning user, then
--    constrain NOT NULL + CHECK).
-- 2. Create service_seeker_profiles + everyday_user_profiles (RLS, indexes,
--    updated_at triggers, and a mutual-exclusivity guard so no user can hold
--    both client-profile types).
-- 3. Migrate every public.customers row into exactly one of the new tables,
--    using customer_type AND users.legacy_role as discriminators.
-- 4. Verify the migration (every customer migrated, nobody in both tables),
--    then drop the old customers policies + table.
-- 5. Drop the obsolete shipments.pickup_area / dropoff_area columns
--    (customers.default_pickup_area disappears with the table; it is NOT copied
--    into either new profile table).
--
-- The transaction engine (shipments, bids, trips, payments, matching, checkout)
-- is unchanged and shared by both kinds. Idempotent guards throughout.
-- Apply with the Supabase CLI (`supabase db push`) or the SQL editor.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. shipments.seeker_kind_snapshot
-- ---------------------------------------------------------------------------
alter table public.shipments add column if not exists seeker_kind_snapshot text;

-- Backfill from the posting user's role (legacy_role first, then any existing
-- customers.customer_type); unknown/ambiguous historical clients default to
-- 'business' (the original main client kind).
update public.shipments s
set seeker_kind_snapshot = case
        when lower(coalesce(u.legacy_role, '')) = 'everyday_user' then 'everyday'
        when lower(coalesce(u.legacy_role, '')) in ('service_seeker', 'client') then 'business'
        when c.customer_type = 'individual' then 'everyday'
        else 'business'
    end
from public.users u
left join public.customers c on c.user_id = u.id
where s.client_user_id = u.id
  and s.seeker_kind_snapshot is null;

-- Any shipment still unmatched (no owning user row) defaults to business.
update public.shipments set seeker_kind_snapshot = 'business'
where seeker_kind_snapshot is null;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'shipments_seeker_kind_snapshot_check'
    ) then
        alter table public.shipments
            add constraint shipments_seeker_kind_snapshot_check
            check (seeker_kind_snapshot in ('everyday', 'business'));
    end if;
end $$;

alter table public.shipments alter column seeker_kind_snapshot set not null;

-- ---------------------------------------------------------------------------
-- 2. New client-profile tables
-- ---------------------------------------------------------------------------
create table if not exists public.service_seeker_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    company_name    text,
    business_type   text,
    transport_need  text,
    default_pickup_city text,
    billing_address text,
    total_shipments integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table if not exists public.everyday_user_profiles (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null unique references public.users (id) on delete cascade,
    total_shipments integer not null default 0,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- Mutual-exclusivity: reject an insert/update into one table when the other
-- already has a row for that user (protects against an admin role change or a
-- re-signup leaving both rows behind).
create or replace function public.enforce_single_client_profile()
returns trigger language plpgsql as $$
declare
    other_table text := case tg_table_name
        when 'service_seeker_profiles' then 'everyday_user_profiles'
        else 'service_seeker_profiles' end;
    conflict boolean;
begin
    execute format('select exists(select 1 from public.%I where user_id = $1)', other_table)
        into conflict using new.user_id;
    if conflict then
        raise exception 'user % already has a % row; a user cannot hold both client-profile types',
            new.user_id, other_table;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_service_seeker_single_profile on public.service_seeker_profiles;
create trigger trg_service_seeker_single_profile
    before insert or update of user_id on public.service_seeker_profiles
    for each row execute function public.enforce_single_client_profile();
drop trigger if exists trg_everyday_single_profile on public.everyday_user_profiles;
create trigger trg_everyday_single_profile
    before insert or update of user_id on public.everyday_user_profiles
    for each row execute function public.enforce_single_client_profile();

-- updated_at maintenance (reuse the existing shared function).
drop trigger if exists trg_service_seeker_profiles_updated_at on public.service_seeker_profiles;
create trigger trg_service_seeker_profiles_updated_at
    before update on public.service_seeker_profiles
    for each row execute function public.set_updated_at();
drop trigger if exists trg_everyday_user_profiles_updated_at on public.everyday_user_profiles;
create trigger trg_everyday_user_profiles_updated_at
    before update on public.everyday_user_profiles
    for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. Migrate customers rows (only if the old table still exists)
-- ---------------------------------------------------------------------------
do $$
begin
    if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'customers'
    ) then
        -- Everyday first: explicit everyday_user legacy role, or an individual
        -- customer_type that is not a business legacy role.
        insert into public.everyday_user_profiles (user_id, total_shipments, created_at, updated_at)
        select c.user_id, coalesce(c.total_shipments, 0), c.created_at, c.updated_at
        from public.customers c
        join public.users u on u.id = c.user_id
        where lower(coalesce(u.legacy_role, '')) = 'everyday_user'
           or (lower(coalesce(u.legacy_role, '')) not in ('service_seeker', 'client')
               and coalesce(c.customer_type, '') = 'individual')
        on conflict (user_id) do nothing;

        -- Business gets every remaining customers row (catch-all).
        insert into public.service_seeker_profiles
            (user_id, company_name, business_type, transport_need,
             default_pickup_city, billing_address, total_shipments, created_at, updated_at)
        select c.user_id, c.company_name, c.business_type, c.transport_need,
               c.default_pickup_city, c.billing_address, coalesce(c.total_shipments, 0),
               c.created_at, c.updated_at
        from public.customers c
        where not exists (
            select 1 from public.everyday_user_profiles e where e.user_id = c.user_id
        )
        on conflict (user_id) do nothing;
    end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4. Verify BEFORE dropping customers
-- ---------------------------------------------------------------------------
do $$
begin
    if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'customers'
    ) then
        -- Every customers row must now exist in exactly one new table.
        if exists (
            select 1 from public.customers c
            where not exists (select 1 from public.service_seeker_profiles s where s.user_id = c.user_id)
              and not exists (select 1 from public.everyday_user_profiles e where e.user_id = c.user_id)
        ) then
            raise exception 'migration incomplete: some customers rows were not migrated';
        end if;
    end if;
    -- No user may end up in both tables.
    if exists (
        select 1 from public.service_seeker_profiles s
        join public.everyday_user_profiles e on e.user_id = s.user_id
    ) then
        raise exception 'invariant violated: a user has both client-profile types';
    end if;
end $$;

-- ---------------------------------------------------------------------------
-- 5. Enable RLS + policies on the new tables (own row only; dispatcher read;
--    admin all) — mirrors the customers policies that are being removed.
-- ---------------------------------------------------------------------------
alter table public.service_seeker_profiles enable row level security;
alter table public.everyday_user_profiles enable row level security;

drop policy if exists admin_all_service_seeker_profiles on public.service_seeker_profiles;
create policy admin_all_service_seeker_profiles on public.service_seeker_profiles
    for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists service_seeker_profile_own on public.service_seeker_profiles;
create policy service_seeker_profile_own on public.service_seeker_profiles
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
drop policy if exists service_seeker_profile_dispatcher_read on public.service_seeker_profiles;
create policy service_seeker_profile_dispatcher_read on public.service_seeker_profiles
    for select using (public.is_dispatcher());

drop policy if exists admin_all_everyday_user_profiles on public.everyday_user_profiles;
create policy admin_all_everyday_user_profiles on public.everyday_user_profiles
    for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists everyday_user_profile_own on public.everyday_user_profiles;
create policy everyday_user_profile_own on public.everyday_user_profiles
    for all using (user_id = public.current_app_user_id())
    with check (user_id = public.current_app_user_id());
drop policy if exists everyday_user_profile_dispatcher_read on public.everyday_user_profiles;
create policy everyday_user_profile_dispatcher_read on public.everyday_user_profiles
    for select using (public.is_dispatcher());

-- ---------------------------------------------------------------------------
-- 6. Drop old customers table (policies first) and the obsolete area columns
-- ---------------------------------------------------------------------------
drop policy if exists admin_all_customers on public.customers;
drop policy if exists customers_own on public.customers;
drop policy if exists customers_dispatcher_read on public.customers;
drop table if exists public.customers;   -- takes default_pickup_area with it

alter table public.shipments drop column if exists pickup_area;
alter table public.shipments drop column if exists dropoff_area;
