-- ============================================================================
-- Migration: one-time order trip-completion lifecycle
-- Date: 2026-07-23
-- ============================================================================
-- Adds the schema needed for the canonical one-time delivery lifecycle:
--   ready_to_start -> in_progress -> awaiting_client_confirmation
--     -> completed | delivery_disputed | admin_review -> resolved_client
--
-- Payments keep their existing status vocabulary (held -> released | refunded;
-- the money stays "held" throughout a dispute / admin review). No existing
-- shipment / bid / trip / payment / wallet row is dropped or rewritten; only
-- forward-compatible columns, one dispute table, one chat linkage and a set of
-- uniqueness backstops are added.
--
-- Forward-only. Idempotent (add-if-not-exists / create-if-not-exists). Runs in
-- one transaction; any RAISE aborts and rolls everything back. Historical
-- migrations are NOT edited. schema.sql mirrors this final state.
-- ============================================================================

-- ---- 1. shipment_trips: delivery-completion + 6-hour confirmation window ----
alter table public.shipment_trips
    add column if not exists delivery_completion_requested_at timestamptz;
alter table public.shipment_trips
    add column if not exists confirmation_deadline_at timestamptz;

-- ---- 2. payments: dummy-refund audit reference -----------------------------
alter table public.payments
    add column if not exists refund_provider_reference text;

-- ---- 3. chat_threads: one-time order linkage (one thread per accepted trip)-
alter table public.chat_threads
    add column if not exists shipment_id bigint references public.shipments (id) on delete cascade;
alter table public.chat_threads
    add column if not exists one_time_trip_id bigint references public.shipment_trips (id) on delete cascade;

-- Exactly one chat thread per accepted one-time shipment. Agreement threads
-- (shipment_id null) are untouched by this partial index.
create unique index if not exists uniq_chat_thread_one_time
    on public.chat_threads (shipment_id)
    where shipment_id is not null;

-- ---- 4. one-time delivery dispute case -------------------------------------
create table if not exists public.shipment_disputes (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    payment_id      bigint references public.payments (id) on delete set null,
    client_user_id  bigint not null references public.users (id),
    transporter_user_id bigint not null references public.users (id),
    chat_thread_id  bigint references public.chat_threads (id) on delete set null,
    trigger         text not null
                    check (trigger in ('client_no', 'confirmation_timeout')),
    status          text not null default 'open'
                    check (status in ('open', 'resolved_transporter', 'resolved_client')),
    client_reason        text,
    transporter_statement text,
    admin_user_id   bigint references public.users (id),
    admin_notes     text,
    resolution      text
                    check (resolution is null or resolution in ('transporter_win', 'client_win')),
    resolved_at     timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- At most ONE open dispute per trip (DB-level guarantee for Phase H).
create unique index if not exists uniq_open_dispute_per_trip
    on public.shipment_disputes (trip_id)
    where status = 'open';
-- Fast admin queue + per-shipment lookups.
create index if not exists idx_disputes_status on public.shipment_disputes (status, created_at);
create index if not exists idx_disputes_shipment on public.shipment_disputes (shipment_id);

-- ---- 5. notification idempotency backstop ----------------------------------
-- One lifecycle notification per (trip, recipient, event type). Repeated
-- transitions / deadline sweeps can never fan out duplicate rows.
create unique index if not exists uniq_notification_event
    on public.shipment_notifications (trip_id, user_id, notification_type)
    where trip_id is not null;

-- ---- 6. payout / refund uniqueness backstops (no double credit) ------------
-- Transporter payout and business-wallet refund each write exactly one wallet
-- transaction per trip; the unique reference makes a second credit impossible.
create unique index if not exists uniq_wallet_lifecycle_txn
    on public.wallet_transactions (type, reference_id)
    where reference_id is not null and type in ('order_payout', 'order_refund');

-- ---- 7. keep the updated_at trigger on the new dispute table ----------------
do $trg$
begin
    if not exists (
        select 1 from pg_trigger where tgname = 'trg_shipment_disputes_updated_at'
    ) then
        execute 'create trigger trg_shipment_disputes_updated_at
                 before update on public.shipment_disputes
                 for each row execute function public.set_updated_at()';
    end if;
end
$trg$;

-- ---- 8. RLS on the dispute table (admin-all; parties read own) --------------
alter table public.shipment_disputes enable row level security;
do $rls$
begin
    if not exists (select 1 from pg_policies where tablename = 'shipment_disputes'
                   and policyname = 'admin_all_shipment_disputes') then
        execute 'create policy admin_all_shipment_disputes on public.shipment_disputes
                 for all using (public.is_admin()) with check (public.is_admin())';
    end if;
    if not exists (select 1 from pg_policies where tablename = 'shipment_disputes'
                   and policyname = 'disputes_parties_read') then
        execute 'create policy disputes_parties_read on public.shipment_disputes
                 for select using (client_user_id = public.current_app_user_id()
                                   or transporter_user_id = public.current_app_user_id())';
    end if;
end
$rls$;

-- ---- 9. backfill legacy in-flight trips/shipments to the canonical names ----
-- Known legacy statuses are remapped; unknown *active* statuses abort rather
-- than being silently guessed. Terminal / pre-flight statuses are left as-is.
do $backfill$
declare
    v_bad integer;
    v_now timestamptz := now();
begin
    -- Any held payment whose trip is in a status the new machine cannot place
    -- is irreconcilable — abort instead of guessing.
    select count(*) into v_bad
    from public.payments p
    join public.shipment_trips t on t.id = p.trip_id
    where p.status = 'held'
      and t.status not in (
          'ready_to_start', 'in_progress', 'awaiting_client_confirmation',
          'completed', 'delivery_disputed', 'admin_review', 'resolved_client',
          'delivery_claimed', 'first_response_pending', 'dispute_pending', 'accepted'
      );
    if v_bad > 0 then
        raise exception 'Aborting: % held payment(s) reference an unmappable trip status', v_bad;
    end if;

    -- Legacy trip -> canonical trip status. A legacy "delivery_claimed" trip is
    -- only a transporter claim awaiting the client, NOT a completed trip: reuse
    -- its old trip_completed_at as the completion-REQUEST time and the 6-hour
    -- window anchor, then clear trip_completed_at (only a genuine client Yes /
    -- admin transporter-win sets it under the new semantics).
    update public.shipment_trips
       set status = 'awaiting_client_confirmation',
           delivery_completion_requested_at = coalesce(delivery_completion_requested_at, trip_completed_at, v_now),
           confirmation_deadline_at = coalesce(confirmation_deadline_at,
                                               coalesce(trip_completed_at, v_now) + interval '6 hours'),
           trip_completed_at = null,
           updated_at = v_now
     where status in ('delivery_claimed', 'first_response_pending');

    -- Legacy dispute -> admin_review: not a completed trip either.
    update public.shipment_trips
       set status = 'admin_review', trip_completed_at = null, updated_at = v_now
     where status = 'dispute_pending';

    -- Mirror onto shipments that have such a trip (only when the shipment is
    -- still in a pre-terminal state, so completed/cancelled orders are safe).
    update public.shipments s
       set status = t.status, updated_at = v_now
      from public.shipment_trips t
     where t.order_id = s.id
       and t.status in ('awaiting_client_confirmation', 'admin_review')
       and s.status in ('in_progress', 'ready_to_start', 'delivery_claimed',
                        'first_response_pending', 'dispute_pending');
end
$backfill$;

-- ============================================================================
-- 10. Legacy shipment_trip_verification cleanup (guarded; row-safe)
-- ============================================================================
-- The one-time lifecycle/dispute system replaced the old two-response
-- verification record; a full source scan found ZERO runtime references to
-- public.shipment_trip_verification. Drop it ONLY when empty; abort (never
-- delete history) if it still holds rows. Idempotent (no-op once gone).
do $verif$
declare
    v_rows integer;
begin
    if to_regclass('public.shipment_trip_verification') is null then
        return;                                   -- already dropped (reapply)
    end if;
    execute 'select count(*) from public.shipment_trip_verification' into v_rows;
    if v_rows > 0 then
        raise exception
            'Aborting: shipment_trip_verification still has % row(s). Refusing to '
            'drop legacy verification history - resolve/migrate those rows first.', v_rows;
    end if;
    -- CASCADE removes its index (idx_trip_verification_trip), its RLS policy
    -- (admin_all_shipment_trip_verification) and its updated_at trigger.
    execute 'drop table public.shipment_trip_verification cascade';
end
$verif$;

-- ============================================================================
-- 11. Anomaly precheck: fail loudly (precise diagnostic) if ANY existing row
--     already violates the integrity/arithmetic invariants, BEFORE adding the
--     constraints. Never rounds or "repairs" financial history.
-- ============================================================================
do $precheck$
declare
    v integer;
    msg text := '';
begin
    -- one-time payment arithmetic. PostgreSQL numeric accepts 'NaN', and NaN
    -- compares greater than ordinary numbers, so finite checks must be explicit.
    -- Lifecycle rows are the one-time checkout/payment states tied to both a
    -- shipment and trip; legacy immediate-payout 'paid' rows stay exempt.
    select count(*) into v from public.payments
      where bid_price < 0 or bid_price = 'NaN'::numeric
         or company_fee < 0 or company_fee = 'NaN'::numeric
         or transporter_amount < 0 or transporter_amount = 'NaN'::numeric
         or wallet_funded_amount < 0 or wallet_funded_amount = 'NaN'::numeric
         or card_funded_amount < 0 or card_funded_amount = 'NaN'::numeric
         or processing_fee_amount < 0 or processing_fee_amount = 'NaN'::numeric
         or (total_card_charge is not null
             and (total_card_charge < 0 or total_card_charge = 'NaN'::numeric));
    if v > 0 then msg := msg || format('[invalid_monetary_amounts=%s] ', v); end if;

    select count(*) into v from public.payments
      where shipment_id is not null and trip_id is not null
        and status in ('processing', 'held', 'released', 'refunded', 'disputed')
        and funding_source is null;
    if v > 0 then msg := msg || format('[lifecycle_funding_source_null=%s] ', v); end if;

    select count(*) into v from public.payments
      where shipment_id is not null and trip_id is not null
        and status in ('processing', 'held', 'released', 'refunded', 'disputed')
        and (wallet_funded_amount + card_funded_amount) <> bid_price;
    if v > 0 then msg := msg || format('[funding_split<>bid=%s] ', v); end if;

    select count(*) into v from public.payments
      where shipment_id is not null and trip_id is not null
        and status in ('processing', 'held', 'released', 'refunded', 'disputed')
        and (company_fee + transporter_amount) <> bid_price;
    if v > 0 then msg := msg || format('[commission_split<>bid=%s] ', v); end if;

    select count(*) into v from public.payments
      where total_card_charge is not null
        and total_card_charge <> (card_funded_amount + processing_fee_amount);
    if v > 0 then msg := msg || format('[total_card_charge<>card+fee=%s] ', v); end if;

    select count(*) into v from public.payments
      where processing_fee_percent is not null
        and (processing_fee_percent < 0 or processing_fee_percent >= 100);
    if v > 0 then msg := msg || format('[processing_percent_out_of_range=%s] ', v); end if;

    select count(*) into v from public.payments
      where company_share_percent is not null and transporter_share_percent is not null
        and (company_share_percent + transporter_share_percent) <> 100;
    if v > 0 then msg := msg || format('[payment_snapshot_sum<>100=%s] ', v); end if;

    select count(*) into v from public.shipments
      where company_share_percent_snapshot is not null
        and transporter_share_percent_snapshot is not null
        and (company_share_percent_snapshot + transporter_share_percent_snapshot) <> 100;
    if v > 0 then msg := msg || format('[shipment_snapshot_sum<>100=%s] ', v); end if;

    -- relationship integrity
    select count(*) into v from public.shipments s
      join public.shipment_bids b on b.id = s.accepted_bid_id
      where s.accepted_bid_id is not null and b.order_id <> s.id;
    if v > 0 then msg := msg || format('[accepted_bid_wrong_order=%s] ', v); end if;

    select count(*) into v from public.shipment_trips t
      join public.shipment_bids b on b.id = t.accepted_bid_id
      where b.order_id <> t.order_id
         or b.transporter_user_id <> t.transporter_user_id
         or b.truck_id <> t.truck_id;
    if v > 0 then msg := msg || format('[trip_bid_mismatch=%s] ', v); end if;

    select count(*) into v from public.payments p
      join public.shipment_trips t on t.id = p.trip_id
      where p.transporter_user_id <> t.transporter_user_id
         or (p.shipment_id is not null and p.shipment_id <> t.order_id);
    if v > 0 then msg := msg || format('[payment_trip_mismatch=%s] ', v); end if;

    select count(*) into v from public.payments p
      join public.shipments s on s.id = p.shipment_id
      where p.shipment_id is not null and p.client_user_id <> s.client_user_id;
    if v > 0 then msg := msg || format('[payment_client_mismatch=%s] ', v); end if;

    select count(*) into v from public.chat_threads c
      join public.shipment_trips t on t.id = c.one_time_trip_id
      where c.one_time_trip_id is not null and c.shipment_id is not null
        and t.order_id <> c.shipment_id;
    if v > 0 then msg := msg || format('[chat_trip_wrong_shipment=%s] ', v); end if;

    select count(*) into v from public.shipment_disputes d
      join public.chat_threads c on c.id = d.chat_thread_id
      where d.chat_thread_id is not null
        and (c.shipment_id <> d.shipment_id
             or c.one_time_trip_id is distinct from d.trip_id);
    if v > 0 then msg := msg || format('[dispute_chat_wrong_trip=%s] ', v); end if;

    if length(msg) > 0 then
        raise exception 'Integrity precheck failed - existing rows violate: %', msg;
    end if;
end
$precheck$;

-- Remove the intermediate same-shipment-only dispute/chat FK and its anchor.
-- The exact-trip FK below covers (chat_thread_id, shipment_id, trip_id), so it
-- also proves the same shipment. No CASCADE: an unexpected dependency should
-- fail this migration instead of silently removing another object.
alter table public.shipment_disputes
    drop constraint if exists fk_disputes_chat_shipment;
drop index if exists public.uq_chat_threads_id_shipment;

-- ============================================================================
-- 12. Supporting UNIQUE INDEXES (composite-FK targets). id is the PK, so each
--     is trivially unique; a FK may reference a unique index directly.
-- ============================================================================
create unique index if not exists uq_bids_order_id
    on public.shipment_bids (order_id, id);
create unique index if not exists uq_bids_id_order_transp_truck
    on public.shipment_bids (id, order_id, transporter_user_id, truck_id);
create unique index if not exists uq_trips_id_order
    on public.shipment_trips (id, order_id);
create unique index if not exists uq_trips_id_transporter
    on public.shipment_trips (id, transporter_user_id);
create unique index if not exists uq_shipments_id_client
    on public.shipments (id, client_user_id);
create unique index if not exists uq_payments_id_trip
    on public.payments (id, trip_id);
create unique index if not exists uq_chat_threads_id_shipment_trip
    on public.chat_threads (id, shipment_id, one_time_trip_id);

-- ============================================================================
-- 13. Composite relationship FKs + arithmetic CHECK constraints. ADD CONSTRAINT
--     has no IF NOT EXISTS, so each is guarded on pg_constraint for idempotency.
--     Nullable referencing columns use MATCH SIMPLE (skipped when null), so
--     legacy NULL paths stay valid. All protect INSERT and UPDATE.
-- ============================================================================
do $integrity$
declare
    c record;
begin
    for c in
        select * from (values
            ('fk_shipments_accepted_bid_same_order',
             'alter table public.shipments add constraint fk_shipments_accepted_bid_same_order foreign key (id, accepted_bid_id) references public.shipment_bids (order_id, id)'),
            ('fk_trips_bid_matches',
             'alter table public.shipment_trips add constraint fk_trips_bid_matches foreign key (accepted_bid_id, order_id, transporter_user_id, truck_id) references public.shipment_bids (id, order_id, transporter_user_id, truck_id)'),
            ('fk_payments_trip_transporter',
             'alter table public.payments add constraint fk_payments_trip_transporter foreign key (trip_id, transporter_user_id) references public.shipment_trips (id, transporter_user_id)'),
            ('fk_payments_trip_shipment',
             'alter table public.payments add constraint fk_payments_trip_shipment foreign key (trip_id, shipment_id) references public.shipment_trips (id, order_id)'),
            ('fk_payments_shipment_client',
             'alter table public.payments add constraint fk_payments_shipment_client foreign key (shipment_id, client_user_id) references public.shipments (id, client_user_id)'),
            ('fk_disputes_trip_shipment',
             'alter table public.shipment_disputes add constraint fk_disputes_trip_shipment foreign key (trip_id, shipment_id) references public.shipment_trips (id, order_id)'),
            ('fk_disputes_trip_transporter',
             'alter table public.shipment_disputes add constraint fk_disputes_trip_transporter foreign key (trip_id, transporter_user_id) references public.shipment_trips (id, transporter_user_id)'),
            ('fk_disputes_shipment_client',
             'alter table public.shipment_disputes add constraint fk_disputes_shipment_client foreign key (shipment_id, client_user_id) references public.shipments (id, client_user_id)'),
            ('fk_disputes_payment_trip',
             'alter table public.shipment_disputes add constraint fk_disputes_payment_trip foreign key (payment_id, trip_id) references public.payments (id, trip_id)'),
            ('fk_disputes_chat_exact_trip',
             'alter table public.shipment_disputes add constraint fk_disputes_chat_exact_trip foreign key (chat_thread_id, shipment_id, trip_id) references public.chat_threads (id, shipment_id, one_time_trip_id)'),
            ('fk_chat_trip_shipment',
             'alter table public.chat_threads add constraint fk_chat_trip_shipment foreign key (one_time_trip_id, shipment_id) references public.shipment_trips (id, order_id)'),
            ('ck_payments_amounts_nonneg',
             'alter table public.payments add constraint ck_payments_amounts_nonneg check (bid_price >= 0 and bid_price <> ''NaN''::numeric and company_fee >= 0 and company_fee <> ''NaN''::numeric and transporter_amount >= 0 and transporter_amount <> ''NaN''::numeric and wallet_funded_amount >= 0 and wallet_funded_amount <> ''NaN''::numeric and card_funded_amount >= 0 and card_funded_amount <> ''NaN''::numeric and processing_fee_amount >= 0 and processing_fee_amount <> ''NaN''::numeric and (total_card_charge is null or (total_card_charge >= 0 and total_card_charge <> ''NaN''::numeric)))'),
            ('ck_payments_funding_split',
             'alter table public.payments add constraint ck_payments_funding_split check (shipment_id is null or trip_id is null or status not in (''processing'', ''held'', ''released'', ''refunded'', ''disputed'') or (funding_source is not null and wallet_funded_amount + card_funded_amount = bid_price))'),
            ('ck_payments_commission_split',
             'alter table public.payments add constraint ck_payments_commission_split check (shipment_id is null or trip_id is null or status not in (''processing'', ''held'', ''released'', ''refunded'', ''disputed'') or (funding_source is not null and company_fee + transporter_amount = bid_price))'),
            ('ck_payments_total_card_charge',
             'alter table public.payments add constraint ck_payments_total_card_charge check (total_card_charge is null or (total_card_charge = card_funded_amount + processing_fee_amount))'),
            ('ck_payments_processing_percent_range',
             'alter table public.payments add constraint ck_payments_processing_percent_range check (processing_fee_percent is null or (processing_fee_percent >= 0 and processing_fee_percent < 100))'),
            ('ck_payments_snapshot_sum',
             'alter table public.payments add constraint ck_payments_snapshot_sum check (company_share_percent is null or transporter_share_percent is null or (company_share_percent + transporter_share_percent = 100))'),
            ('ck_shipments_snapshot_sum',
             'alter table public.shipments add constraint ck_shipments_snapshot_sum check (company_share_percent_snapshot is null or transporter_share_percent_snapshot is null or (company_share_percent_snapshot + transporter_share_percent_snapshot = 100))')
        ) as t(conname, ddl)
    loop
        if not exists (select 1 from pg_constraint where conname = c.conname) then
            execute c.ddl;
        end if;
    end loop;
end
$integrity$;
