-- ============================================================================
-- Migration: one-time order trip-completion lifecycle
-- Date: 2026-07-23
-- ============================================================================
-- Adds the schema needed for the canonical one-time delivery lifecycle:
--   ready_to_start -> in_progress -> awaiting_client_confirmation
--     -> completed | delivery_disputed | admin_review -> resolved_client
--
-- Payments keep their existing status vocabulary (held -> released | refunded;
-- the money stays "held" throughout a dispute / admin review). No existing
-- shipment / bid / trip / payment / wallet row is dropped or rewritten; only
-- forward-compatible columns, one dispute table, one chat linkage and a set of
-- uniqueness backstops are added.
--
-- Forward-only. Idempotent (add-if-not-exists / create-if-not-exists). Runs in
-- one transaction; any RAISE aborts and rolls everything back. Historical
-- migrations are NOT edited. schema.sql mirrors this final state.
-- ============================================================================

-- ---- 1. shipment_trips: delivery-completion + 6-hour confirmation window ----
alter table public.shipment_trips
    add column if not exists delivery_completion_requested_at timestamptz;
alter table public.shipment_trips
    add column if not exists confirmation_deadline_at timestamptz;

-- ---- 2. payments: dummy-refund audit reference -----------------------------
alter table public.payments
    add column if not exists refund_provider_reference text;

-- ---- 3. chat_threads: one-time order linkage (one thread per accepted trip)-
alter table public.chat_threads
    add column if not exists shipment_id bigint references public.shipments (id) on delete cascade;
alter table public.chat_threads
    add column if not exists one_time_trip_id bigint references public.shipment_trips (id) on delete cascade;

-- Exactly one chat thread per accepted one-time shipment. Agreement threads
-- (shipment_id null) are untouched by this partial index.
create unique index if not exists uniq_chat_thread_one_time
    on public.chat_threads (shipment_id)
    where shipment_id is not null;

-- ---- 4. one-time delivery dispute case -------------------------------------
create table if not exists public.shipment_disputes (
    id              bigint generated by default as identity primary key,
    shipment_id     bigint not null references public.shipments (id) on delete cascade,
    trip_id         bigint not null references public.shipment_trips (id) on delete cascade,
    payment_id      bigint references public.payments (id) on delete set null,
    client_user_id  bigint not null references public.users (id),
    transporter_user_id bigint not null references public.users (id),
    chat_thread_id  bigint references public.chat_threads (id) on delete set null,
    trigger         text not null
                    check (trigger in ('client_no', 'confirmation_timeout')),
    status          text not null default 'open'
                    check (status in ('open', 'resolved_transporter', 'resolved_client')),
    client_reason        text,
    transporter_statement text,
    admin_user_id   bigint references public.users (id),
    admin_notes     text,
    resolution      text
                    check (resolution is null or resolution in ('transporter_win', 'client_win')),
    resolved_at     timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- At most ONE open dispute per trip (DB-level guarantee for Phase H).
create unique index if not exists uniq_open_dispute_per_trip
    on public.shipment_disputes (trip_id)
    where status = 'open';
-- Fast admin queue + per-shipment lookups.
create index if not exists idx_disputes_status on public.shipment_disputes (status, created_at);
create index if not exists idx_disputes_shipment on public.shipment_disputes (shipment_id);

-- ---- 5. notification idempotency backstop ----------------------------------
-- One lifecycle notification per (trip, recipient, event type). Repeated
-- transitions / deadline sweeps can never fan out duplicate rows.
create unique index if not exists uniq_notification_event
    on public.shipment_notifications (trip_id, user_id, notification_type)
    where trip_id is not null;

-- ---- 6. payout / refund uniqueness backstops (no double credit) ------------
-- Transporter payout and business-wallet refund each write exactly one wallet
-- transaction per trip; the unique reference makes a second credit impossible.
create unique index if not exists uniq_wallet_lifecycle_txn
    on public.wallet_transactions (type, reference_id)
    where reference_id is not null and type in ('order_payout', 'order_refund');

-- ---- 7. keep the updated_at trigger on the new dispute table ----------------
do $trg$
begin
    if not exists (
        select 1 from pg_trigger where tgname = 'trg_shipment_disputes_updated_at'
    ) then
        execute 'create trigger trg_shipment_disputes_updated_at
                 before update on public.shipment_disputes
                 for each row execute function public.set_updated_at()';
    end if;
end
$trg$;

-- ---- 8. RLS on the dispute table (admin-all; parties read own) --------------
alter table public.shipment_disputes enable row level security;
do $rls$
begin
    if not exists (select 1 from pg_policies where tablename = 'shipment_disputes'
                   and policyname = 'admin_all_shipment_disputes') then
        execute 'create policy admin_all_shipment_disputes on public.shipment_disputes
                 for all using (public.is_admin()) with check (public.is_admin())';
    end if;
    if not exists (select 1 from pg_policies where tablename = 'shipment_disputes'
                   and policyname = 'disputes_parties_read') then
        execute 'create policy disputes_parties_read on public.shipment_disputes
                 for select using (client_user_id = public.current_app_user_id()
                                   or transporter_user_id = public.current_app_user_id())';
    end if;
end
$rls$;

-- ---- 9. backfill legacy in-flight trips/shipments to the canonical names ----
-- Known legacy statuses are remapped; unknown *active* statuses abort rather
-- than being silently guessed. Terminal / pre-flight statuses are left as-is.
do $backfill$
declare
    v_bad integer;
    v_now timestamptz := now();
begin
    -- Any held payment whose trip is in a status the new machine cannot place
    -- is irreconcilable — abort instead of guessing.
    select count(*) into v_bad
    from public.payments p
    join public.shipment_trips t on t.id = p.trip_id
    where p.status = 'held'
      and t.status not in (
          'ready_to_start', 'in_progress', 'awaiting_client_confirmation',
          'completed', 'delivery_disputed', 'admin_review', 'resolved_client',
          'delivery_claimed', 'first_response_pending', 'dispute_pending', 'accepted'
      );
    if v_bad > 0 then
        raise exception 'Aborting: % held payment(s) reference an unmappable trip status', v_bad;
    end if;

    -- Legacy trip -> canonical trip status.
    update public.shipment_trips
       set status = 'awaiting_client_confirmation',
           delivery_completion_requested_at = coalesce(delivery_completion_requested_at, trip_completed_at, v_now),
           confirmation_deadline_at = coalesce(confirmation_deadline_at,
                                               coalesce(trip_completed_at, v_now) + interval '6 hours'),
           updated_at = v_now
     where status in ('delivery_claimed', 'first_response_pending');

    update public.shipment_trips
       set status = 'admin_review', updated_at = v_now
     where status = 'dispute_pending';

    -- Mirror onto shipments that have such a trip (only when the shipment is
    -- still in a pre-terminal state, so completed/cancelled orders are safe).
    update public.shipments s
       set status = t.status, updated_at = v_now
      from public.shipment_trips t
     where t.order_id = s.id
       and t.status in ('awaiting_client_confirmation', 'admin_review')
       and s.status in ('in_progress', 'ready_to_start', 'delivery_claimed',
                        'first_response_pending', 'dispute_pending');
end
$backfill$;
