-- ============================================================================
-- Migration: versioned commission policies + Terms versions + snapshots
-- Date: 2026-07-21
-- ============================================================================
-- Adds two completely independent, versioned commission settings
-- ('one_time_order' and 'agreement'), versioned platform Terms with per-user
-- acknowledgements, commission snapshot columns on shipments/agreements, and
-- audit columns on both payment tables. Seeds both policies at 20% company /
-- 80% transporter and safely backfills every existing row to that split.
--
-- Safe to run once on the existing database. Apply with the Supabase CLI
-- (`supabase db push`) or in the SQL editor as a single transaction
-- (psql: run with -1). Idempotent guards are included so a partial re-run
-- does not duplicate seed data.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Versioned commission policies (append-only, immutable)
-- ---------------------------------------------------------------------------
create table if not exists public.commission_policies (
    id              bigint generated by default as identity primary key,
    policy_type     text not null
                    check (policy_type in ('one_time_order', 'agreement')),
    version_number  integer not null check (version_number >= 1),
    -- numeric(5,2) enforces max two decimal places at the database level
    company_share_percent     numeric(5,2) not null
                    check (company_share_percent >= 0 and company_share_percent < 100),
    transporter_share_percent numeric(5,2) not null
                    check (transporter_share_percent > 0 and transporter_share_percent <= 100),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    created_by_admin_user_id bigint references public.users (id) on delete set null,
    created_at      timestamptz not null default now(),
    constraint commission_policies_type_version_unique unique (policy_type, version_number),
    constraint commission_policies_shares_sum_100
        check (company_share_percent + transporter_share_percent = 100)
);

create index if not exists idx_commission_policies_type_version
    on public.commission_policies (policy_type, version_number desc);

-- ---------------------------------------------------------------------------
-- 2. Versioned platform Terms (append-only, immutable)
-- ---------------------------------------------------------------------------
create table if not exists public.terms_versions (
    id              bigint generated by default as identity primary key,
    version_number  integer not null unique check (version_number >= 1),
    effective_at    timestamptz not null default now(),
    change_summary  text not null check (length(trim(change_summary)) > 0),
    one_time_policy_id  bigint not null references public.commission_policies (id),
    agreement_policy_id bigint not null references public.commission_policies (id),
    published_by_admin_user_id bigint references public.users (id) on delete set null,
    published_at    timestamptz not null default now()
);

create index if not exists idx_terms_versions_version
    on public.terms_versions (version_number desc);

-- ---------------------------------------------------------------------------
-- 3. Per-user Terms acknowledgements
-- ---------------------------------------------------------------------------
create table if not exists public.terms_acknowledgements (
    id              bigint generated by default as identity primary key,
    user_id         bigint not null references public.users (id) on delete cascade,
    terms_version_id bigint not null references public.terms_versions (id) on delete cascade,
    acknowledged_at timestamptz not null default now(),
    constraint terms_ack_user_version_unique unique (user_id, terms_version_id)
);

create index if not exists idx_terms_ack_version
    on public.terms_acknowledgements (terms_version_id);

-- ---------------------------------------------------------------------------
-- 4. Immutability guard: published versions can never be edited or deleted
--    (applies to every connection, including the backend service role)
-- ---------------------------------------------------------------------------
create or replace function public.prevent_version_mutation()
returns trigger language plpgsql as $$
begin
    raise exception 'published % rows are immutable — publish a new version instead', tg_table_name;
end;
$$;

drop trigger if exists trg_commission_policies_immutable on public.commission_policies;
create trigger trg_commission_policies_immutable
    before update or delete on public.commission_policies
    for each row execute function public.prevent_version_mutation();

drop trigger if exists trg_terms_versions_immutable on public.terms_versions;
create trigger trg_terms_versions_immutable
    before update or delete on public.terms_versions
    for each row execute function public.prevent_version_mutation();

-- ---------------------------------------------------------------------------
-- 5. Commission snapshot columns
-- ---------------------------------------------------------------------------
alter table public.shipments
    add column if not exists company_share_percent_snapshot     numeric(5,2),
    add column if not exists transporter_share_percent_snapshot numeric(5,2),
    add column if not exists commission_policy_id bigint references public.commission_policies (id),
    add column if not exists terms_version_id     bigint references public.terms_versions (id);

alter table public.agreements
    add column if not exists company_share_percent_snapshot     numeric(5,2),
    add column if not exists transporter_share_percent_snapshot numeric(5,2),
    add column if not exists commission_policy_id bigint references public.commission_policies (id),
    add column if not exists terms_version_id     bigint references public.terms_versions (id);

-- Audit trail on final payment records: the split actually applied.
alter table public.payments
    add column if not exists company_share_percent     numeric(5,2),
    add column if not exists transporter_share_percent numeric(5,2),
    add column if not exists commission_policy_id bigint references public.commission_policies (id);

alter table public.agreement_monthly_payments
    add column if not exists company_share_percent     numeric(5,2),
    add column if not exists transporter_share_percent numeric(5,2),
    add column if not exists commission_policy_id bigint references public.commission_policies (id);

create index if not exists idx_shipments_commission_policy
    on public.shipments (commission_policy_id);
create index if not exists idx_agreements_commission_policy
    on public.agreements (commission_policy_id);

-- ---------------------------------------------------------------------------
-- 6. Seed: both policy types at 20% company / 80% transporter + Terms v1
-- ---------------------------------------------------------------------------
insert into public.commission_policies
    (policy_type, version_number, company_share_percent, transporter_share_percent, change_summary)
select 'one_time_order', 1, 20.00, 80.00,
       'Initial platform commission rate (20% company / 80% transporter).'
where not exists (
    select 1 from public.commission_policies where policy_type = 'one_time_order'
);

insert into public.commission_policies
    (policy_type, version_number, company_share_percent, transporter_share_percent, change_summary)
select 'agreement', 1, 20.00, 80.00,
       'Initial platform commission rate (20% company / 80% transporter).'
where not exists (
    select 1 from public.commission_policies where policy_type = 'agreement'
);

insert into public.terms_versions
    (version_number, change_summary, one_time_policy_id, agreement_policy_id)
select 1,
       'Initial platform Terms: 20% company / 80% transporter for both one-time orders and agreements.',
       (select id from public.commission_policies
         where policy_type = 'one_time_order' and version_number = 1),
       (select id from public.commission_policies
         where policy_type = 'agreement' and version_number = 1)
where not exists (select 1 from public.terms_versions);

-- ---------------------------------------------------------------------------
-- 7. Backfill existing data with the legacy 20/80 split (never retroactive:
--    these rows were all created under the hard-coded 20% fee)
-- ---------------------------------------------------------------------------
-- Shipments that already have an accepted bid (or moved past 'open') keep the
-- historical 20/80 snapshot. Still-open shipments are left NULL on purpose:
-- they snapshot the then-active policy when a bid is accepted.
update public.shipments s
set company_share_percent_snapshot     = 20.00,
    transporter_share_percent_snapshot = 80.00,
    commission_policy_id = p.id,
    terms_version_id     = t.id
from public.commission_policies p, public.terms_versions t
where p.policy_type = 'one_time_order' and p.version_number = 1
  and t.version_number = 1
  and s.company_share_percent_snapshot is null
  and (s.accepted_bid_id is not null or s.status not in ('open', 'cancelled'));

-- Every existing agreement was finalized under the hard-coded 20% fee.
update public.agreements a
set company_share_percent_snapshot     = 20.00,
    transporter_share_percent_snapshot = 80.00,
    commission_policy_id = p.id,
    terms_version_id     = t.id
from public.commission_policies p, public.terms_versions t
where p.policy_type = 'agreement' and p.version_number = 1
  and t.version_number = 1
  and a.company_share_percent_snapshot is null;

-- Completed one-time invoices: record the split that was applied.
update public.payments pay
set company_share_percent     = 20.00,
    transporter_share_percent = 80.00,
    commission_policy_id = p.id
from public.commission_policies p
where p.policy_type = 'one_time_order' and p.version_number = 1
  and pay.company_share_percent is null;

-- Agreement monthly payments: record the split that was applied.
update public.agreement_monthly_payments amp
set company_share_percent     = 20.00,
    transporter_share_percent = 80.00,
    commission_policy_id = p.id
from public.commission_policies p
where p.policy_type = 'agreement' and p.version_number = 1
  and amp.company_share_percent is null;

-- ---------------------------------------------------------------------------
-- 8. Row Level Security
--    (backend uses the service role and bypasses RLS; these protect direct
--    PostgREST/browser access)
-- ---------------------------------------------------------------------------
alter table public.commission_policies    enable row level security;
alter table public.terms_versions         enable row level security;
alter table public.terms_acknowledgements enable row level security;

-- Platform admins: full management access.
drop policy if exists admin_all_commission_policies on public.commission_policies;
create policy admin_all_commission_policies on public.commission_policies
    for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists admin_all_terms_versions on public.terms_versions;
create policy admin_all_terms_versions on public.terms_versions
    for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists admin_all_terms_acknowledgements on public.terms_acknowledgements;
create policy admin_all_terms_acknowledgements on public.terms_acknowledgements
    for all using (public.is_admin()) with check (public.is_admin());

-- Every authenticated user may read published policies and Terms.
drop policy if exists commission_policies_authenticated_read on public.commission_policies;
create policy commission_policies_authenticated_read on public.commission_policies
    for select using (auth.uid() is not null);

drop policy if exists terms_versions_authenticated_read on public.terms_versions;
create policy terms_versions_authenticated_read on public.terms_versions
    for select using (auth.uid() is not null);

-- Users manage only their own acknowledgements (insert + read; no edits).
drop policy if exists terms_ack_own_read on public.terms_acknowledgements;
create policy terms_ack_own_read on public.terms_acknowledgements
    for select using (user_id = public.current_app_user_id());

drop policy if exists terms_ack_own_insert on public.terms_acknowledgements;
create policy terms_ack_own_insert on public.terms_acknowledgements
    for insert with check (user_id = public.current_app_user_id());
