-- Mandatory one-time transporter reviews.
-- Additive and idempotent. Existing completed trips are intentionally not
-- backfilled; pending review status remains derived from completion + no row.

create table if not exists public.shipment_trip_reviews (
    id                  bigint generated by default as identity primary key,
    shipment_id         bigint not null,
    trip_id             bigint not null,
    client_user_id      bigint not null,
    transporter_user_id bigint not null,
    rating              integer not null,
    comment             text,
    created_at          timestamptz not null default now()
);

lock table public.shipment_trip_reviews in share row exclusive mode;

-- A partially created table must not be hardened around invalid data. This gate
-- also makes relationship-anomaly failures atomic and leaves every row intact.
do $$
declare
    required_nulls bigint;
    duplicate_ids bigint;
    duplicate_trips bigint;
    invalid_ratings bigint;
    invalid_comments bigint;
    shipment_client_mismatches bigint;
    trip_shipment_mismatches bigint;
    trip_transporter_mismatches bigint;
    missing_users bigint;
begin
    select count(*) into required_nulls
    from public.shipment_trip_reviews
    where id is null or shipment_id is null or trip_id is null
       or client_user_id is null or transporter_user_id is null
       or rating is null or created_at is null;

    select count(*) into duplicate_ids
    from (
        select id from public.shipment_trip_reviews
        group by id having count(*) > 1
    ) duplicates;

    select count(*) into duplicate_trips
    from (
        select trip_id from public.shipment_trip_reviews
        group by trip_id having count(*) > 1
    ) duplicates;

    select count(*) into invalid_ratings
    from public.shipment_trip_reviews
    where rating not between 1 and 5;

    select count(*) into invalid_comments
    from public.shipment_trip_reviews
    where comment is not null and length(comment) > 1000;

    select count(*) into shipment_client_mismatches
    from public.shipment_trip_reviews r
    where not exists (
        select 1 from public.shipments s
        where s.id = r.shipment_id and s.client_user_id = r.client_user_id
    );

    select count(*) into trip_shipment_mismatches
    from public.shipment_trip_reviews r
    where not exists (
        select 1 from public.shipment_trips t
        where t.id = r.trip_id and t.order_id = r.shipment_id
    );

    select count(*) into trip_transporter_mismatches
    from public.shipment_trip_reviews r
    where not exists (
        select 1 from public.shipment_trips t
        where t.id = r.trip_id
          and t.transporter_user_id = r.transporter_user_id
    );

    select count(*) into missing_users
    from public.shipment_trip_reviews r
    where not exists (select 1 from public.users u where u.id = r.client_user_id)
       or not exists (
           select 1 from public.users u where u.id = r.transporter_user_id
       );

    if required_nulls + duplicate_ids + duplicate_trips + invalid_ratings
       + invalid_comments + shipment_client_mismatches
       + trip_shipment_mismatches + trip_transporter_mismatches
       + missing_users > 0 then
        raise exception using
            errcode = '23514',
            message = format(
                'shipment_trip_reviews integrity precheck failed: '
                'required_nulls=%s, duplicate_ids=%s, duplicate_trips=%s, '
                'invalid_ratings=%s, invalid_comments=%s, '
                'shipment_client_mismatches=%s, trip_shipment_mismatches=%s, '
                'trip_transporter_mismatches=%s, missing_users=%s',
                required_nulls,
                duplicate_ids,
                duplicate_trips,
                invalid_ratings,
                invalid_comments,
                shipment_client_mismatches,
                trip_shipment_mismatches,
                trip_transporter_mismatches,
                missing_users
            );
    end if;
end $$;

alter table public.shipment_trip_reviews
    alter column id set not null,
    alter column shipment_id set not null,
    alter column trip_id set not null,
    alter column client_user_id set not null,
    alter column transporter_user_id set not null,
    alter column rating set not null,
    alter column created_at set default now(),
    alter column created_at set not null;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_pkey'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_pkey primary key (id);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_rating_check'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_rating_check
            check (rating between 1 and 5);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_comment_check'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_comment_check
            check (comment is null or length(comment) <= 1000);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_trip_unique'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_trip_unique unique (trip_id);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_shipment_client_fk'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_shipment_client_fk
            foreign key (shipment_id, client_user_id)
            references public.shipments (id, client_user_id)
            on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_trip_shipment_fk'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_trip_shipment_fk
            foreign key (trip_id, shipment_id)
            references public.shipment_trips (id, order_id)
            on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_trip_transporter_fk'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_trip_transporter_fk
            foreign key (trip_id, transporter_user_id)
            references public.shipment_trips (id, transporter_user_id)
            on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_client_user_fk'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_client_user_fk
            foreign key (client_user_id) references public.users (id)
            on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.shipment_trip_reviews'::regclass
          and conname = 'shipment_trip_reviews_transporter_user_fk'
    ) then
        alter table public.shipment_trip_reviews
            add constraint shipment_trip_reviews_transporter_user_fk
            foreign key (transporter_user_id) references public.users (id)
            on delete cascade;
    end if;
end $$;

create index if not exists idx_shipment_trip_reviews_transporter
    on public.shipment_trip_reviews (transporter_user_id, created_at desc);
create index if not exists idx_shipment_trip_reviews_client
    on public.shipment_trip_reviews (client_user_id, created_at desc);

alter table public.shipment_trip_reviews enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'shipment_trip_reviews'
          and policyname = 'admin_all_shipment_trip_reviews'
    ) then
        create policy admin_all_shipment_trip_reviews
            on public.shipment_trip_reviews for all
            using (public.is_admin()) with check (public.is_admin());
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'shipment_trip_reviews'
          and policyname = 'trip_reviews_client_read'
    ) then
        create policy trip_reviews_client_read
            on public.shipment_trip_reviews for select
            using (client_user_id = public.current_app_user_id());
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'shipment_trip_reviews'
          and policyname = 'trip_reviews_transporter_read'
    ) then
        create policy trip_reviews_transporter_read
            on public.shipment_trip_reviews for select
            using (transporter_user_id = public.current_app_user_id());
    end if;
end $$;

create or replace view public.transporter_review_aggregates
    with (security_invoker = true) as
select transporter_user_id,
       round(avg(rating)::numeric, 1) as rating_average,
       count(*)::bigint as rating_count
from public.shipment_trip_reviews
group by transporter_user_id;
